

#
#
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# start of FM.TBGLST_D._01_00_CF
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
#
#

from CF.CONSTANTS import NAMES as N
from FM import FM


_section_ = "__KEYS__"
_moduleName_ = "FM"
_sub0_ = "_02"
_sub1_ = "AX"
# ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱
_filename_ = f"""{N.MAKE_NAME(
		__SECTION__=_section_,
		__MODULE_NAME__=_moduleName_,
		__SUBD0__=_subd0_,
		__SUB0__=_sub0_,
		__SUB1__=_sub1_,
		__SUB2__=_sub2_,
)}"""  # FM/TBGLST_D/_01_00_CF.py
# ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱
_newFilename_ = f"""{N.MAKE_NAME(
		isNew_=True,
		__MODULE_NAME__=_moduleName_,
		__SUBD0__=_subd0_,
		__SUB0__=_sub0_,
		__SUB1__=_sub1_,
		__SUB2__=_sub2_,
)}"""  # FM/TBGLST_D/_01_00_CF_NEW.py
# ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱ ⟰0⟱
__ID__ = N.MAKE_ID(
		("__FILENAME__", _filename_,),  # FM/TBGLST_D/_01_00_CF.py
		("__MODULE_NAME__", _moduleName_,),  # FM
		("__NEW_FILENAME__", _newFilename_,),  # FM/TBGLST_D/_01_00_CF_NEW.py
		("__SUBD0__", _subd0_,),  # TBGLST_D
		("__SUB0__", _sub0_,),  # _01
		("__SUB1__", _sub1_,),  # 00
		("__SUB2__", _sub2_,),  # CF
)

# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * SCTN101 FMAX _DEF_
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
NOP = "NOP"  # ignore the remainder of the line
SCTNS_DEF = "SCTNS_DEF"  # define the sections <NAC><SCTN><MODULE><SUB0><SUB1><SUB2><DESCRIPTION>
SCTN0003_LAMBDA_DEF = "SCTN0003_LAMBDA_DEF"  # define a lambda function <NAC><K_EVENT_NAME><lambda str>
SCTN0003_TYPE_DEF = "SCTN0003_TYPE_DEF"  # define a fake type used in the translation dict <NAC><K_EVENT_NAME><TYPE>
SCTN0201_STR_DEF = "SCTN0201_STR_DEF"  # define a STR in SCTN0201 <NAC><K_EVENT_NAME><str>
SCTN0201_VAL_DEF = "SCTN0201_VAL_DEF"  # define a VAL in SCTN0201 <NAC><K_EVENT_NAME><VAL>
SCTN0202_OPT_ADD_HLPLN = "SCTN0202_OPT_ADD_HLPLN"  # add a line to the help for a PARM, after the comment is automatically added<NAC><PARM><ADDONHELPLINE>
SCTN0202_OPT_STR_ADD = "SCTN0202_OPT_STR_ADD"  # define a '-a[=]' in SCTN22 <NAC><PARM><KEY><VAL>
SCTN0202_OPT_VAL_ADD = "SCTN0202_OPT_VAL_ADD"  # define a '-a[=]' in SCTN22 <NAC><PARM><KEY><VAL>
SCTN0202_OPTDICT_STR_ADD = "SCTN0202_OPTDICT_STR_ADD"  # define a OPTNAME: 'str' in SCTN0202 <NAC><KEY><PARM><STRDEFAULT>
SCTN0202_OPTDICT_VAL_ADD = "SCTN0202_OPTDICT_VAL_ADD"  # define a OPTNAME: VAL in SCTN0202 <NAC><KEY><PARM><VALDEFAULT>
SCTN0203_DICT_DEF = "SCTN0203_DICT_DEF"  # define a dict in SCTN203 <NAC><DICTNAME><DICTMODE>
SCTN0203_DICT_VS_ADD = "SCTN0203_DICT_VS_ADD"  # define a dict STR in SCTN203 <NAC><DICTNAME><STR>
SCTN0203_DICT_VV_ADD = "SCTN0203_DICT_VV_ADD"  # define a dict VAL in SCTN203 <NAC><DICTNAME><VAL>
SCTN0204_LIST_DEF = "SCTN0204_LIST_DEF"  # define a list in SCTN204 <NAC><LISTNAME>
SCTN0204_LIST_STR_ADD = "SCTN0204_LIST_STR_ADD"  # define a list STR in SCTN204 <NAC><LISTNAME><STR>
SCTN0204_LIST_VAL_ADD = "SCTN0204_LIST_VAL_ADD"  # define a VAL in a list in SCTN204 <NAC><LISTNAME><VAL>
SCTN0101_AX_DEF = "SCTN0101_AX_DEF"  # define a new FM action <NAC>
SCTN0102_STR_DEF = "SCTN0102_STR_DEF"  # define a FM string <NAC><VALNAME><STR>
SCTN0102_VAL_DEF = "SCTN0102_VAL_DEF"  # define a FM _value_ <NAC><VALNAME><VAL>
SCTN0103_DICT_DEF = "SCTN0103_DICT_DEF"  # define a dict for FM <NAC><DICTNAME>
SCTN0104_LIST_DEF = "SCTN0104_LIST_DEF"  # define a list in FM <NAC><LISTNAME>
SCTN0104_LIST_STR_ADD = "SCTN0104_LIST_STR_ADD"  # define a list in FM <NAC>
SCTN0104_LIST_VAL_ADD = "SCTN0104_LIST_VAL_ADD"  # define a list in FM <NAC>
SCTN0105_LDICT_DEF = "SCTN0105_LDICT_DEF"  # define a dict for FM <NAC>
SCTN0105_LDICT_VS_ADD = "SCTN0105_LDICT_VS_ADD"  # define a dict for FM <NAC>
SCTN0105_LDICT_VV_ADD = "SCTN0105_LDICT_VV_ADD"  # define a dict for FM <NAC>
SCTN0106_SCTN_DEF = "SCTN0106_SCTN_DEF"  # define the SCTN all over the place <NAC><SCTNNAME><DESCRIPTION0>
SCTN0900_STR_DEF = "SCTN0900_STR_DEF"  # define a string in the first section (colors, etc.) of defines in PSG.py <NAC><VALNAME><VAL>
SCTN0900_VAL_DEF = "SCTN0900_VAL_DEF"  # define a value in the first define section in PSG.py <NAC><VALNAME><VAL>
SCTN0901_DUBLT_SS_DEF = "SCTN0901_DUBLT_SS_DEF"  # define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>
SCTN0901_DUBLT_SV_DEF = "SCTN0901_DUBLT_SV_DEF"  # define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>
SCTN0901_DUBLT_VS_DEF = "SCTN0901_DUBLT_VS_DEF"  # define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>
SCTN0901_DUBLT_VV_DEF = "SCTN0901_DUBLT_VV_DEF"  # define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>
SCTN0901_KEY_DEF = "SCTN0901_KEY_DEF"  # define a key in the second section of defines in PSG.py <NAC><VALNAME>
SCTN0901_STR_DEF = "SCTN0901_STR_DEF"  # define a string in the second section of defines in PSG.py <NAC><VALNAME><VAL>
SCTN0901_VAL_DEF = "SCTN0901_VAL_DEF"  # define a value in the second define section in PSG.py <NAC><VALNAME><VAL>
SCTN0902_DICT_DEF = "SCTN0902_DICT_DEF"  # define a dict in PSG <NAC><DICTNAME>
SCTN0902_DICT_SS_ADD = "SCTN0902_DICT_SS_ADD"  # add a str-str to a dict <NAC><DICTNAME><STR><STR>
SCTN0902_DICT_SV_ADD = "SCTN0902_DICT_SV_ADD"  # add a str-val to a dict <NAC><DICTNAME><STR><VAL>
SCTN0902_DICT_VS_ADD = "SCTN0902_DICT_VS_ADD"  # add a str to a dict <NAC><DICTNAME><KEY><VAL>
SCTN0902_DICT_VV_ADD = "SCTN0902_DICT_VV_ADD"  # add a val to a dict in PSG <NAC><DICTNAME><KEY><VAL>
SCTN0903_LIST_DEF = "SCTN0903_LIST_DEF"  # define a list in PSG <NAC><LISTNAME>
SCTN0903_LIST_STR_ADD = "SCTN0903_LIST_STR_ADD"  # add a str to a list in PSG <NAC><LISTNAME><STR>
SCTN0903_LIST_VAL_ADD = "SCTN0903_LIST_VAL_ADD"  # add a val to a list in PSG <NAC><LISTNAME><VAL>
SCTN0904_PLATEQ_ELIF_ADD = "SCTN0904_PLATEQ_ELIF_ADD"  # platform equalizer define an elif <NAC><STRUCTNAME><CONDITION><VAL>
SCTN0904_PLATEQ_ELSE_ADD = "SCTN0904_PLATEQ_ELSE_ADD"  # platform equalizer define an else <NAC><STRUCTNAME><CONDITION>
SCTN0904_PLATEQ_FUNC_STR_ADD = "SCTN0904_PLATEQ_FUNC_STR_ADD"  # add a function string line <NAC><STRUCTNAME><CONDITION>
SCTN0904_PLATEQ_IF_ADD = "SCTN0904_PLATEQ_IF_ADD"  # add the 1st if to a platform equalizer <NAC><STRUCTNAME><CONDITION>
SCTN0904_PLATEQ_PLAT_DEF = "SCTN0904_PLATEQ_PLAT_DEF"  # define a platform equalizer struct <NAC><STRUCTNAME>
SCTN0904_PLATEQ_STR_ADD = "SCTN0904_PLATEQ_STR_ADD"  # add a string to a PLATEQ <NAC><STRUCTNAME><VALNAME><VAL>
SCTN0904_PLATEQ_VAL_ADD = "SCTN0904_PLATEQ_VAL_ADD"  # add a value to a PLATEQ <NAC><STRUCTNAME><VALNAME><VAL>
SCTN0905_TDD_VS_ADD = "SCTN0905_TDD_VS_ADD"  # define a ddict <NAC><TUPDICTNAME><KEY><VAL><DDICTKEY>
SCTN0905_TDD_VV_ADD = "SCTN0905_TDD_VV_ADD"  # define a ddict <NAC><TUPDICTNAME><KEY><VAL><DDICTKEY>
SCTN0905_TUPDICT_DDICT_DEF = "SCTN0905_TUPDICT_DDICT_DEF"  # define a ddict <NAC><TUPDICTNAME><KEY><DDICTKEY>
SCTN0905_TUPDICT_DEF = "SCTN0905_TUPDICT_DEF"  # define a TUPDICT in the second define section in PSG.py <NAC><TUPDICTNAME>
SCTN0905_TUPDICT_DICT_ADD = "SCTN0905_TUPDICT_DICT_ADD"  # add a value to a tupdict <NAC><TUPDICTNAME><KEY><VAL>
SCTN0905_TUPDICT_SS_ADD = "SCTN0905_TUPDICT_SS_ADD"  # add a str to a tupdict <NAC><TUPDICTNAME><STR><STR>
SCTN0905_TUPDICT_SV_ADD = "SCTN0905_TUPDICT_SV_ADD"  # add a value to a tupdict <NAC><TUPDICTNAME><STR><VAL>
SCTN0905_TUPDICT_VS_ADD = "SCTN0905_TUPDICT_VS_ADD"  # add a str to a tupdict <NAC><TUPDICTNAME><KEY><STR>
SCTN0905_TUPDICT_VV_ADD = "SCTN0905_TUPDICT_VV_ADD"  # add a value to a tupdict <NAC><TUPDICTNAME><KEY><VAL>
SCTN0906_BTN_DEF = "SCTN0906_BTN_DEF"  # define a button <NAC><BTNNAME>
SCTN0906_BTN_STR_ADD = "SCTN0906_BTN_STR_ADD"  # add a (VAL,VAL) to a tupdict <NAC><BTNNAME><KEY><VAL>
SCTN0906_BTN_VAL_ADD = "SCTN0906_BTN_VAL_ADD"  # add a (VAL,VAL) to a tupdict <NAC><BTNNAME><KEY><VAL>
SCTN0907_SPIN_DEF = "SCTN0907_SPIN_DEF"  # define a spin box entry <NAC><SPINNAME>
SCTN0907_SPIN_DICT_STR_ADD = "SCTN0907_SPIN_DICT_STR_ADD"  # add a STR to the SPINDICT <NAC><SPINNAME><KEY><STR>
SCTN0907_SPIN_DICT_VAL_ADD = "SCTN0907_SPIN_DICT_VAL_ADD"  # add a VAL to the SPINDICT <NAC><SPINNAME><KEY><VAL>
SCTN0907_SPIN_VALUES_STR_ADD = "SCTN0907_SPIN_VALUES_STR_ADD"  # add a STR to the values list <NAC><SPINNAME><STR>
SCTN0907_SPIN_VALUES_VAL_ADD = "SCTN0907_SPIN_VALUES_VAL_ADD"  # add a VAL to the values list <NAC><SPINNAME><VAL>
SCTN0908_CHECKBOX_DEF = "SCTN0908_CHECKBOX_DEF"  # define a checkbox <NAC><CHECKBOXNAME>
SCTN0908_CHECKBOX_STR_ADD = "SCTN0908_CHECKBOX_STR_ADD"  # add a str to a checkbox <NAC><CHECKBOXNAME><KEY><VAL>
SCTN0908_CHECKBOX_VAL_ADD = "SCTN0908_CHECKBOX_VAL_ADD"  # add a val to a checkbox <NAC><CHECKBOXNAME><KEY><VAL>
SCTN0909_TEXT_DEF = "SCTN0909_TEXT_DEF"  # define a text <NAC><TEXTNAME>
SCTN0909_TEXT_STR_ADD = "SCTN0909_TEXT_STR_ADD"  # add a str to a text element <NAC><TEXTNAME><KEY><VAL>
SCTN0909_TEXT_VAL_ADD = "SCTN0909_TEXT_VAL_ADD"  # add a val to a text element <NAC><TEXTNAME>
SCTN090A_RADIO_DEF = "SCTN090A_RADIO_DEF"  # define a radio button element
SCTN090B_COLUMN_BUTTON_ADD = "SCTN090B_COLUMN_BUTTON_ADD"  # add a button to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN090B_COLUMN_CHECKBOX_ADD = "SCTN090B_COLUMN_CHECKBOX_ADD"  # add a combo to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN090B_COLUMN_COLUMN_ADD = "SCTN090B_COLUMN_COLUMN_ADD"  # add a column to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN090B_COLUMN_COLUMN_PARM_STR_ADD = "SCTN090B_COLUMN_COLUMN_PARM_STR_ADD"  # add a column parm to the column to a row <NAC><COLUMNNAME>[ROWKEY]<LEVEL><KEY><VAL>
SCTN090B_COLUMN_COLUMN_PARM_VAL_ADD = "SCTN090B_COLUMN_COLUMN_PARM_VAL_ADD"  # add a column parm to the column to a row <NAC><COLUMNNAME>[ROWKEY]<LEVEL><KEY><VAL>
SCTN090B_COLUMN_COMBO_ADD = "SCTN090B_COLUMN_COMBO_ADD"  # add a combo to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN090B_COLUMN_DEF = "SCTN090B_COLUMN_DEF"  # define a column <NAC><COLUMNNAME>
SCTN090B_COLUMN_KEY_ADD = "SCTN090B_COLUMN_KEY_ADD"  # add a key to a column element 'key=' will be added automatically <NAC><COLUMNNAME><ROWKEY><ELEMENTKEY><VAL>
SCTN090B_COLUMN_PACKEDPARM_ADD = "SCTN090B_COLUMN_PACKEDPARM_ADD"  # add packedparms to a column entry <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
SCTN090B_COLUMN_PARM_ADD = "SCTN090B_COLUMN_PARM_ADD"  # add parms to a column entry <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
SCTN090B_COLUMN_RADIO_ADD = "SCTN090B_COLUMN_RADIO_ADD"  # add a radio to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN090B_COLUMN_ROW_ADD = "SCTN090B_COLUMN_ROW_ADD"  # add a row [] to a column <NAC><COLUMNNAME><ROWKEY><LEVEL>
SCTN090B_COLUMN_SPIN_ADD = "SCTN090B_COLUMN_SPIN_ADD"  # add a spinbox to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN090B_COLUMN_TEXT_ADD = "SCTN090B_COLUMN_TEXT_ADD"  # add a text element to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN090C_APPDS_DEF = "SCTN090C_APPDS_DEF"  # add a nested dict holding all of the variables passed between PySimpleGUI and this app
SCTN090C_APPDS_DICT_DEF = "SCTN090C_APPDS_DICT_DEF"  # add a dict to the mainapp dict <NAC><DICTNAME
SCTN090C_APPDS_DICT_VS_ADD = "SCTN090C_APPDS_DICT_VS_ADD"  # add a string to a dict mainapp dict <NAC><DICTNAME><KEY><STR>
SCTN090C_APPDS_DICT_VV_ADD = "SCTN090C_APPDS_DICT_VV_ADD"  # add a value to a dict mainapp dict <NAC><DICTNAME><KEY><VAL>
SCTN090C_APPDS_VS_ADD = "SCTN090C_APPDS_VS_ADD"  # add a string to the mainapp dict <NAC><KEY><STR>
SCTN090C_APPDS_VV_ADD = "SCTN090C_APPDS_VV_ADD"  # add a value to the mainapp dict <NAC><KEY><VAL>
SCTN090D_FORMMAIN_DEF = "SCTN090D_FORMMAIN_DEF"  # define a frame <NAC><FRAMENAME><_WINDOW_><FINALIZEBOOL> (** added automatically bool adds or not chained finalize() call)
SCTN090E_LAYOUT_BUTTON_ADD = "SCTN090E_LAYOUT_BUTTON_ADD"  # add a button to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN090E_LAYOUT_CHECKBOX_ADD = "SCTN090E_LAYOUT_CHECKBOX_ADD"  # add a checkbox to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN090E_LAYOUT_COLUMN_ADD = "SCTN090E_LAYOUT_COLUMN_ADD"  # add a column to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN090E_LAYOUT_COMBO_ADD = "SCTN090E_LAYOUT_COMBO_ADD"  # add a combo to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN090E_LAYOUT_DEF = "SCTN090E_LAYOUT_DEF"  # define a layout <NAC><LAYOUTNAME>
SCTN090E_LAYOUT_KEY_ADD = "SCTN090E_LAYOUT_KEY_ADD"  # add a key to a layout element 'key=' will be added automatically <NAC><LAYOUTNAME><ROWKEY><ELEMENTKEY><VAL>
SCTN090E_LAYOUT_PACKEDPARM_ADD = "SCTN090E_LAYOUT_PACKEDPARM_ADD"  # add packedparms to a layout entry <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
SCTN090E_LAYOUT_PARM_VAL_ADD = "SCTN090E_LAYOUT_PARM_VAL_ADD"  # add parms to a layout entry <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
SCTN090E_LAYOUT_RADIO_ADD = "SCTN090E_LAYOUT_RADIO_ADD"  # add a radio to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN090E_LAYOUT_ROW_ADD = "SCTN090E_LAYOUT_ROW_ADD"  # add a row [] to a layout <NAC><LAYOUTNAME><ROWKEY><LEVEL>
SCTN090E_LAYOUT_SPIN_ADD = "SCTN090E_LAYOUT_SPIN_ADD"  # add a spinbox to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN090E_LAYOUT_TEXT_ADD = "SCTN090E_LAYOUT_TEXT_ADD"  # add a text element to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN090F_WINDOW_DEF = "SCTN090F_WINDOW_DEF"  # define a window element <NAC><WINDOWNAME>
SCTN090F_WINDOW_STR_ADD = "SCTN090F_WINDOW_STR_ADD"  # add a str to the window element <NAC><WINDOWNAME><VALNAME><VAL>
SCTN090F_WINDOW_VAL_ADD = "SCTN090F_WINDOW_VAL_ADD"  # add a str to the window element <NAC><WINDOWNAME><VALNAME><VAL>
SCTN0910_DUBLT_SS_DEF = "SCTN0910_DUBLT_SS_DEF"  # define a (x,y) tuple <NAC><DUBTUPNAME><VAL1><VAL2>
SCTN0910_DUBLT_SV_DEF = "SCTN0910_DUBLT_SV_DEF"  # define a (x,y) tuple <NAC><DUBTUPNAME><VAL1><VAL2>
SCTN0910_DUBLT_VS_DEF = "SCTN0910_DUBLT_VS_DEF"  # define a (x,y) tuple <NAC><DUBTUPNAME><VAL1><VAL2>
SCTN0910_DUBLT_VV_DEF = "SCTN0910_DUBLT_VV_DEF"  # define a (x,y) tuple <NAC><DUBTUPNAME><VAL1><VAL2>
SCTN0910_STR_DEF = "SCTN0910_STR_DEF"  # define a string in the second section of defines in PSG.py <NAC><VALNAME><VAL>
SCTN0910_VAL_DEF = "SCTN0910_VAL_DEF"  # define a value in the second define section in PSG.py <NAC><VALNAME><VAL>
SCTN0911_COMBO_DEF = "SCTN0911_COMBO_DEF"  # define a combo box <NAC><COMBOBOXNAME>
SCTN0912_FRAMEELEMENT_DEF = "SCTN0912_FRAMEELEMENT_DEF"  # define a frame element <NAC><FENAME>
SCTN0913_RCMENU_DEF = "SCTN0913_RCMENU_DEF"  # define a right click menu <NAC><RCMENUNAME>
SCTN0913_RCMENU_VAL_ADD = "SCTN0913_RCMENU_VAL_ADD"  # define a right click menu <NAC><RCMENUNAME><VAL>
SCTN0914_FORMPOPUP_DEF = "SCTN0914_FORMPOPUP_DEF"  # define a frame <NAC><FRAMENAME><_WINDOW_><FINALIZEBOOL> (** added automatically bool adds or not chained finalize() call)
SCTN0915_PUDLG_DEF = "SCTN0915_PUDLG_DEF"  # define a popup dialog <NAC><POPUPNAME><POPUPTYPE>
SCTN0915_PUDLG_DICT_STR_ADD = "SCTN0915_PUDLG_DICT_STR_ADD"  # add a str to a text element <NAC><POPUPNAME><KEY><VAL>
SCTN0915_PUDLG_DICT_VAL_ADD = "SCTN0915_PUDLG_DICT_VAL_ADD"  # add a val to a text element <NAC><POPUPNAME><KEY><VAL>
SCTN0915_PUDLG_LIST_STR_ADD = "SCTN0915_PUDLG_LIST_STR_ADD"  # add a str to a text element <NAC><POPUPNAME><KEY><VAL>
SCTN0915_PUDLG_LIST_VAL_ADD = "SCTN0915_PUDLG_LIST_VAL_ADD"  # add a val to a text element <NAC><POPUPNAME><KEY><VAL>
SCTN0916_KEY0_DEF = "SCTN0916_KEY0_DEF"  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><KEY>
SCTN0916_KEY1_DEF = "SCTN0916_KEY1_DEF"  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><SUB1><KEY>
SCTN0916_KEY2_DEF = "SCTN0916_KEY2_DEF"  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><SUB1><SUB2><KEY>
SCTN0916_KEY_DEF = "SCTN0916_KEY_DEF"  # put a key in def1 of PSG.py <NAC><KEYGROUP><KEY>
SCTN0916_KEYSTR0_DEF = "SCTN0916_KEYSTR0_DEF"  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><KEY><VAL>
SCTN0916_KEYSTR1_DEF = "SCTN0916_KEYSTR1_DEF"  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><SUB1><KEY><VAL>
SCTN0916_KEYSTR2_DEF = "SCTN0916_KEYSTR2_DEF"  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><SUB1><SUB2><KEY><VAL>
SCTN0916_KEYSTR_DEF = "SCTN0916_KEYSTR_DEF"  # put a key in def1 of PSG.py <NAC><KEYGROUP><KEY><VAL>
SCTN09FF_BTN_DEF = "SCTN09FF_BTN_DEF"  # define a button <NAC><CLASSNAME><BTNNAME>
SCTN09FF_BTN_STR_ADD = "SCTN09FF_BTN_STR_ADD"  # add a (VAL,VAL) to a tupdict <NAC><CLASSNAME><BTNNAME><KEY><VAL>
SCTN09FF_BTN_VAL_ADD = "SCTN09FF_BTN_VAL_ADD"  # add a (VAL,VAL) to a tupdict <NAC><CLASSNAME><BTNNAME><KEY><VAL>
SCTN09FF_CHECKBOX_DEF = "SCTN09FF_CHECKBOX_DEF"  # define a checkbox <NAC><CLASSNAME><CHECKBOXNAME>
SCTN09FF_CHECKBOX_PARM_ADD = "SCTN09FF_CHECKBOX_PARM_ADD"  # add a parameter to a checkbox <NAC><CLASSNAME><CHECKBOXNAME><VAL>
SCTN09FF_CHECKBOX_STR_ADD = "SCTN09FF_CHECKBOX_STR_ADD"  # add a str to a checkbox <NAC><CLASSNAME><CHECKBOXNAME><KEY><VAL>
SCTN09FF_CHECKBOX_VAL_ADD = "SCTN09FF_CHECKBOX_VAL_ADD"  # add a val to a checkbox <NAC><CLASSNAME><CHECKBOXNAME><KEY><VAL>
SCTN09FF_COLUMN_BUTTON_ADD = "SCTN09FF_COLUMN_BUTTON_ADD"  # add a button to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN09FF_COLUMN_CHECKBOX_ADD = "SCTN09FF_COLUMN_CHECKBOX_ADD"  # add a combo to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN09FF_COLUMN_COLUMN_ADD = "SCTN09FF_COLUMN_COLUMN_ADD"  # add a column to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN09FF_COLUMN_COLUMN_PARM_STR_ADD = "SCTN09FF_COLUMN_COLUMN_PARM_STR_ADD"  # add a column parm to the column to a row <NAC><CLASSNAME><COLUMNNAME>[ROWKEY]<LEVEL><KEY><VAL>
SCTN09FF_COLUMN_COLUMN_PARM_VAL_ADD = "SCTN09FF_COLUMN_COLUMN_PARM_VAL_ADD"  # add a column parm to the column to a row <NAC><CLASSNAME><COLUMNNAME>[ROWKEY]<LEVEL><KEY><VAL>
SCTN09FF_COLUMN_COMBO_ADD = "SCTN09FF_COLUMN_COMBO_ADD"  # add a combo to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN09FF_COLUMN_DEF = "SCTN09FF_COLUMN_DEF"  # define a column <NAC><CLASSNAME><COLUMNNAME>
SCTN09FF_COLUMN_GROUP_DEF = "SCTN09FF_COLUMN_GROUP_DEF"  # define a column group <NAC><CLASSNAME><COLUMNGROUP>
SCTN09FF_COLUMN_KEY_ADD = "SCTN09FF_COLUMN_KEY_ADD"  # add a key to a column element 'key=' will be added automatically <NAC><CLASSNAME><COLUMNNAME><ROWKEY><ELEMENTKEY><VAL>
SCTN09FF_COLUMN_PACKEDPARM_ADD = "SCTN09FF_COLUMN_PACKEDPARM_ADD"  # add packedparms to a column entry <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
SCTN09FF_COLUMN_PARM_ADD = "SCTN09FF_COLUMN_PARM_ADD"  # add parms to a column entry <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
SCTN09FF_COLUMN_RADIO_ADD = "SCTN09FF_COLUMN_RADIO_ADD"  # add a radio to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN09FF_COLUMN_ROW_ADD = "SCTN09FF_COLUMN_ROW_ADD"  # add a row [] to a column <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL>
SCTN09FF_COLUMN_SPIN_ADD = "SCTN09FF_COLUMN_SPIN_ADD"  # add a spinbox to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN09FF_COLUMN_TEXT_ADD = "SCTN09FF_COLUMN_TEXT_ADD"  # add a text element to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN09FF_COMBO_DEF = "SCTN09FF_COMBO_DEF"  # define a combo box <NAC><COMBOBOXNAME>
SCTN09FF_DEF = "SCTN09FF_DEF"  # define a class <NAC><CLASSNAME>
SCTN09FF_DICT_DEF = "SCTN09FF_DICT_DEF"  # define a dict in PSG <NAC><CLASSNAME><DICTNAME>
SCTN09FF_DICT_SS_ADD = "SCTN09FF_DICT_SS_ADD"  # add a str-str to a dict <NAC><CLASSNAME><DICTNAME><STR><STR>
SCTN09FF_DICT_SV_ADD = "SCTN09FF_DICT_SV_ADD"  # add a str-val to a dict <NAC><CLASSNAME><DICTNAME><STR><VAL>
SCTN09FF_DICT_VS_ADD = "SCTN09FF_DICT_VS_ADD"  # add a str to a dict <NAC><CLASSNAME><DICTNAME><KEY><VAL>
SCTN09FF_DICT_VV_ADD = "SCTN09FF_DICT_VV_ADD"  # add a val to a dict in PSG <NAC><CLASSNAME><DICTNAME><KEY><VAL>
SCTN09FF_DPD_DEF = "SCTN09FF_DPD_DEF"  # define a DPD debugPrintDict in PSG <NAC><CLASSNAME><DPDNAME>
SCTN09FF_DPD_VV_ADD = "SCTN09FF_DPD_VV_ADD"  # add a val to a DPD debugPrintDict in PSG <NAC><CLASSNAME><DPDNAME><KEY><VAL>
SCTN09FF_FORMMAIN_DEF = "SCTN09FF_FORMMAIN_DEF"  # define a class mainframe
SCTN09FF_FORMPOPUP_DEF = "SCTN09FF_FORMPOPUP_DEF"  # define a class mainframe
SCTN09FF_FRAMEELEMENT_DEF = "SCTN09FF_FRAMEELEMENT_DEF"  # define a frame element
SCTN09FF_FUNCTION_BLANKLINE = "SCTN09FF_FUNCTION_BLANKLINE"  # define a class <NAC><CLASSNAME><FUNCNAME><PARMS>
SCTN09FF_FUNCTION_DEF = "SCTN09FF_FUNCTION_DEF"  # define a class <NAC><CLASSNAME><FUNCNAME><PARMS>
SCTN09FF_FUNCTION_DEF_FROM_FILE = "SCTN09FF_FUNCTION_DEF_FROM_FILE"  # define a class <NAC><CLASSNAME><FUNCNAME><FILENAME>
SCTN09FF_FUNCTION_LAMBDA1_DEF = "SCTN09FF_FUNCTION_LAMBDA1_DEF"  # add a lambda to the top of a function, usually for absorbing things
SCTN09FF_FUNCTION_LAMBDA2_DEF = "SCTN09FF_FUNCTION_LAMBDA2_DEF"  # add a lambda to the top of a function, usually for absorbing things
SCTN09FF_FUNCTION_LINE_ADD = "SCTN09FF_FUNCTION_LINE_ADD"  # define a class <NAC><CLASSNAME><FUNCNAME><LINE>
SCTN09FF_FUNCTION_READ_FROM_FILE = "SCTN09FF_FUNCTION_READ_FROM_FILE"  # define a class <NAC><CLASSNAME><FUNCNAME><FILENAME>
SCTN09FF_FUNCTION_STR1_DEF = "SCTN09FF_FUNCTION_STR1_DEF"  # define a string in the class <NAC><CLASSNAME><FUNCNAME><VALNAME><VAL>
SCTN09FF_FUNCTION_STR2_DEF = "SCTN09FF_FUNCTION_STR2_DEF"  # define a string in the class <NAC><CLASSNAME><FUNCNAME><VALNAME><VAL>
SCTN09FF_FUNCTION_VAL1_DEF = "SCTN09FF_FUNCTION_VAL1_DEF"  # define a value in the class <NAC><CLASSNAME><FUNCNAME><VALNAME><VAL>
SCTN09FF_FUNCTION_VAL2_DEF = "SCTN09FF_FUNCTION_VAL2_DEF"  # define a value in the class <NAC><CLASSNAME><FUNCNAME><VALNAME><VAL>
SCTN09FF_GROUP_SELECT = "SCTN09FF_GROUP_SELECT"  # define a column group default <NAC><CLASSNAME><GROUPNAME><GROUPVALUE>
SCTN09FF_INIT_ADD1_LAMBDA = "SCTN09FF_INIT_ADD1_LAMBDA"  # define a string in the class <NAC><CLASSNAME><VALNAME><VAL>
SCTN09FF_INIT_ADD1_LINE = "SCTN09FF_INIT_ADD1_LINE"  # define a class <NAC><CLASSNAME><LINE>
SCTN09FF_INIT_ADD1_READ_FROM_FILE = "SCTN09FF_INIT_ADD1_READ_FROM_FILE"  # read a section of __init__ from a file in res/functions <NAC><CLASSNAME><FILENAME>
SCTN09FF_INIT_ADD1_STR = "SCTN09FF_INIT_ADD1_STR"  # define a string in the class <NAC><CLASSNAME><VALNAME><VAL>
SCTN09FF_INIT_ADD1_VAL = "SCTN09FF_INIT_ADD1_VAL"  # define a value in the class <NAC><CLASSNAME><VALNAME><VAL>
SCTN09FF_INIT_ADD2_DICTIN_SS = "SCTN09FF_INIT_ADD2_DICTIN_SS"  # add a str-str to a dict <NAC><CLASSNAME><STR><STR>
SCTN09FF_INIT_ADD2_DICTIN_SV = "SCTN09FF_INIT_ADD2_DICTIN_SV"  # add a str-val to a dict <NAC><CLASSNAME><STR><VAL>
SCTN09FF_INIT_ADD2_DICTIN_VS = "SCTN09FF_INIT_ADD2_DICTIN_VS"  # add a str to a dict <NAC><CLASSNAME><KEY><VAL>
SCTN09FF_INIT_ADD2_DICTIN_VV = "SCTN09FF_INIT_ADD2_DICTIN_VV"  # add a val to a dict in PSG <NAC><CLASSNAME><KEY><VAL>
SCTN09FF_INIT_ADD2_FOREIGN_KEY = "SCTN09FF_INIT_ADD2_FOREIGN_KEY"  # add values to _DICT_KEYS, _DICT_KEYS_REVERSE_ for external elements like buttons and checkboxes <NAC><CLASSNAME><KEY>
SCTN09FF_INIT_ADD2_LAMBDA = "SCTN09FF_INIT_ADD2_LAMBDA"  # define a value in the class <NAC><CLASSNAME><VALNAME><VAL>
SCTN09FF_INIT_ADD2_LINE = "SCTN09FF_INIT_ADD2_LINE"  # define a class <NAC><CLASSNAME><LINE>
SCTN09FF_INIT_ADD2_READ_FROM_FILE = "SCTN09FF_INIT_ADD2_READ_FROM_FILE"  # read a section of __init__ from a file in res/functions <NAC><CLASSNAME><FILENAME>
SCTN09FF_INIT_ADD2_STR = "SCTN09FF_INIT_ADD2_STR"  # define a string in the class <NAC><CLASSNAME><VALNAME><VAL>
SCTN09FF_INIT_ADD2_VAL = "SCTN09FF_INIT_ADD2_VAL"  # define a value in the class <NAC><CLASSNAME><VALNAME><VAL>
SCTN09FF_INIT_ADD3_LINE = "SCTN09FF_INIT_ADD3_LINE"  # define a class <NAC><CLASSNAME><LINE>
SCTN09FF_INIT_DEF = "SCTN09FF_INIT_DEF"  # define a class <NAC><CLASSNAME><PARMS>
SCTN09FF_LAYOUT_BUTTON_ADD = "SCTN09FF_LAYOUT_BUTTON_ADD"  # add a button to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN09FF_LAYOUT_CHECKBOX_ADD = "SCTN09FF_LAYOUT_CHECKBOX_ADD"  # add a checkbox to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN09FF_LAYOUT_COLUMN_ADD = "SCTN09FF_LAYOUT_COLUMN_ADD"  # add a column to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN09FF_LAYOUT_COMBO_ADD = "SCTN09FF_LAYOUT_COMBO_ADD"  # add a combo to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN09FF_LAYOUT_DEF = "SCTN09FF_LAYOUT_DEF"  # define layouts
SCTN09FF_LAYOUT_KEY_ADD = "SCTN09FF_LAYOUT_KEY_ADD"  # add a key to a layout element 'key=' will be added automatically <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><ELEMENTKEY><VAL>
SCTN09FF_LAYOUT_PACKEDPARM_ADD = "SCTN09FF_LAYOUT_PACKEDPARM_ADD"  # add packedparms to a layout entry <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
SCTN09FF_LAYOUT_PARM_VAL_ADD = "SCTN09FF_LAYOUT_PARM_VAL_ADD"  # add parms to a layout entry <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
SCTN09FF_LAYOUT_RADIO_ADD = "SCTN09FF_LAYOUT_RADIO_ADD"  # add a radio to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN09FF_LAYOUT_ROW_ADD = "SCTN09FF_LAYOUT_ROW_ADD"  # add a row [] to a layout <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL>
SCTN09FF_LAYOUT_SPIN_ADD = "SCTN09FF_LAYOUT_SPIN_ADD"  # add a spinbox to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN09FF_LAYOUT_TEXT_ADD = "SCTN09FF_LAYOUT_TEXT_ADD"  # add a text element to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
SCTN09FF_LIST_DEF = "SCTN09FF_LIST_DEF"  # define a list in PSG <NAC><CLASSNAME><LISTNAME>
SCTN09FF_LIST_STR_ADD = "SCTN09FF_LIST_STR_ADD"  # add a str to a list in PSG <NAC><CLASSNAME><LISTNAME><STR>
SCTN09FF_LIST_VAL_ADD = "SCTN09FF_LIST_VAL_ADD"  # add a val to a list in PSG <NAC><CLASSNAME><LISTNAME><VAL>
SCTN09FF_RADIO_DEF = "SCTN09FF_RADIO_DEF"  # define a radio button element
SCTN09FF_RCMENU_DEF = "SCTN09FF_RCMENU_DEF"  # define a right click menu
SCTN09FF_RCMENU_VAL_ADD = "SCTN09FF_RCMENU_VAL_ADD"  # define a right click menu
SCTN09FF_SPIN_DEF = "SCTN09FF_SPIN_DEF"  # define a spin box entry <NAC><CLASSNAME><SPINNAME>
SCTN09FF_SPIN_DICT_VS_ADD = "SCTN09FF_SPIN_DICT_VS_ADD"  # add a STR to the SPINDICT <NAC><CLASSNAME><SPINNAME><KEY><STR>
SCTN09FF_SPIN_DICT_VV_ADD = "SCTN09FF_SPIN_DICT_VV_ADD"  # add a VAL to the SPINDICT <NAC><CLASSNAME><SPINNAME><KEY><VAL>
SCTN09FF_SPIN_LIST_STR_ADD = "SCTN09FF_SPIN_LIST_STR_ADD"  # add a STR to the values list <NAC><CLASSNAME><SPINNAME><STR>
SCTN09FF_SPIN_LIST_VAL_ADD = "SCTN09FF_SPIN_LIST_VAL_ADD"  # add a VAL to the values list <NAC><CLASSNAME><SPINNAME><VAL>
SCTN09FF_TEXT_DEF = "SCTN09FF_TEXT_DEF"  # define a text <NAC><CLASSNAME><TEXTNAME><ISATIME>
SCTN09FF_TEXT_PARM_ADD = "SCTN09FF_TEXT_PARM_ADD"  # add a PARM to a text element <NAC><CLASSNAME><TEXTNAME><VAL>
SCTN09FF_TEXT_STR_ADD = "SCTN09FF_TEXT_STR_ADD"  # add a str to a text element <NAC><CLASSNAME><TEXTNAME><KEY><MODULE><VAL>
SCTN09FF_TEXT_VAL_ADD = "SCTN09FF_TEXT_VAL_ADD"  # add a val to a text element <NAC><CLASSNAME><TEXTNAME><KEY><MODULE><VAL>
SCTN09FF_WINDOW_DEF = "SCTN09FF_WINDOW_DEF"  # define a main dictdict <NAC><CLASSNAME><MAINNAME>
SCTN09FF_WINDOW_STR_ADD = "SCTN09FF_WINDOW_STR_ADD"  # add a str to the main dictdict
SCTN09FF_WINDOW_VAL_ADD = "SCTN09FF_WINDOW_VAL_ADD"  # add a str to the main dictdict


FMAXFM_AXLST = [
	NOP,  # ignore the remainder of the line
	SCTNS_DEF,  # define the sections <NAC><SCTN><MODULE><SUB0><SUB1><SUB2><DESCRIPTION>
	SCTN0003_LAMBDA_DEF,  # define a lambda function <NAC><K_EVENT_NAME><lambda str>
	SCTN0003_TYPE_DEF,  # define a fake type used in the translation dict <NAC><K_EVENT_NAME><TYPE>
	SCTN0201_STR_DEF,  # define a STR in SCTN0201 <NAC><K_EVENT_NAME><str>
	SCTN0201_VAL_DEF,  # define a VAL in SCTN0201 <NAC><K_EVENT_NAME><VAL>
	SCTN0202_OPT_ADD_HLPLN,  # add a line to the help for a PARM, after the comment is automatically added<NAC><PARM><ADDONHELPLINE>
	SCTN0202_OPT_STR_ADD,  # define a '-a[=]' in SCTN22 <NAC><PARM><KEY><VAL>
	SCTN0202_OPT_VAL_ADD,  # define a '-a[=]' in SCTN22 <NAC><PARM><KEY><VAL>
	SCTN0202_OPTDICT_STR_ADD,  # define a OPTNAME: 'str' in SCTN0202 <NAC><KEY><PARM><STRDEFAULT>
	SCTN0202_OPTDICT_VAL_ADD,  # define a OPTNAME: VAL in SCTN0202 <NAC><KEY><PARM><VALDEFAULT>
	SCTN0203_DICT_DEF,  # define a dict in SCTN203 <NAC><DICTNAME><DICTMODE>
	SCTN0203_DICT_VS_ADD,  # define a dict STR in SCTN203 <NAC><DICTNAME><STR>
	SCTN0203_DICT_VV_ADD,  # define a dict VAL in SCTN203 <NAC><DICTNAME><VAL>
	SCTN0204_LIST_DEF,  # define a list in SCTN204 <NAC><LISTNAME>
	SCTN0204_LIST_STR_ADD,  # define a list STR in SCTN204 <NAC><LISTNAME><STR>
	SCTN0204_LIST_VAL_ADD,  # define a VAL in a list in SCTN204 <NAC><LISTNAME><VAL>
	SCTN0101_AX_DEF,  # define a new FM action <NAC>
	SCTN0102_STR_DEF,  # define a FM string <NAC><VALNAME><STR>
	SCTN0102_VAL_DEF,  # define a FM _value_ <NAC><VALNAME><VAL>
	SCTN0103_DICT_DEF,  # define a dict for FM <NAC><DICTNAME>
	SCTN0104_LIST_DEF,  # define a list in FM <NAC><LISTNAME>
	SCTN0104_LIST_STR_ADD,  # define a list in FM <NAC>
	SCTN0104_LIST_VAL_ADD,  # define a list in FM <NAC>
	SCTN0105_LDICT_DEF,  # define a dict for FM <NAC>
	SCTN0105_LDICT_VS_ADD,  # define a dict for FM <NAC>
	SCTN0105_LDICT_VV_ADD,  # define a dict for FM <NAC>
	SCTN0106_SCTN_DEF,  # define the SCTN all over the place <NAC><SCTNNAME><DESCRIPTION0>
	SCTN0900_STR_DEF,  # define a string in the first section (colors, etc.) of defines in PSG.py <NAC><VALNAME><VAL>
	SCTN0900_VAL_DEF,  # define a value in the first define section in PSG.py <NAC><VALNAME><VAL>
	SCTN0901_DUBLT_SS_DEF,  # define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>
	SCTN0901_DUBLT_SV_DEF,  # define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>
	SCTN0901_DUBLT_VS_DEF,  # define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>
	SCTN0901_DUBLT_VV_DEF,  # define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>
	SCTN0901_KEY_DEF,  # define a key in the second section of defines in PSG.py <NAC><VALNAME>
	SCTN0901_STR_DEF,  # define a string in the second section of defines in PSG.py <NAC><VALNAME><VAL>
	SCTN0901_VAL_DEF,  # define a value in the second define section in PSG.py <NAC><VALNAME><VAL>
	SCTN0902_DICT_DEF,  # define a dict in PSG <NAC><DICTNAME>
	SCTN0902_DICT_SS_ADD,  # add a str-str to a dict <NAC><DICTNAME><STR><STR>
	SCTN0902_DICT_SV_ADD,  # add a str-val to a dict <NAC><DICTNAME><STR><VAL>
	SCTN0902_DICT_VS_ADD,  # add a str to a dict <NAC><DICTNAME><KEY><VAL>
	SCTN0902_DICT_VV_ADD,  # add a val to a dict in PSG <NAC><DICTNAME><KEY><VAL>
	SCTN0903_LIST_DEF,  # define a list in PSG <NAC><LISTNAME>
	SCTN0903_LIST_STR_ADD,  # add a str to a list in PSG <NAC><LISTNAME><STR>
	SCTN0903_LIST_VAL_ADD,  # add a val to a list in PSG <NAC><LISTNAME><VAL>
	SCTN0904_PLATEQ_ELIF_ADD,  # platform equalizer define an elif <NAC><STRUCTNAME><CONDITION><VAL>
	SCTN0904_PLATEQ_ELSE_ADD,  # platform equalizer define an else <NAC><STRUCTNAME><CONDITION>
	SCTN0904_PLATEQ_FUNC_STR_ADD,  # add a function string line <NAC><STRUCTNAME><CONDITION>
	SCTN0904_PLATEQ_IF_ADD,  # add the 1st if to a platform equalizer <NAC><STRUCTNAME><CONDITION>
	SCTN0904_PLATEQ_PLAT_DEF,  # define a platform equalizer struct <NAC><STRUCTNAME>
	SCTN0904_PLATEQ_STR_ADD,  # add a string to a PLATEQ <NAC><STRUCTNAME><VALNAME><VAL>
	SCTN0904_PLATEQ_VAL_ADD,  # add a value to a PLATEQ <NAC><STRUCTNAME><VALNAME><VAL>
	SCTN0905_TDD_VS_ADD,  # define a ddict <NAC><TUPDICTNAME><KEY><VAL><DDICTKEY>
	SCTN0905_TDD_VV_ADD,  # define a ddict <NAC><TUPDICTNAME><KEY><VAL><DDICTKEY>
	SCTN0905_TUPDICT_DDICT_DEF,  # define a ddict <NAC><TUPDICTNAME><KEY><DDICTKEY>
	SCTN0905_TUPDICT_DEF,  # define a TUPDICT in the second define section in PSG.py <NAC><TUPDICTNAME>
	SCTN0905_TUPDICT_DICT_ADD,  # add a value to a tupdict <NAC><TUPDICTNAME><KEY><VAL>
	SCTN0905_TUPDICT_SS_ADD,  # add a str to a tupdict <NAC><TUPDICTNAME><STR><STR>
	SCTN0905_TUPDICT_SV_ADD,  # add a value to a tupdict <NAC><TUPDICTNAME><STR><VAL>
	SCTN0905_TUPDICT_VS_ADD,  # add a str to a tupdict <NAC><TUPDICTNAME><KEY><STR>
	SCTN0905_TUPDICT_VV_ADD,  # add a value to a tupdict <NAC><TUPDICTNAME><KEY><VAL>
	SCTN0906_BTN_DEF,  # define a button <NAC><BTNNAME>
	SCTN0906_BTN_STR_ADD,  # add a (VAL,VAL) to a tupdict <NAC><BTNNAME><KEY><VAL>
	SCTN0906_BTN_VAL_ADD,  # add a (VAL,VAL) to a tupdict <NAC><BTNNAME><KEY><VAL>
	SCTN0907_SPIN_DEF,  # define a spin box entry <NAC><SPINNAME>
	SCTN0907_SPIN_DICT_STR_ADD,  # add a STR to the SPINDICT <NAC><SPINNAME><KEY><STR>
	SCTN0907_SPIN_DICT_VAL_ADD,  # add a VAL to the SPINDICT <NAC><SPINNAME><KEY><VAL>
	SCTN0907_SPIN_VALUES_STR_ADD,  # add a STR to the values list <NAC><SPINNAME><STR>
	SCTN0907_SPIN_VALUES_VAL_ADD,  # add a VAL to the values list <NAC><SPINNAME><VAL>
	SCTN0908_CHECKBOX_DEF,  # define a checkbox <NAC><CHECKBOXNAME>
	SCTN0908_CHECKBOX_STR_ADD,  # add a str to a checkbox <NAC><CHECKBOXNAME><KEY><VAL>
	SCTN0908_CHECKBOX_VAL_ADD,  # add a val to a checkbox <NAC><CHECKBOXNAME><KEY><VAL>
	SCTN0909_TEXT_DEF,  # define a text <NAC><TEXTNAME>
	SCTN0909_TEXT_STR_ADD,  # add a str to a text element <NAC><TEXTNAME><KEY><VAL>
	SCTN0909_TEXT_VAL_ADD,  # add a val to a text element <NAC><TEXTNAME>
	SCTN090A_RADIO_DEF,  # define a radio button element
	SCTN090B_COLUMN_BUTTON_ADD,  # add a button to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN090B_COLUMN_CHECKBOX_ADD,  # add a combo to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN090B_COLUMN_COLUMN_ADD,  # add a column to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN090B_COLUMN_COLUMN_PARM_STR_ADD,  # add a column parm to the column to a row <NAC><COLUMNNAME>[ROWKEY]<LEVEL><KEY><VAL>
	SCTN090B_COLUMN_COLUMN_PARM_VAL_ADD,  # add a column parm to the column to a row <NAC><COLUMNNAME>[ROWKEY]<LEVEL><KEY><VAL>
	SCTN090B_COLUMN_COMBO_ADD,  # add a combo to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN090B_COLUMN_DEF,  # define a column <NAC><COLUMNNAME>
	SCTN090B_COLUMN_KEY_ADD,  # add a key to a column element 'key=' will be added automatically <NAC><COLUMNNAME><ROWKEY><ELEMENTKEY><VAL>
	SCTN090B_COLUMN_PACKEDPARM_ADD,  # add packedparms to a column entry <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
	SCTN090B_COLUMN_PARM_ADD,  # add parms to a column entry <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
	SCTN090B_COLUMN_RADIO_ADD,  # add a radio to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN090B_COLUMN_ROW_ADD,  # add a row [] to a column <NAC><COLUMNNAME><ROWKEY><LEVEL>
	SCTN090B_COLUMN_SPIN_ADD,  # add a spinbox to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN090B_COLUMN_TEXT_ADD,  # add a text element to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN090C_APPDS_DEF,  # add a nested dict holding all of the variables passed between PySimpleGUI and this app
	SCTN090C_APPDS_DICT_DEF,  # add a dict to the mainapp dict <NAC><DICTNAME
	SCTN090C_APPDS_DICT_VS_ADD,  # add a string to a dict mainapp dict <NAC><DICTNAME><KEY><STR>
	SCTN090C_APPDS_DICT_VV_ADD,  # add a value to a dict mainapp dict <NAC><DICTNAME><KEY><VAL>
	SCTN090C_APPDS_VS_ADD,  # add a string to the mainapp dict <NAC><KEY><STR>
	SCTN090C_APPDS_VV_ADD,  # add a value to the mainapp dict <NAC><KEY><VAL>
	SCTN090D_FORMMAIN_DEF,  # define a frame <NAC><FRAMENAME><_WINDOW_><FINALIZEBOOL> (** added automatically bool adds or not chained finalize() call)
	SCTN090E_LAYOUT_BUTTON_ADD,  # add a button to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN090E_LAYOUT_CHECKBOX_ADD,  # add a checkbox to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN090E_LAYOUT_COLUMN_ADD,  # add a column to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN090E_LAYOUT_COMBO_ADD,  # add a combo to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN090E_LAYOUT_DEF,  # define a layout <NAC><LAYOUTNAME>
	SCTN090E_LAYOUT_KEY_ADD,  # add a key to a layout element 'key=' will be added automatically <NAC><LAYOUTNAME><ROWKEY><ELEMENTKEY><VAL>
	SCTN090E_LAYOUT_PACKEDPARM_ADD,  # add packedparms to a layout entry <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
	SCTN090E_LAYOUT_PARM_VAL_ADD,  # add parms to a layout entry <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
	SCTN090E_LAYOUT_RADIO_ADD,  # add a radio to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN090E_LAYOUT_ROW_ADD,  # add a row [] to a layout <NAC><LAYOUTNAME><ROWKEY><LEVEL>
	SCTN090E_LAYOUT_SPIN_ADD,  # add a spinbox to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN090E_LAYOUT_TEXT_ADD,  # add a text element to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN090F_WINDOW_DEF,  # define a window element <NAC><WINDOWNAME>
	SCTN090F_WINDOW_STR_ADD,  # add a str to the window element <NAC><WINDOWNAME><VALNAME><VAL>
	SCTN090F_WINDOW_VAL_ADD,  # add a str to the window element <NAC><WINDOWNAME><VALNAME><VAL>
	SCTN0910_DUBLT_SS_DEF,  # define a (x,y) tuple <NAC><DUBTUPNAME><VAL1><VAL2>
	SCTN0910_DUBLT_SV_DEF,  # define a (x,y) tuple <NAC><DUBTUPNAME><VAL1><VAL2>
	SCTN0910_DUBLT_VS_DEF,  # define a (x,y) tuple <NAC><DUBTUPNAME><VAL1><VAL2>
	SCTN0910_DUBLT_VV_DEF,  # define a (x,y) tuple <NAC><DUBTUPNAME><VAL1><VAL2>
	SCTN0910_STR_DEF,  # define a string in the second section of defines in PSG.py <NAC><VALNAME><VAL>
	SCTN0910_VAL_DEF,  # define a value in the second define section in PSG.py <NAC><VALNAME><VAL>
	SCTN0911_COMBO_DEF,  # define a combo box <NAC><COMBOBOXNAME>
	SCTN0912_FRAMEELEMENT_DEF,  # define a frame element <NAC><FENAME>
	SCTN0913_RCMENU_DEF,  # define a right click menu <NAC><RCMENUNAME>
	SCTN0913_RCMENU_VAL_ADD,  # define a right click menu <NAC><RCMENUNAME><VAL>
	SCTN0914_FORMPOPUP_DEF,  # define a frame <NAC><FRAMENAME><_WINDOW_><FINALIZEBOOL> (** added automatically bool adds or not chained finalize() call)
	SCTN0915_PUDLG_DEF,  # define a popup dialog <NAC><POPUPNAME><POPUPTYPE>
	SCTN0915_PUDLG_DICT_STR_ADD,  # add a str to a text element <NAC><POPUPNAME><KEY><VAL>
	SCTN0915_PUDLG_DICT_VAL_ADD,  # add a val to a text element <NAC><POPUPNAME><KEY><VAL>
	SCTN0915_PUDLG_LIST_STR_ADD,  # add a str to a text element <NAC><POPUPNAME><KEY><VAL>
	SCTN0915_PUDLG_LIST_VAL_ADD,  # add a val to a text element <NAC><POPUPNAME><KEY><VAL>
	SCTN0916_KEY0_DEF,  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><KEY>
	SCTN0916_KEY1_DEF,  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><SUB1><KEY>
	SCTN0916_KEY2_DEF,  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><SUB1><SUB2><KEY>
	SCTN0916_KEY_DEF,  # put a key in def1 of PSG.py <NAC><KEYGROUP><KEY>
	SCTN0916_KEYSTR0_DEF,  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><KEY><VAL>
	SCTN0916_KEYSTR1_DEF,  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><SUB1><KEY><VAL>
	SCTN0916_KEYSTR2_DEF,  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><SUB1><SUB2><KEY><VAL>
	SCTN0916_KEYSTR_DEF,  # put a key in def1 of PSG.py <NAC><KEYGROUP><KEY><VAL>
	SCTN09FF_BTN_DEF,  # define a button <NAC><CLASSNAME><BTNNAME>
	SCTN09FF_BTN_STR_ADD,  # add a (VAL,VAL) to a tupdict <NAC><CLASSNAME><BTNNAME><KEY><VAL>
	SCTN09FF_BTN_VAL_ADD,  # add a (VAL,VAL) to a tupdict <NAC><CLASSNAME><BTNNAME><KEY><VAL>
	SCTN09FF_CHECKBOX_DEF,  # define a checkbox <NAC><CLASSNAME><CHECKBOXNAME>
	SCTN09FF_CHECKBOX_PARM_ADD,  # add a parameter to a checkbox <NAC><CLASSNAME><CHECKBOXNAME><VAL>
	SCTN09FF_CHECKBOX_STR_ADD,  # add a str to a checkbox <NAC><CLASSNAME><CHECKBOXNAME><KEY><VAL>
	SCTN09FF_CHECKBOX_VAL_ADD,  # add a val to a checkbox <NAC><CLASSNAME><CHECKBOXNAME><KEY><VAL>
	SCTN09FF_COLUMN_BUTTON_ADD,  # add a button to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN09FF_COLUMN_CHECKBOX_ADD,  # add a combo to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN09FF_COLUMN_COLUMN_ADD,  # add a column to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN09FF_COLUMN_COLUMN_PARM_STR_ADD,  # add a column parm to the column to a row <NAC><CLASSNAME><COLUMNNAME>[ROWKEY]<LEVEL><KEY><VAL>
	SCTN09FF_COLUMN_COLUMN_PARM_VAL_ADD,  # add a column parm to the column to a row <NAC><CLASSNAME><COLUMNNAME>[ROWKEY]<LEVEL><KEY><VAL>
	SCTN09FF_COLUMN_COMBO_ADD,  # add a combo to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN09FF_COLUMN_DEF,  # define a column <NAC><CLASSNAME><COLUMNNAME>
	SCTN09FF_COLUMN_GROUP_DEF,  # define a column group <NAC><CLASSNAME><COLUMNGROUP>
	SCTN09FF_COLUMN_KEY_ADD,  # add a key to a column element 'key=' will be added automatically <NAC><CLASSNAME><COLUMNNAME><ROWKEY><ELEMENTKEY><VAL>
	SCTN09FF_COLUMN_PACKEDPARM_ADD,  # add packedparms to a column entry <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
	SCTN09FF_COLUMN_PARM_ADD,  # add parms to a column entry <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
	SCTN09FF_COLUMN_RADIO_ADD,  # add a radio to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN09FF_COLUMN_ROW_ADD,  # add a row [] to a column <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL>
	SCTN09FF_COLUMN_SPIN_ADD,  # add a spinbox to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN09FF_COLUMN_TEXT_ADD,  # add a text element to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN09FF_COMBO_DEF,  # define a combo box <NAC><COMBOBOXNAME>
	SCTN09FF_DEF,  # define a class <NAC><CLASSNAME>
	SCTN09FF_DICT_DEF,  # define a dict in PSG <NAC><CLASSNAME><DICTNAME>
	SCTN09FF_DICT_SS_ADD,  # add a str-str to a dict <NAC><CLASSNAME><DICTNAME><STR><STR>
	SCTN09FF_DICT_SV_ADD,  # add a str-val to a dict <NAC><CLASSNAME><DICTNAME><STR><VAL>
	SCTN09FF_DICT_VS_ADD,  # add a str to a dict <NAC><CLASSNAME><DICTNAME><KEY><VAL>
	SCTN09FF_DICT_VV_ADD,  # add a val to a dict in PSG <NAC><CLASSNAME><DICTNAME><KEY><VAL>
	SCTN09FF_DPD_DEF,  # define a DPD debugPrintDict in PSG <NAC><CLASSNAME><DPDNAME>
	SCTN09FF_DPD_VV_ADD,  # add a val to a DPD debugPrintDict in PSG <NAC><CLASSNAME><DPDNAME><KEY><VAL>
	SCTN09FF_FORMMAIN_DEF,  # define a class mainframe
	SCTN09FF_FORMPOPUP_DEF,  # define a class mainframe
	SCTN09FF_FRAMEELEMENT_DEF,  # define a frame element
	SCTN09FF_FUNCTION_BLANKLINE,  # define a class <NAC><CLASSNAME><FUNCNAME><PARMS>
	SCTN09FF_FUNCTION_DEF,  # define a class <NAC><CLASSNAME><FUNCNAME><PARMS>
	SCTN09FF_FUNCTION_DEF_FROM_FILE,  # define a class <NAC><CLASSNAME><FUNCNAME><FILENAME>
	SCTN09FF_FUNCTION_LAMBDA1_DEF,  # add a lambda to the top of a function, usually for absorbing things
	SCTN09FF_FUNCTION_LAMBDA2_DEF,  # add a lambda to the top of a function, usually for absorbing things
	SCTN09FF_FUNCTION_LINE_ADD,  # define a class <NAC><CLASSNAME><FUNCNAME><LINE>
	SCTN09FF_FUNCTION_READ_FROM_FILE,  # define a class <NAC><CLASSNAME><FUNCNAME><FILENAME>
	SCTN09FF_FUNCTION_STR1_DEF,  # define a string in the class <NAC><CLASSNAME><FUNCNAME><VALNAME><VAL>
	SCTN09FF_FUNCTION_STR2_DEF,  # define a string in the class <NAC><CLASSNAME><FUNCNAME><VALNAME><VAL>
	SCTN09FF_FUNCTION_VAL1_DEF,  # define a value in the class <NAC><CLASSNAME><FUNCNAME><VALNAME><VAL>
	SCTN09FF_FUNCTION_VAL2_DEF,  # define a value in the class <NAC><CLASSNAME><FUNCNAME><VALNAME><VAL>
	SCTN09FF_GROUP_SELECT,  # define a column group default <NAC><CLASSNAME><GROUPNAME><GROUPVALUE>
	SCTN09FF_INIT_ADD1_LAMBDA,  # define a string in the class <NAC><CLASSNAME><VALNAME><VAL>
	SCTN09FF_INIT_ADD1_LINE,  # define a class <NAC><CLASSNAME><LINE>
	SCTN09FF_INIT_ADD1_READ_FROM_FILE,  # read a section of __init__ from a file in res/functions <NAC><CLASSNAME><FILENAME>
	SCTN09FF_INIT_ADD1_STR,  # define a string in the class <NAC><CLASSNAME><VALNAME><VAL>
	SCTN09FF_INIT_ADD1_VAL,  # define a value in the class <NAC><CLASSNAME><VALNAME><VAL>
	SCTN09FF_INIT_ADD2_DICTIN_SS,  # add a str-str to a dict <NAC><CLASSNAME><STR><STR>
	SCTN09FF_INIT_ADD2_DICTIN_SV,  # add a str-val to a dict <NAC><CLASSNAME><STR><VAL>
	SCTN09FF_INIT_ADD2_DICTIN_VS,  # add a str to a dict <NAC><CLASSNAME><KEY><VAL>
	SCTN09FF_INIT_ADD2_DICTIN_VV,  # add a val to a dict in PSG <NAC><CLASSNAME><KEY><VAL>
	SCTN09FF_INIT_ADD2_FOREIGN_KEY,  # add values to _DICT_KEYS, _DICT_KEYS_REVERSE_ for external elements like buttons and checkboxes <NAC><CLASSNAME><KEY>
	SCTN09FF_INIT_ADD2_LAMBDA,  # define a value in the class <NAC><CLASSNAME><VALNAME><VAL>
	SCTN09FF_INIT_ADD2_LINE,  # define a class <NAC><CLASSNAME><LINE>
	SCTN09FF_INIT_ADD2_READ_FROM_FILE,  # read a section of __init__ from a file in res/functions <NAC><CLASSNAME><FILENAME>
	SCTN09FF_INIT_ADD2_STR,  # define a string in the class <NAC><CLASSNAME><VALNAME><VAL>
	SCTN09FF_INIT_ADD2_VAL,  # define a value in the class <NAC><CLASSNAME><VALNAME><VAL>
	SCTN09FF_INIT_ADD3_LINE,  # define a class <NAC><CLASSNAME><LINE>
	SCTN09FF_INIT_DEF,  # define a class <NAC><CLASSNAME><PARMS>
	SCTN09FF_LAYOUT_BUTTON_ADD,  # add a button to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN09FF_LAYOUT_CHECKBOX_ADD,  # add a checkbox to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN09FF_LAYOUT_COLUMN_ADD,  # add a column to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN09FF_LAYOUT_COMBO_ADD,  # add a combo to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN09FF_LAYOUT_DEF,  # define layouts
	SCTN09FF_LAYOUT_KEY_ADD,  # add a key to a layout element 'key=' will be added automatically <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><ELEMENTKEY><VAL>
	SCTN09FF_LAYOUT_PACKEDPARM_ADD,  # add packedparms to a layout entry <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
	SCTN09FF_LAYOUT_PARM_VAL_ADD,  # add parms to a layout entry <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
	SCTN09FF_LAYOUT_RADIO_ADD,  # add a radio to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN09FF_LAYOUT_ROW_ADD,  # add a row [] to a layout <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL>
	SCTN09FF_LAYOUT_SPIN_ADD,  # add a spinbox to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN09FF_LAYOUT_TEXT_ADD,  # add a text element to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	SCTN09FF_LIST_DEF,  # define a list in PSG <NAC><CLASSNAME><LISTNAME>
	SCTN09FF_LIST_STR_ADD,  # add a str to a list in PSG <NAC><CLASSNAME><LISTNAME><STR>
	SCTN09FF_LIST_VAL_ADD,  # add a val to a list in PSG <NAC><CLASSNAME><LISTNAME><VAL>
	SCTN09FF_RADIO_DEF,  # define a radio button element
	SCTN09FF_RCMENU_DEF,  # define a right click menu
	SCTN09FF_RCMENU_VAL_ADD,  # define a right click menu
	SCTN09FF_SPIN_DEF,  # define a spin box entry <NAC><CLASSNAME><SPINNAME>
	SCTN09FF_SPIN_DICT_VS_ADD,  # add a STR to the SPINDICT <NAC><CLASSNAME><SPINNAME><KEY><STR>
	SCTN09FF_SPIN_DICT_VV_ADD,  # add a VAL to the SPINDICT <NAC><CLASSNAME><SPINNAME><KEY><VAL>
	SCTN09FF_SPIN_LIST_STR_ADD,  # add a STR to the values list <NAC><CLASSNAME><SPINNAME><STR>
	SCTN09FF_SPIN_LIST_VAL_ADD,  # add a VAL to the values list <NAC><CLASSNAME><SPINNAME><VAL>
	SCTN09FF_TEXT_DEF,  # define a text <NAC><CLASSNAME><TEXTNAME><ISATIME>
	SCTN09FF_TEXT_PARM_ADD,  # add a PARM to a text element <NAC><CLASSNAME><TEXTNAME><VAL>
	SCTN09FF_TEXT_STR_ADD,  # add a str to a text element <NAC><CLASSNAME><TEXTNAME><KEY><MODULE><VAL>
	SCTN09FF_TEXT_VAL_ADD,  # add a val to a text element <NAC><CLASSNAME><TEXTNAME><KEY><MODULE><VAL>
	SCTN09FF_WINDOW_DEF,  # define a main dictdict <NAC><CLASSNAME><MAINNAME>
	SCTN09FF_WINDOW_STR_ADD,  # add a str to the main dictdict
	SCTN09FF_WINDOW_VAL_ADD,  # add a str to the main dictdict
]


#
#
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * end of __KEYS__.FM._02_FM_AX.py
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
#
#
