

from CF.CONST_D import _01_00_NAMES as N
from FM import FM


# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * start of FM TBGLST_D _03 01 PSG CLOCKS
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*

_class_ = "CLOCKS"
_moduleName_ = "FM"
_subd0_ = "TBGLST_D"
_sub0_ = "_03"
_sub1_ = "01"
_sub2_ = "PSG"
# ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱
_filename_ = f"""{N.MAKE_NAME(
	__CLASS__=_class_,
	__MODULE_NAME__=_moduleName_,
	__SUBD0__=_subd0_,
	__SUB0__=_sub0_,
	__SUB1__=_sub1_,
	__SUB2__=_sub2_,
)}"""  # FM/TBGLST_D/_03_01_PSG_CLOCKS_C.py
# ⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱
_newFilename_ = f"""{N.MAKE_NAME(
	isNew_=True,
	__CLASS__=_class_,
	__MODULE_NAME__=_moduleName_,
	__SUBD0__=_subd0_,
	__SUB0__=_sub0_,
	__SUB1__=_sub1_,
	__SUB2__=_sub2_,
)}"""  # FM/TBGLST_D/_03_01_PSG_CLOCKS_C_NEW.py
# ⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱
__ID__ = N.MAKE_ID(
	("__CLASS__", _class_,),  # CLOCKS
	("__FILENAME__", _filename_,),  # FM/TBGLST_D/_03_01_PSG_CLOCKS_C.py
	("__MODULE_NAME__", _moduleName_,),  # FM
	("__NEW_FILENAME__", _newFilename_,),  # FM/TBGLST_D/_03_01_PSG_CLOCKS_C_NEW.py
	("__SUBD0__", _subd0_,),  # TBGLST_D
	("__SUB0__", _sub0_,),  # _03
	("__SUB1__", _sub1_,),  # 01
	("__SUB2__", _sub2_,),  # PSG
)
# ⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱
TBGLST = [
	(("PSGVAL__CLOCKS", FMAX.SCTN09FF_DEF, _class_, "define clocks class",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01", FMAX.SCTN09FF_GROUP_SELECT, _class_, "_COLUMN01_", "self._COLUMN01B_", "define the selector for COLUMNM01A/B",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A00", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_DEF", _class_, "_COLUMN01A_", "the column that puts the two smaller clocks below the main one",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A01", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_ROW_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_00", "L03", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A02", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_TEXT_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_00", "L04", "COLUMN01A_E01", "add a new TEXT element to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A03", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_PARM_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_00", "L05", "COLUMN01A_E01", "**self._TEXT_TIME_S_CLOCK_", "add the main clock",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A04", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_ROW_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_01", "L03", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A05", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_TEXT_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_01", "L04", "COLUMN01A_E02", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A06", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_PARM_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_01", "L05", "COLUMN01A_E02", "**self._TEXT_TIME_S_AT_ZEROELAPSE_", "add time to go",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A07", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_TEXT_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_01", "L04", "COLUMN01A_E03", "add a new text element to row01 clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A08", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_PARM_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_01", "L05", "COLUMN01A_E03", "**self._TEXT_TIME_S_ELAPSED_", "add elapsed time",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A09", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_ROW_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_02", "L03", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A0A", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_TEXT_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_02", "L04", "COLUMN01A_E04", "add a new text element to row01 clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A0B", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_PARM_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_02", "L05", "COLUMN01A_E04", "**self._TEXT_TIME_S_TOGO_", "add elapsed time",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A0C", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_TEXT_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_02", "L04", "COLUMN01A_E05", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A0D", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_PARM_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_02", "L05", "COLUMN01A_E05", "**self._TEXT_TIME_S_AT_NEXT_ALERT_", "add time to go",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A0E", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_ROW_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_03", "L03", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A0F", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_TEXT_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_03", "L04", "COLUMN01A_E06", "add a new text element to row01 clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A10", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_PARM_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_03", "L05", "COLUMN01A_E06", "**self._TEXT_NAME_NEXT_EVENT_", "add the main clock",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A11", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_ROW_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_04", "L03", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A12", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_CHECKBOX_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_04", "L04", "COLUMN01A_E07", "add a new text element to row01 clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A13", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_PARM_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_04", "L05", "COLUMN01A_E07", "**PSG.CHECKBOX_RUNAWAY01", "add elapsed time",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A14", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_CHECKBOX_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_04", "L04", "COLUMN01A_E08", "add a new text element to row01 clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A15", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_PARM_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_04", "L05", "COLUMN01A_E08", "**PSG.CHECKBOX_ALPHA_DIM01", "add elapsed time",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A16", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_ROW_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_05", "L03", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A17", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_CHECKBOX_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_05", "L04", "COLUMN01A_E09", "add a new text element to row01 clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A18", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_PARM_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_05", "L05", "COLUMN01A_E09", "**PSG.CHECKBOX_HIDE01", "add elapsed time",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A19", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_CHECKBOX_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_05", "L04", "COLUMN01A_E0A", "add a new text element to row01 clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01A1A", FMAX.NOP, "FMAX.SCTN09FF_COLUMN_PARM_ADD", _class_, "_COLUMN01A_", "COLUMN01A_ROW_05", "L05", "COLUMN01A_E0A", "**PSG.CHECKBOX_HOVER_DATE01", "add elapsed time",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B00", FMAX.SCTN09FF_COLUMN_DEF, _class_, "_COLUMN01B_", "the column that puts the two smaller clocks above the main one",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B01", FMAX.SCTN09FF_COLUMN_ROW_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_00", "L03", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B02", FMAX.SCTN09FF_COLUMN_TEXT_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_00", "L04", "COLUMN01B_E01", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B03", FMAX.SCTN09FF_COLUMN_PARM_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_00", "L05", "COLUMN01B_E01", "**self._TEXT_TIME_S_AT_ZEROELAPSE_", "add time to go",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B04", FMAX.SCTN09FF_COLUMN_TEXT_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_00", "L04", "COLUMN01B_E02", "add a new text element to row01 clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B05", FMAX.SCTN09FF_COLUMN_PARM_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_00", "L05", "COLUMN01B_E02", "**self._TEXT_TIME_S_ELAPSED_", "add elapsed time",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B06", FMAX.SCTN09FF_COLUMN_ROW_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_01", "L03", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B07", FMAX.SCTN09FF_COLUMN_TEXT_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_01", "L04", "COLUMN01B_E03", "add a new text element to row01 clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B08", FMAX.SCTN09FF_COLUMN_PARM_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_01", "L05", "COLUMN01B_E03", "**self._TEXT_TIME_S_TOGO_", "add elapsed time",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B09", FMAX.SCTN09FF_COLUMN_TEXT_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_01", "L04", "COLUMN01B_E04", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B0A", FMAX.SCTN09FF_COLUMN_PARM_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_01", "L05", "COLUMN01B_E04", "**self._TEXT_TIME_S_AT_NEXT_ALERT_", "add time to go",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B0B", FMAX.SCTN09FF_COLUMN_ROW_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_02", "L03", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B0C", FMAX.SCTN09FF_COLUMN_TEXT_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_02", "L04", "COLUMN01B_E05", "add a new text element to row01 clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B0D", FMAX.SCTN09FF_COLUMN_PARM_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_02", "L05", "COLUMN01B_E05", "**self._TEXT_NAME_NEXT_EVENT_", "add the main clock",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B0E", FMAX.SCTN09FF_COLUMN_ROW_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_03", "L03", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B0F", FMAX.SCTN09FF_COLUMN_CHECKBOX_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_03", "L04", "COLUMN01B_E06", "add a new text element to row01 clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B10", FMAX.SCTN09FF_COLUMN_PARM_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_03", "L05", "COLUMN01B_E06", "**PSG.CHECKBOX_RUNAWAY01", "add elapsed time",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B11", FMAX.SCTN09FF_COLUMN_CHECKBOX_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_03", "L04", "COLUMN01B_E07", "add a new text element to row01 clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B12", FMAX.SCTN09FF_COLUMN_PARM_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_03", "L05", "COLUMN01B_E07", "**PSG.CHECKBOX_ALPHA_DIM01", "add elapsed time",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B13", FMAX.SCTN09FF_COLUMN_ROW_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_04", "L03", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B14", FMAX.SCTN09FF_COLUMN_CHECKBOX_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_04", "L04", "COLUMN01B_E08", "add a new text element to row01 clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B15", FMAX.SCTN09FF_COLUMN_PARM_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_04", "L05", "COLUMN01B_E08", "**PSG.CHECKBOX_HIDE01", "add elapsed time",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B16", FMAX.SCTN09FF_COLUMN_CHECKBOX_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_04", "L04", "COLUMN01B_E09", "add a new text element to row01 clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B17", FMAX.SCTN09FF_COLUMN_PARM_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_04", "L05", "COLUMN01B_E09", "**PSG.CHECKBOX_HOVER_DATE01", "add elapsed time",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B18", FMAX.SCTN09FF_COLUMN_ROW_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_05", "L03", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B19", FMAX.SCTN09FF_COLUMN_TEXT_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_05", "L04", "COLUMN01B_E0A", "add a new TEXT element to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN01B1A", FMAX.SCTN09FF_COLUMN_PARM_ADD, _class_, "_COLUMN01B_", "COLUMN01B_ROW_05", "L05", "COLUMN01B_E0A", "**self._TEXT_TIME_S_CLOCK_", "add the main clock",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN02", FMAX.NOP, "the COLUMN02 for APPMODE_CLOCKS",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN0200", FMAX.SCTN09FF_COLUMN_DEF, _class_, "_COLUMN02_", "the column that puts the two smaller clocks below the main one",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN0201", FMAX.SCTN09FF_COLUMN_ROW_ADD, _class_, "_COLUMN02_", "COLUMN02_ROW_01", "L03", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN0202", FMAX.SCTN09FF_COLUMN_BUTTON_ADD, _class_, "_COLUMN02_", "COLUMN02_ROW_01", "L04", "COLUMN02_E01", "add a button element to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN0203", FMAX.SCTN09FF_COLUMN_PARM_ADD, _class_, "_COLUMN02_", "COLUMN02_ROW_01", "L05", "COLUMN02_E01", "**PSG.BTN_QUIT20", "add the xpand button to clocks",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN0204", FMAX.SCTN09FF_COLUMN_ROW_ADD, _class_, "_COLUMN02_", "COLUMN02_ROW_02", "L03", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN0205", FMAX.SCTN09FF_COLUMN_BUTTON_ADD, _class_, "_COLUMN02_", "COLUMN02_ROW_02", "L04", "COLUMN02_E02", "add reset button for elapsed time",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN0206", FMAX.SCTN09FF_COLUMN_PARM_ADD, _class_, "_COLUMN02_", "COLUMN02_ROW_02", "L05", "COLUMN02_E02", "**PSG.BTN_ZERO20", "add the zero button to clocks",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN0207", FMAX.SCTN09FF_COLUMN_ROW_ADD, _class_, "_COLUMN02_", "COLUMN02_ROW_03", "L03", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN0208", FMAX.SCTN09FF_COLUMN_BUTTON_ADD, _class_, "_COLUMN02_", "COLUMN02_ROW_03", "L04", "COLUMN02_E03", "add reset button for elapsed time",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN0209", FMAX.SCTN09FF_COLUMN_PARM_ADD, _class_, "_COLUMN02_", "COLUMN02_ROW_03", "L05", "COLUMN02_E03", "**PSG.BTN_XPAND20", "add the zero button to clocks",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN020A", FMAX.SCTN09FF_COLUMN_ROW_ADD, _class_, "_COLUMN02_", "COLUMN02_ROW_04", "L03", "add a new row to clocks column",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN020B", FMAX.SCTN09FF_COLUMN_TEXT_ADD, _class_, "_COLUMN02_", "COLUMN02_ROW_04", "L04", "COLUMN02_E04", "add reset button for elapsed time",), __ID__),
	(("PSGVAL__CLOCKS_COLUMN020C", FMAX.SCTN09FF_COLUMN_PARM_ADD, _class_, "_COLUMN02_", "COLUMN02_ROW_04", "L05", "COLUMN02_E04", "**self._TEXT_CURRENT_INTERVAL_COUNT_", "add the zero button to clocks",), __ID__),
	(("PSGVAL__CLOCKS_DICT_KEYS_INT00", FMAX.SCTN09FF_DICT_DEF, _class_, "_DICT_KEYS_INT_", "dict of integer keys and their format",), __ID__),
	(("PSGVAL__CLOCKS_DICT_KEYS_INT01", FMAX.SCTN09FF_DICT_VS_ADD, _class_, "_DICT_KEYS_INT_", "PSG.K_CURRENT_INTERVAL_COUNT", "04d", "intervalCount:04d",), __ID__),
	(("PSGVAL__CLOCKS_DICT_KEYS_TIME00", FMAX.SCTN09FF_DICT_DEF, _class_, "_DICT_KEYS_TIME_", "dict of time keys and their max value int seconds",), __ID__),
	(("PSGVAL__CLOCKS_DICT_KEYS_TIME01", FMAX.SCTN09FF_DICT_VV_ADD, _class_, "_DICT_KEYS_TIME_", "PSG.K_TIME_S_AT_NEXT_ALERT", "CF.DAY_S", "comment",), __ID__),
	(("PSGVAL__CLOCKS_DICT_KEYS_TIME01", FMAX.SCTN09FF_DICT_VV_ADD, _class_, "_DICT_KEYS_TIME_", "PSG.K_TIME_F_AT_ZEROELAPSE", "CF.DAY_S", "comment",), __ID__),
	(("PSGVAL__CLOCKS_DICT_KEYS_TIME01", FMAX.SCTN09FF_DICT_VV_ADD, _class_, "_DICT_KEYS_TIME_", "PSG.K_TIME_S_CLOCK", "CF.DAY_S", "",), __ID__),
	(("PSGVAL__CLOCKS_DICT_KEYS_TIME01", FMAX.SCTN09FF_DICT_VV_ADD, _class_, "_DICT_KEYS_TIME_", "PSG.K_TIME_S_ELAPSED", "CF.TIME_S_995959", "",), __ID__),
	(("PSGVAL__CLOCKS_DICT_KEYS_TIME01", FMAX.SCTN09FF_DICT_VV_ADD, _class_, "_DICT_KEYS_TIME_", "PSG.K_TIME_S_TOGO", "CF.DAY_S", "",), __ID__),
	(("PSGVAL__CLOCKS_DICT_VALUES00", FMAX.NOP, "FMAX.SCTN09FF_DICT_DEF", _class_, "_VALUES_", "dict to hold the virtual checkboxes etc.",), __ID__),
	(("PSGVAL__CLOCKS_DICT_VALUES01", FMAX.NOP, "FMAX.SCTN09FF_DICT_DEF", _class_, "_VALUES_", "PSG.K_CHECKBOX_ALPHA_DIM", "True", "checkbox alpha dim",), __ID__),
	(("PSGVAL__CLOCKS_DICT_VALUES01", FMAX.NOP, "FMAX.SCTN09FF_DICT_DEF", _class_, "_VALUES_", "PSG.K_CHECKBOX_HIDE", "True", "checkbox hide",), __ID__),
	(("PSGVAL__CLOCKS_DICT_VALUES01", FMAX.NOP, "FMAX.SCTN09FF_DICT_DEF", _class_, "_VALUES_", "PSG.K_CHECKBOX_HOVER_DATE", "True", "checkbox show date when hovering",), __ID__),
	(("PSGVAL__CLOCKS_DICT_VALUES01", FMAX.NOP, "FMAX.SCTN09FF_DICT_DEF", _class_, "_VALUES_", "PSG.K_CHECKBOX_RUNAWAY", "False", "checkbox alpha dim",), __ID__),
	(("PSGVAL__CLOCKS_DPD00", FMAX.SCTN09FF_DPD_DEF, _class_, "_DPD_", "define a DPD CLOCKS:/",), __ID__),
	(("PSGVAL__CLOCKS_DPD01", FMAX.SCTN09FF_DPD_VV_ADD, _class_, "_DPD_", "F___INIT__", "True", "define a DPD at /",), __ID__),
	(("PSGVAL__CLOCKS_FORMMAIN", FMAX.NOP, "the form for clocks",), __ID__),
	(("PSGVAL__CLOCKS_FORMMAIN00", FMAX.SCTN09FF_FORMMAIN_DEF, _class_, "_WINDOW_", "True", "the clocks form defined and done",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT", FMAX.SCTN09FF_INIT_DEF, _class_, ",%ESCLN%%TAB3%keyBase_,%ESCLN%%TAB3%formName_%NEWLINE%%TAB2%", "init parms defined",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT000", FMAX.SCTN09FF_INIT_ADD1_VAL, _class_, "_THIS_KEY_BASE_", "keyBase_", "adopt keyBase_",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT001", FMAX.SCTN09FF_INIT_ADD1_LAMBDA, _class_, "_USE_THIS_KEY_", "__KEY_TEXT__: %FTQ%%OBRCE%__KEY_TEXT__%CBRCE%%OBRCE%self._THIS_KEY_BASE_%CBRCE%%TQ%", "make a local key sourcer",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT002", FMAX.SCTN09FF_INIT_ADD1_VAL, _class_, "_DICT_KEYS_", "{}", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT002", FMAX.SCTN09FF_INIT_ADD1_VAL, _class_, "_DICT_KEYS_REVERSE_", "{}", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT002", FMAX.SCTN09FF_INIT_ADD1_VAL, _class_, "_LIST_KEYS_TIME_", "[]", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT002", FMAX.SCTN09FF_INIT_ADD1_VAL, _class_, "_THIS_CLASS_", "CLOCKS", "set the class name",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT002", FMAX.SCTN09FF_INIT_ADD1_VAL, _class_, "_THIS_FORM_NAME_", "formName_", "adopt formName_",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_ALPHA_CHANNEL_", "PSG.SZ_ALPHA_HIGH", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_ALPHA_HIGH_", "PSG.SZ_ALPHA_HIGH", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_ALPHA_LOW_", "PSG.SZ_ALPHA_LOW", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_BBOX_", "PSG.EMPTY_BBOX", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_CHANGED_EVENTS_", "False", "comment",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_CHANGED_LOCATION_", "False", "comment",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_CHANGED_MOUSE_LOCATION_", "False", "comment",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_CHANGED_VALUES_", "False", "comment",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_CLOSE_BBOX_", "PSG.EMPTY_BBOX", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_CURRENTLY_DIMMED_", "False", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_CURRENT_EVENTMODE_", "None", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_CURRENT_EVENT_", "None", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_CURRENT_FLIP_INFO_", "[]", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_CURRENT_LOCATION_", "PSG.EMPTY_XY", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_CURRENT_MOUSE_LOCATION_", "PSG.EMPTY_XY", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_CURRENT_MOUSE_STATUS_", "PSG.MOUSE_STATUS_NONE", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_CURRENT_VALUES_", "{}", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_EXITING_", "False", "this class is currently being exited bool",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_HIDDEN_", "False", "bool are we hidden or not",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_MAINFRAME_", "None", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_MPX_", "PSG.EMPTY_XY", "comment",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_SCREEN_DIMS_", "PSG.EMPTY_XY", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_SIZE_", "PSG.EMPTY_XY", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_TIME_MS_AT_CHECK_MOUSE_", "PSG.ZERO_CLOCK", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_TIME_MS_AT_FLIP_", "PSG.ZERO_CLOCK", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_TIME_MS_AT_MOVE_", "PSG.ZERO_CLOCK", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_TIME_MS_AT_UNHIDE_", "PSG.ZERO_CLOCK", "the time when the window will unhide",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT01", FMAX.SCTN09FF_INIT_ADD2_VAL, _class_, "_TIME_MS_AT_UPDATE_", "PSG.ZERO_CLOCK", "",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT02_DICTIN01", FMAX.SCTN09FF_INIT_ADD2_DICTIN_VV, _class_, "K_CHECKBOX_ALPHA_DIM", "True", "False", "value of the alphas dim checkbox",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT02_DICTIN01", FMAX.SCTN09FF_INIT_ADD2_DICTIN_VV, _class_, "K_CHECKBOX_HIDE", "True", "False", "checkbox hid for a moment when the mouse hovers",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT02_DICTIN01", FMAX.SCTN09FF_INIT_ADD2_DICTIN_VV, _class_, "K_CHECKBOX_HOVER_DATE", "True", "False", "checkbox hid for a moment when the mouse hovers",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT02_DICTIN01", FMAX.SCTN09FF_INIT_ADD2_DICTIN_VV, _class_, "K_CHECKBOX_RUNAWAY", "False", "False", "value of runaway checkbox",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT02_DICTIN01", FMAX.SCTN09FF_INIT_ADD2_DICTIN_VV, _class_, "K_TIME_S_AT_NEXT_ALERT", "PSG.ZERO_CLOCK", "True", "time at next event",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT02_DICTIN01", FMAX.SCTN09FF_INIT_ADD2_DICTIN_VV, _class_, "K_TIME_F_AT_ZEROELAPSE", "PSG.ZERO_CLOCK", "True", "time at last zero of elapsed timer",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT02_DICTIN01", FMAX.SCTN09FF_INIT_ADD2_DICTIN_VV, _class_, "K_TIME_S_CLOCK", "PSG.ZERO_CLOCK", "True", "time clock or wall clock",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT02_DICTIN01", FMAX.SCTN09FF_INIT_ADD2_DICTIN_VV, _class_, "K_TIME_S_ELAPSED", "PSG.ZERO_CLOCK", "True", "time elapsed",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT02_DICTIN01", FMAX.SCTN09FF_INIT_ADD2_DICTIN_VV, _class_, "K_TIME_S_TOGO", "PSG.ZERO_CLOCK", "True", "countdown to next event",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT03_KEY01", FMAX.SCTN09FF_INIT_ADD2_FOREIGN_KEY, _class_, "PSG.K_CHECKBOX_ALPHA_DIM", "False", "add foreign key for alpha dimming",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT03_KEY01", FMAX.SCTN09FF_INIT_ADD2_FOREIGN_KEY, _class_, "PSG.K_CHECKBOX_HIDE", "False", "add foreign key for hiding",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT03_KEY01", FMAX.SCTN09FF_INIT_ADD2_FOREIGN_KEY, _class_, "PSG.K_CHECKBOX_HOVER_DATE", "False", "add foreign key for hiding",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT03_KEY01", FMAX.SCTN09FF_INIT_ADD2_FOREIGN_KEY, _class_, "PSG.K_CHECKBOX_RUNAWAY", "False", "add foreign key for runningaway",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT03_KEY01", FMAX.SCTN09FF_INIT_ADD2_FOREIGN_KEY, _class_, "PSG.K_CURRENT_INTERVAL_COUNT", "True", "add foreign key for CURRENT_INTERVAL_COUNT",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT03_LINE0100", FMAX.SCTN09FF_INIT_ADD3_LINE, _class_, "if (self._DPD_[PSG.F___INIT__] is True):", "see if debug printing is on",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT03_LINE0101", FMAX.SCTN09FF_INIT_ADD3_LINE, _class_, "%TAB1%self.debugPrint(", "debugPrint",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT03_LINE0102", FMAX.SCTN09FF_INIT_ADD3_LINE, _class_, "%TAB2%title_=%DQ%__INIT__3%DQ%,", "print _DICT_KEYS_REVERSE_",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT03_LINE0103", FMAX.SCTN09FF_INIT_ADD3_LINE, _class_, "%TAB2%printDictinS_=True,", "print _DICT_KEYS_",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT03_LINE0104", FMAX.SCTN09FF_INIT_ADD3_LINE, _class_, "%TAB2%message_=%FTQ%self._DICT_KEYS {self._DICT_KEYS_}", "print _DICT_KEYS_",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_00_INIT03_LINE0105", FMAX.SCTN09FF_INIT_ADD3_LINE, _class_, "self._DICT_KEYS_REVERSE_ {self._DICT_KEYS_REVERSE_}%TQ%)", "print _DICT_KEYS_REVERSE_",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_01_ENTER", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "__enter__", "__enter__.py", "False", "define __enter__",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_02_EXIT", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "__exit__", "__exit__.py", "False", "define __exit__ in CLOCKS",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_CHECK_MOUSE", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "checkMouse", "checkMouse.py", "False", "define checkMouse",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_DEBUG_PRINT", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "debugPrint", "debugPrint.py", "False", "print debug info",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_EASY_UPDATE", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "easyUpdate", "CLOCKS/easyUpdate.py", "False", "load the whole thing from the file for easyUpdate",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_EASY_UPDATEPARMS", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "easyUpdateParms", "easyUpdateParms.py", "False", "load the whole thing from the file for easyUpdate",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_ENINT", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "enint", "enint.py", "False", "convert any str in _DICTIN_ to int",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_ENSTRING", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "enstring", "enstring.py", "False", "update _DICTINSTR_ or return strings converted from integers in _DICTIN_",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_HANDLEEVENTS", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "handleEvents", "handleEvents.py", "False", "turn interval count off",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_HANDLEVALUES", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "handleValues", "handleValues.py", "False", "turn interval count off",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_HIDE", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "hide", "hide.py", "True", "convert any str in _DICTIN_ to int",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_INTERVALCOUNTOFF", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "intervalCountOff", "intervalCountOff.py", "False", "turn interval count off",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_INTERVALCOUNTON", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "intervalCountOn", "intervalCountOn.py", "False", "turn interval count on",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_MAKEINKEY", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "makeInKey", "makeInKey.py", "False", "make a human key from a PSG key",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_MAKEOUTKEY", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "makeOutKey", "makeOutKey.py", "False", "make a key used in PSG from a human key",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_MIDNIGHT", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "midnight", "midnight.py", "False", "make a key used in PSG from a human key",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_QUICK_READ", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "quickRead", "quickRead.py", "False", "read the frame and set self._RESULT_ etc",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_RUNAWAY", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "runaway", "runaway.py", "False", "define runaway",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_SETCHECKBOX", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "setCheckbox", "setCheckbox.py", "False", "define setCheckbox",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_TOOLTIPOFF", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "tooltipOff", "CLOCKS/tooltipOff.py", "False", "define tooltipOff",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_TOOLTIPON", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "tooltipOn", "CLOCKS/tooltipOn.py", "False", "define tooltipOn",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_UNHIDE", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "unhide", "unhide.py", "True", "convert any str in _DICTIN_ to int",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_UPDATE_FLIPPED_ITEMS", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "updateFlippedItems", "updateFlippedItems.py", "False", "update items which may have multiple values",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_UPDATE_FROM_DICT", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "updateFromDict", "updateFromDict.py", "False", "update the displayed info from a dict or the default _DICTIN_",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_03_ZERO_FLIPPED", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "zeroFlipped", "zeroFlipped.py", "False", "update the displayed info from a dict or the default _DICTIN_",), __ID__),
	(("PSGVAL__CLOCKS_FUNC_FF_UPDATE", FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE, _class_, "update", "CLOCKS/update.py", "False", "define the required update function",), __ID__),
	(("PSGVAL__CLOCKS_LAYOUT", FMAX.NOP, "layout for APPMODE_CLOCKS",), __ID__),
	(("PSGVAL__CLOCKS_LAYOUT00", FMAX.SCTN09FF_LAYOUT_DEF, _class_, "_LAYOUT_", "layout for APPMODE_CLOCKS",), __ID__),
	(("PSGVAL__CLOCKS_LAYOUT01", FMAX.SCTN09FF_LAYOUT_ROW_ADD, _class_, "_LAYOUT_", "LAYOUT_ROW_00", "L03", "add a row to the layout",), __ID__),
	(("PSGVAL__CLOCKS_LAYOUT02", FMAX.SCTN09FF_LAYOUT_COLUMN_ADD, _class_, "_LAYOUT_", "LAYOUT_ROW_00", "L04", "LAYOUT_E01", "add a column",), __ID__),
	(("PSGVAL__CLOCKS_LAYOUT03", FMAX.SCTN09FF_LAYOUT_PARM_VAL_ADD, _class_, "_LAYOUT_", "LAYOUT_ROW_00", "L05", "LAYOUT_E01", "layout", "self._COLUMN01_", "comment",), __ID__),
	(("PSGVAL__CLOCKS_LAYOUT04", FMAX.SCTN09FF_LAYOUT_PARM_VAL_ADD, _class_, "_LAYOUT_", "LAYOUT_ROW_00", "L05", "LAYOUT_E01", "pad", "PSG.SZ_PAD_ALL", "comment",), __ID__),
	(("PSGVAL__CLOCKS_LAYOUT05", FMAX.SCTN09FF_LAYOUT_COLUMN_ADD, _class_, "_LAYOUT_", "LAYOUT_ROW_00", "L04", "LAYOUT_E02", "add a column",), __ID__),
	(("PSGVAL__CLOCKS_LAYOUT06", FMAX.SCTN09FF_LAYOUT_PARM_VAL_ADD, _class_, "_LAYOUT_", "LAYOUT_ROW_00", "L05", "LAYOUT_E02", "layout", "self._COLUMN02_", "comment",), __ID__),
	(("PSGVAL__CLOCKS_LAYOUT07", FMAX.SCTN09FF_LAYOUT_PARM_VAL_ADD, _class_, "_LAYOUT_", "LAYOUT_ROW_00", "L05", "LAYOUT_E02", "pad", "PSG.SZ_PAD_ALL", "comment",), __ID__),
	(("PSGVAL__CLOCKS_LIST_FLIPPABLE_KEYS00", FMAX.SCTN09FF_LIST_DEF, _class_, "_LIST_FLIPPABLE_KEYS_", "list of the items that can be str|list[str, str, ..]",), __ID__),
	(("PSGVAL__CLOCKS_LIST_FLIPPABLE_KEYS01", FMAX.SCTN09FF_LIST_VAL_ADD, _class_, "_LIST_FLIPPABLE_KEYS_", "PSG.K_TEXT_CURRENT_INTERVAL_COUNT", "list of the items that can be str|list[str, str, ..]",), __ID__),
	(("PSGVAL__CLOCKS_LIST_FLIPPABLE_KEYS01", FMAX.SCTN09FF_LIST_VAL_ADD, _class_, "_LIST_FLIPPABLE_KEYS_", "PSG.K_TEXT_NAME_NEXT_EVENT", "list of the items that can be str|list[str, str, ..]",), __ID__),
	(("PSGVAL__CLOCKS_LIST_MUST_UPDATE00", FMAX.SCTN09FF_LIST_DEF, _class_, "_LIST_MUST_UPDATE_", "list of values that need to be sent through easyUpdate",), __ID__),
	(("PSGVAL__CLOCKS_LIST_MUST_UPDATE01", FMAX.SCTN09FF_LIST_VAL_ADD, _class_, "_LIST_MUST_UPDATE_", "PSG.K_CHECKBOX_ALPHA_DIM", "use easyUpdate-alike to change K_CHECKBOX_ALPHA_DIM",), __ID__),
	(("PSGVAL__CLOCKS_LIST_MUST_UPDATE01", FMAX.SCTN09FF_LIST_VAL_ADD, _class_, "_LIST_MUST_UPDATE_", "PSG.K_CHECKBOX_HIDE", "use easyUpdate-alike to change K_CHECKBOX_HIDE",), __ID__),
	(("PSGVAL__CLOCKS_LIST_MUST_UPDATE01", FMAX.SCTN09FF_LIST_VAL_ADD, _class_, "_LIST_MUST_UPDATE_", "PSG.K_CHECKBOX_HOVER_DATE", "use easyUpdate-alike to change K_CHECKBOX_HOVER_DATE",), __ID__),
	(("PSGVAL__CLOCKS_LIST_MUST_UPDATE01", FMAX.SCTN09FF_LIST_VAL_ADD, _class_, "_LIST_MUST_UPDATE_", "PSG.K_CHECKBOX_RUNAWAY", "use easyUpdate-alike to change K_CHECKBOX_RUNAWAY",), __ID__),
	(("PSGVAL__CLOCKS_RCMENU01", FMAX.SCTN09FF_RCMENU_DEF, _class_, "_RCMENU01_", "right click to do the things",), __ID__),
	(("PSGVAL__CLOCKS_RCMENU0101", FMAX.SCTN09FF_RCMENU_VAL_ADD, _class_, "_RCMENU01_", "PSG.K_BTN_QUIT_ALL", "quit by right click",), __ID__),
	(("PSGVAL__CLOCKS_RCMENU0101", FMAX.SCTN09FF_RCMENU_VAL_ADD, _class_, "_RCMENU01_", "PSG.K_BTN_XPAND", "quit by right click",), __ID__),
	(("PSGVAL__CLOCKS_RCMENU0101", FMAX.SCTN09FF_RCMENU_VAL_ADD, _class_, "_RCMENU01_", "PSG.K_BTN_ZERO", "quit by right click",), __ID__),
	(("PSGVAL__CLOCKS_RCMENU0101", FMAX.SCTN09FF_RCMENU_VAL_ADD, _class_, "_RCMENU01_", "PSG.K_CHECKBOX_ALPHA_DIM", "toggle K_CHECKBOX_ALPHA_DIM",), __ID__),
	(("PSGVAL__CLOCKS_RCMENU0101", FMAX.SCTN09FF_RCMENU_VAL_ADD, _class_, "_RCMENU01_", "PSG.K_CHECKBOX_HIDE", "toggle K_CHECKBOX_HIDE",), __ID__),
	(("PSGVAL__CLOCKS_RCMENU0101", FMAX.SCTN09FF_RCMENU_VAL_ADD, _class_, "_RCMENU01_", "PSG.K_CHECKBOX_RUNAWAY", "toggle K_CHECKBOX_RUNAWAY",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_CURRENT_INTERVAL_COUNT00", FMAX.SCTN09FF_TEXT_DEF, _class_, "_TEXT_CURRENT_INTERVAL_COUNT_", "False", "class text for interval count",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_CURRENT_INTERVAL_COUNT01", FMAX.SCTN09FF_TEXT_PARM_ADD, _class_, "_TEXT_CURRENT_INTERVAL_COUNT_", "**PSG.TEXT_CURRENT_INTERVAL_COUNT", "interval count template",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_CURRENT_INTERVAL_COUNT01", FMAX.SCTN09FF_TEXT_VAL_ADD, _class_, "_TEXT_CURRENT_INTERVAL_COUNT_", "PSG.KEY", "PSG", "K_CURRENT_INTERVAL_COUNT", "interval count template",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_NAME_NEXT_EVENT00", FMAX.SCTN09FF_TEXT_DEF, _class_, "_TEXT_NAME_NEXT_EVENT_", "False", "class text for interval count",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_NAME_NEXT_EVENT01", FMAX.SCTN09FF_TEXT_PARM_ADD, _class_, "_TEXT_NAME_NEXT_EVENT_", "**PSG.TEXT_NAME_NEXT_EVENT", "interval count template",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_NAME_NEXT_EVENT01", FMAX.SCTN09FF_TEXT_VAL_ADD, _class_, "_TEXT_NAME_NEXT_EVENT_", "PSG.KEY", "PSG", "K_NAME_NEXT_EVENT", "interval count template",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_TIME_AT_ZERO00", FMAX.SCTN09FF_TEXT_DEF, _class_, "_TEXT_TIME_S_AT_ZEROELAPSE_", "True", "class text for interval count",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_TIME_AT_ZERO01", FMAX.SCTN09FF_TEXT_PARM_ADD, _class_, "_TEXT_TIME_S_AT_ZEROELAPSE_", "**PSG.TEXT_TIME_S_AT_ZEROELAPSE", "interval count template",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_TIME_AT_ZERO01", FMAX.SCTN09FF_TEXT_VAL_ADD, _class_, "_TEXT_TIME_S_AT_ZEROELAPSE_", "PSG.KEY", "PSG", "K_TIME_F_AT_ZEROELAPSE", "interval count template",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_TIME_S_AT_NEXT_ALERT00", FMAX.SCTN09FF_TEXT_DEF, _class_, "_TEXT_TIME_S_AT_NEXT_ALERT_", "True", "class text for interval count",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_TIME_S_AT_NEXT_ALERT01", FMAX.SCTN09FF_TEXT_PARM_ADD, _class_, "_TEXT_TIME_S_AT_NEXT_ALERT_", "**PSG.TEXT_TIME_S_AT_NEXT_ALERT", "interval count template",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_TIME_S_AT_NEXT_ALERT01", FMAX.SCTN09FF_TEXT_VAL_ADD, _class_, "_TEXT_TIME_S_AT_NEXT_ALERT_", "PSG.KEY", "PSG", "K_TIME_S_AT_NEXT_ALERT", "interval count template",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_TIME_S_CLOCK00", FMAX.SCTN09FF_TEXT_DEF, _class_, "_TEXT_TIME_S_CLOCK_", "True", "class text for interval count",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_TIME_S_CLOCK01", FMAX.SCTN09FF_TEXT_PARM_ADD, _class_, "_TEXT_TIME_S_CLOCK_", "**PSG.TEXT_TIME_S_CLOCK", "interval count template",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_TIME_S_CLOCK01", FMAX.SCTN09FF_TEXT_VAL_ADD, _class_, "_TEXT_TIME_S_CLOCK_", "PSG.KEY", "PSG", "K_TIME_S_CLOCK", "interval count template",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_TIME_S_ELAPSED00", FMAX.SCTN09FF_TEXT_DEF, _class_, "_TEXT_TIME_S_ELAPSED_", "True", "class text for interval count",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_TIME_S_ELAPSED01", FMAX.SCTN09FF_TEXT_PARM_ADD, _class_, "_TEXT_TIME_S_ELAPSED_", "**PSG.TEXT_TIME_S_ELAPSED", "interval count template",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_TIME_S_ELAPSED01", FMAX.SCTN09FF_TEXT_VAL_ADD, _class_, "_TEXT_TIME_S_ELAPSED_", "PSG.KEY", "PSG", "K_TIME_S_ELAPSED", "interval count template",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_TIME_S_TOGO00", FMAX.SCTN09FF_TEXT_DEF, _class_, "_TEXT_TIME_S_TOGO_", "True", "class text for interval count",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_TIME_S_TOGO01", FMAX.SCTN09FF_TEXT_PARM_ADD, _class_, "_TEXT_TIME_S_TOGO_", "**PSG.TEXT_TIME_S_TOGO", "interval count template",), __ID__),
	(("PSGVAL__CLOCKS_TEXT_TIME_S_TOGO01", FMAX.SCTN09FF_TEXT_VAL_ADD, _class_, "_TEXT_TIME_S_TOGO_", "PSG.KEY", "PSG", "K_TIME_S_TOGO", "interval count template",), __ID__),
	(("PSGVAL__CLOCKS_WINDOW", FMAX.NOP, "the window for APPMODE_CLOCKS",), __ID__),
	(("PSGVAL__CLOCKS_WINDOW00", FMAX.SCTN09FF_WINDOW_DEF, _class_, "_WINDOW_", "define the clocks window",), __ID__),
	(("PSGVAL__CLOCKS_WINDOW01", FMAX.SCTN09FF_WINDOW_VAL_ADD, _class_, "_WINDOW_", "PSG.ALPHA_CHANNEL", "PSG.SZ_ALPHA_HIGH", "set the high alpha as the default",), __ID__),
	(("PSGVAL__CLOCKS_WINDOW01", FMAX.SCTN09FF_WINDOW_VAL_ADD, _class_, "_WINDOW_", "PSG.BACKGROUND_COLOR", "PSG.COLOR_BACKGROUND", "eliminate all not useful on the floating clocks",), __ID__),
	(("PSGVAL__CLOCKS_WINDOW01", FMAX.SCTN09FF_WINDOW_VAL_ADD, _class_, "_WINDOW_", "PSG.BORDER_DEPTH", "PSG.SZ_BORDER_DEPTH", "border depth to zero",), __ID__),
	(("PSGVAL__CLOCKS_WINDOW01", FMAX.SCTN09FF_WINDOW_VAL_ADD, _class_, "_WINDOW_", "PSG.ELEMENT_PADDING", "PSG.SZ_PAD_ALL", "all padding for elements ((1, 1), (1, 1)) by default",), __ID__),
	(("PSGVAL__CLOCKS_WINDOW01", FMAX.SCTN09FF_WINDOW_VAL_ADD, _class_, "_WINDOW_", "PSG.FORCE_TOPLEVEL", "None", "",), __ID__),
	(("PSGVAL__CLOCKS_WINDOW01", FMAX.SCTN09FF_WINDOW_VAL_ADD, _class_, "_WINDOW_", "PSG.GRAB_ANYWHERE", "True", "eliminate all not useful on the floating clocks",), __ID__),
	(("PSGVAL__CLOCKS_WINDOW01", FMAX.SCTN09FF_WINDOW_VAL_ADD, _class_, "_WINDOW_", "PSG.KEEP_ON_TOP", "True", "eliminate all not useful on the floating clocks",), __ID__),
	(("PSGVAL__CLOCKS_WINDOW01", FMAX.SCTN09FF_WINDOW_VAL_ADD, _class_, "_WINDOW_", "PSG.LAYOUT", "self._LAYOUT_", "add the layout for CLOCKS_WINDOW",), __ID__),
	(("PSGVAL__CLOCKS_WINDOW01", FMAX.SCTN09FF_WINDOW_VAL_ADD, _class_, "_WINDOW_", "PSG.MARGINS", "PSG.SZ_MARGINS_ALL", "",), __ID__),
	(("PSGVAL__CLOCKS_WINDOW01", FMAX.SCTN09FF_WINDOW_VAL_ADD, _class_, "_WINDOW_", "PSG.NO_TITLEBAR", "True", "no titlebar on APPMODE_CLOCKS window",), __ID__),
	(("PSGVAL__CLOCKS_WINDOW01", FMAX.SCTN09FF_WINDOW_VAL_ADD, _class_, "_WINDOW_", "PSG.TITLE", "PSG.TITLE_CLOCKS", "",), __ID__),
]
# ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰


#
#
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * end of FM/TBGLST_D/_03_01_PSG_CLOCKS_C_NEW.py
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
#
#


#
