__TIMEOUT__ = "__TIMEOUT__"  # default timeout key
APPMODE_CLOCKS = "APPMODE_CLOCKS"  # mode clocks only
APPMODE_EDIT = "APPMODE_EDIT"  # edit mode on top of main window
APPMODE_MAIN = "APPMODE_MAIN"  # main mode (xpand from clocks to this)
APPMODE_MOUSE_OVER = "APPMODE_MOUSE_OVER"  # mouseOver mode (xpand from clocks to this)
APPMODE_NEW_ALARMPOPUP = "APPMODE_NEW_ALARMPOPUP"  # main mode (xpand from clocks to this)
APPMODE_NONE = "APPMODE_NONE"  # NONE mode
APPMODE_THECLOCK = "APPMODE_THECLOCK"  # theClock mode (xpand from clocks to this)
EVENTMODE_ALARM = "EVENTMODE_ALARM"  #
EVENTMODE_INTERVAL = "EVENTMODE_INTERVAL"  #
EVENTMODE_NONE = "EVENTMODE_NONE"  # what mode is this event
F___ENTER__ = "F___ENTER__"  # define __enter__
F___EXIT__ = "F___EXIT__"  # define __exit__ in CLOCKS
F___INIT__ = "F___INIT__"  # define a DPD at /
F_APPDSDECODE = "F_APPDSDECODE"  # fkey ENTRY appdsDecode
F_CHECKMOUSE = "F_CHECKMOUSE"  # define checkMouse
F_COMPAREBBOX = "F_COMPAREBBOX"  # FKEY entry compareBBox
F_COMPAREXY = "F_COMPAREXY"  # FKEY entry compareXY
F_DEBUGPRINT = "F_DEBUGPRINT"  # print debug info
F_DOIT = "F_DOIT"  # FKEY entry doit
F_DOMIDNIGHTWORK = "F_DOMIDNIGHTWORK"  # FKEY entry doMidnightWork
F_DOSTARTUP = "F_DOSTARTUP"  # FKEY entry doStartup
F_EASYUPDATE = "F_EASYUPDATE"  # load the whole thing from the file for easyUpdate
F_EASYUPDATEPARMS = "F_EASYUPDATEPARMS"  # load the whole thing from the file for easyUpdate
F_ENINT = "F_ENINT"  # convert any str in _DICTIN_ to int
F_ENSTRING = "F_ENSTRING"  # update _DICTINSTR_ or return strings converted from integers in _DICTIN_
F_FINDNEXTALARMEVENT = "F_FINDNEXTALARMEVENT"  # FKEY entry findNextAlarmEvent
F_FIXTIMEATNEXT = "F_FIXTIMEATNEXT"  # FKEY entry fixTimeAtNext
F_GETBBOX = "F_GETBBOX"  # FKEY entry getBBox
F_GETCLOSEBBOX = "F_GETCLOSEBBOX"  # FKEY entry getCloseBBox
F_GETMOUSEPOS = "F_GETMOUSEPOS"  # FKEY entry getMousePos
F_HANDLEEVENTS = "F_HANDLEEVENTS"  # turn interval count off
F_HANDLEVALUES = "F_HANDLEVALUES"  # turn interval count off
F_HIDE = "F_HIDE"  # convert any str in _DICTIN_ to int
F_INNERLOOP = "F_INNERLOOP"  # FKEY entry doit
F_INTERVALCOUNTOFF = "F_INTERVALCOUNTOFF"  # turn interval count off
F_INTERVALCOUNTON = "F_INTERVALCOUNTON"  # turn interval count on
F_ISINBBOX = "F_ISINBBOX"  # FKEY entry isInBBox
F_LOCALTIMES = "F_LOCALTIMES"  # FKEY entry localTimes
F_MAKEINKEY = "F_MAKEINKEY"  # make a human key from a PSG key
F_MAKEOUTKEY = "F_MAKEOUTKEY"  # make a key used in PSG from a human key
F_MIDNIGHT = "F_MIDNIGHT"  # make a key used in PSG from a human key
F_OUTERLOOP = "F_OUTERLOOP"  # FKEY entry outerLoop
F_QUICKREAD = "F_QUICKREAD"  # read the frame and set self._RESULT_ etc
F_RUNAWAY = "F_RUNAWAY"  # define runaway
F_SETCHECKBOX = "F_SETCHECKBOX"  # define setCheckbox
F_SPLITBBOXTORAW = "F_SPLITBBOXTORAW"  # FKEY entry splitBBoxToRaw
F_SPLITXYTORAW = "F_SPLITXYTORAW"  # FKEY entry splitXYToRaw
F_TOOLTIPOFF = "F_TOOLTIPOFF"  # define tooltipOff
F_TOOLTIPON = "F_TOOLTIPON"  # define tooltipOn
F_UNHIDE = "F_UNHIDE"  # convert any str in _DICTIN_ to int
F_UPDATE = "F_UPDATE"  # define the required update function
F_UPDATEFLIPPEDITEMS = "F_UPDATEFLIPPEDITEMS"  # update items which may have multiple values
F_UPDATEFROMDICT = "F_UPDATEFROMDICT"  # update the displayed info from a dict or the default _DICTIN_
F_UPDATEINTERVAL = "F_UPDATEINTERVAL"  # FKEY entry updateInterval
F_ZEROFLIPPED = "F_ZEROFLIPPED"  # update the displayed info from a dict or the default _DICTIN_
FORM_CLOCKS = "FORM_CLOCKS"  # holds all of clocks form entries
FORM_EDITENTRY = "FORM_EDITENTRY"  # holds all of form edit-entry entries
FORM_EDITOR = "FORM_EDITOR"  # holds all of form editor entries
FORM_MAIN = "FORM_MAIN"  # holds all of form main entries
FORM_POPUP01 = "FORM_POPUP01"  # holds all of form popup entries
FORM_POPUP02 = "FORM_POPUP02"  # holds all of form popup entries
FORM_POPUP03 = "FORM_POPUP03"  # holds all of form popup entries
FORM_POPUP04 = "FORM_POPUP04"  # holds all of form popup entries
FORM_POPUP05 = "FORM_POPUP05"  # holds all of form popup entries
FORM_THECLOCK = "FORM_THECLOCK"  # holds all of theclock form entries
K_ALARMPOPUP_TEXT_TEXT = "K_ALARMPOPUP_TEXT_TEXT"  # key for the text on a popup
K_ALERTING_LIST = "K_ALERTING_LIST"  # list that holds all currently alarming events
K_ALPHA_CHANNEL = "K_ALPHA_CHANNEL"  #
K_ALPHA_HIGH = "K_ALPHA_HIGH"  #
K_ALPHA_LOW = "K_ALPHA_LOW"  #
K_APPMODE = "K_APPMODE"  # no appmode set
K_AUTO_CLOSE_DURATION = "K_AUTO_CLOSE_DURATION"  # auto close alert time of this event
K_BBOX = "K_BBOX"  #
K_BTN_DISMISS = "K_BTN_DISMISS"  # button xpand font
K_BTN_DOWN = "K_BTN_DOWN"  # focus on click
K_BTN_EDIT = "K_BTN_EDIT"  # button xpand key
K_BTN_QUIT_ALL = "K_BTN_QUIT_ALL"  # button xpand font
K_BTN_UP = "K_BTN_UP"  # button up key
K_BTN_XPAND = "K_BTN_XPAND"  # button xpand font
K_BTN_ZERO = "K_BTN_ZERO"  # button zero key
K_CHANGED_EVENTS = "K_CHANGED_EVENTS"  # comment
K_CHANGED_LOCATION = "K_CHANGED_LOCATION"  # comment
K_CHANGED_MOUSE_LOCATION = "K_CHANGED_MOUSE_LOCATION"  # comment
K_CHANGED_VALUES = "K_CHANGED_VALUES"  # comment
K_CHECKBOX_ALPHA_DIM = "K_CHECKBOX_ALPHA_DIM"  # value of the alphas dim checkbox
K_CHECKBOX_DISMISSED = "K_CHECKBOX_DISMISSED"  # set the key for the checkbox
K_CHECKBOX_ENABLED = "K_CHECKBOX_ENABLED"  # set the key for the checkbox
K_CHECKBOX_FIRSTRUN = "K_CHECKBOX_FIRSTRUN"  # set the key for the checkbox
K_CHECKBOX_HIDE = "K_CHECKBOX_HIDE"  # checkbox hid for a moment when the mouse hovers
K_CHECKBOX_HOVER_DATE = "K_CHECKBOX_HOVER_DATE"  # checkbox hid for a moment when the mouse hovers
K_CHECKBOX_IS_ALERTING_NOW = "K_CHECKBOX_IS_ALERTING_NOW"  # set the key for the checkbox
K_CHECKBOX_PREDISMISSABLE = "K_CHECKBOX_PREDISMISSABLE"  # set the key for the checkbox
K_CHECKBOX_RUNAWAY = "K_CHECKBOX_RUNAWAY"  # value of runaway checkbox
K_CHECKBOX_SNOOZABLE = "K_CHECKBOX_SNOOZABLE"  # set the key for the checkbox
K_CHECKBOX_SNOOZED = "K_CHECKBOX_SNOOZED"  # set the key for the checkbox
K_CLOSE_BBOX = "K_CLOSE_BBOX"  #
K_COLOR_ALERT_BACKGROUND = "K_COLOR_ALERT_BACKGROUND"  # alert background color
K_COLOR_ALERT_TEXT = "K_COLOR_ALERT_TEXT"  # color of text on alert popup
K_COLOR_BACKGROUND = "K_COLOR_BACKGROUND"  # the background of the main frames
K_COLOR_BLACK = "K_COLOR_BLACK"  # black
K_COLOR_BTN_BACKGROUND = "K_COLOR_BTN_BACKGROUND"  # background color on buttons by default
K_COLOR_BTN_TEXT = "K_COLOR_BTN_TEXT"  # text color on buttons by default
K_COLOR_CLOCK_BACKGROUND = "K_COLOR_CLOCK_BACKGROUND"  # the background of the main frames
K_COLOR_GRAY3 = "K_COLOR_GRAY3"  # gray 3
K_COLOR_GRAY6 = "K_COLOR_GRAY6"  # gray 6
K_COLOR_GRAY9 = "K_COLOR_GRAY9"  # gray 9
K_COLOR_GRAYC = "K_COLOR_GRAYC"  # gray C
K_COLOR_TEXT_CURRENT_INTERVAL_COUNT_INACTIVE = "K_COLOR_TEXT_CURRENT_INTERVAL_COUNT_INACTIVE"  # the GRAY color used when the next event is not an interval
K_COLOR_TEXT_HIGH = "K_COLOR_TEXT_HIGH"  # the highlight color used in blinking bits when they are 'lit'
K_COLOR_TEXT_LOW = "K_COLOR_TEXT_LOW"  # the color the clock digits are
K_COLOR_TEXT_NORMAL = "K_COLOR_TEXT_NORMAL"  # the color the clock digits are
K_COLOR_TEXT_SPIN = "K_COLOR_TEXT_SPIN"  # the color the clock digits are
K_COLOR_TIME_CLOCK = "K_COLOR_TIME_CLOCK"  # color of the clock on any window/frame/etc.
K_COLOR_TIME_ELAPSED = "K_COLOR_TIME_ELAPSED"  # color of the clock on any window/frame/etc.
K_COLOR_TIME_TOGO = "K_COLOR_TIME_TOGO"  # color of the clock on any window/frame/etc.
K_COLOR_WHITE = "K_COLOR_WHITE"  # white
K_COLORS_BTN_NORMAL = "K_COLORS_BTN_NORMAL"  # comment
K_COLORS_TEXT_HIGH = "K_COLORS_TEXT_HIGH"  # combined colors for a clock text element
K_COLORS_TEXT_LOW = "K_COLORS_TEXT_LOW"  # combined colors for a clock text element
K_COLORS_TEXT_NORMAL = "K_COLORS_TEXT_NORMAL"  # combined colors for a clock text element
K_COLORS_TIME_CLOCK = "K_COLORS_TIME_CLOCK"  # combined colors for a clock text element
K_COLORS_TIME_ELAPSED = "K_COLORS_TIME_ELAPSED"  # combined colors for a clock text element
K_COLORS_TIME_TOGO = "K_COLORS_TIME_TOGO"  # combined colors for a clock text element
K_COLUMN01B = "K_COLUMN01B"  # the column that puts the two smaller clocks above the main one
K_COLUMN02 = "K_COLUMN02"  # the column that puts the two smaller clocks below the main one
K_CURRENT_EVENT = "K_CURRENT_EVENT"  #
K_CURRENT_EVENTMODE = "K_CURRENT_EVENTMODE"  #
K_CURRENT_EVENTMODE_VAL = "K_CURRENT_EVENTMODE_VAL"  # comment
K_CURRENT_FLIP_INFO = "K_CURRENT_FLIP_INFO"  #
K_CURRENT_INTERVAL_COUNT = "K_CURRENT_INTERVAL_COUNT"  # comment
K_CURRENT_LOCATION = "K_CURRENT_LOCATION"  #
K_CURRENT_MOUSE_LOCATION = "K_CURRENT_MOUSE_LOCATION"  #
K_CURRENT_MOUSE_STATUS = "K_CURRENT_MOUSE_STATUS"  #
K_CURRENT_VALUES = "K_CURRENT_VALUES"  #
K_CURRENTLY_DIMMED = "K_CURRENTLY_DIMMED"  #
K_DEVMODE = "K_DEVMODE"  # comment
K_DICT_ALL_THE_FORMS = "K_DICT_ALL_THE_FORMS"  # comment
K_DICT_KEYS = "K_DICT_KEYS"  #
K_DICT_KEYS_REVERSE = "K_DICT_KEYS_REVERSE"  #
K_DISMISSED = "K_DISMISSED"  # is this event dismissed
K_DPD_ROOT = "K_DPD_ROOT"  # DPD_ROOT defined
K_EMPTY_BBOX = "K_EMPTY_BBOX"  # empty XY dict
K_EMPTY_TUPDICT_FLIP_INFO = "K_EMPTY_TUPDICT_FLIP_INFO"  # easy dict for flip info in class passed as a list of these dicts
K_EMPTY_XY = "K_EMPTY_XY"  # empty XY dict
K_ENABLED = "K_ENABLED"  # is this event enabled
K_EVENT_ENTRIES = "K_EVENT_ENTRIES"  #
K_EVENT_NAME = "K_EVENT_NAME"  # name of the event
K_EVENTMODE = "K_EVENTMODE"  # this entry's event_mode
K_EXITING = "K_EXITING"  # this class is currently being exited bool
K_FIRSTRUN = "K_FIRSTRUN"  # are we initializing or not
K_FONT_DEFAULT = "K_FONT_DEFAULT"  # default font my favorite readable font
K_FONTSZ_ALERT_TEXT = "K_FONTSZ_ALERT_TEXT"  # the font for the clocks only clock
K_FONTSZ_BTNS = "K_FONTSZ_BTNS"  # comment
K_FONTSZ_CLOCKS_CURRENT_INTERVAL_COUNT = "K_FONTSZ_CLOCKS_CURRENT_INTERVAL_COUNT"  # the font for the clocks only clock
K_FONTSZ_CLOCKS_TIME_S_CLOCK = "K_FONTSZ_CLOCKS_TIME_S_CLOCK"  # the font for the clocks only clock
K_FONTSZ_CLOCKS_TIME_S_ELAPSED = "K_FONTSZ_CLOCKS_TIME_S_ELAPSED"  # the font for the clocks only clock
K_FONTSZ_CLOCKS_TIME_S_TOGO = "K_FONTSZ_CLOCKS_TIME_S_TOGO"  # the font for the clocks only clock
K_FORMNAME = "K_FORMNAME"  # time of this event
K_HIDDEN = "K_HIDDEN"  # bool are we hidden or not
K_INDEX_EAST = "K_INDEX_EAST"  # EAST
K_INDEX_NORTH = "K_INDEX_NORTH"  # NORTH
K_INDEX_OF_NEXT_EVENT = "K_INDEX_OF_NEXT_EVENT"  # holds events
K_INDEX_SOUTH = "K_INDEX_SOUTH"  # SOUTH
K_INDEX_WEST = "K_INDEX_WEST"  # WEST
K_INDEX_X = "K_INDEX_X"  # X
K_INDEX_Y = "K_INDEX_Y"  # Y
K_IS_ALERTING_NOW = "K_IS_ALERTING_NOW"  # count of number of times this has alerted since last reset
K_K_ALARMPOPUP_TEXT_TEXT = "K_K_ALARMPOPUP_TEXT_TEXT"  # alarm text for this event
K_K_EVENT_NAME = "K_K_EVENT_NAME"  # this entry's name
K_K_TIME_S_AT_ALARM = "K_K_TIME_S_AT_ALARM"  # time of this event if it an alarm
K_LIST_ALL_TIMES = "K_LIST_ALL_TIMES"  # list of all times
K_LIST_APPDS_MIDNIGHT_FIX_TIMES = "K_LIST_APPDS_MIDNIGHT_FIX_TIMES"  # list of times to be updated at midnight
K_LIST_CLOSE = "K_LIST_CLOSE"  # list with close statuses
K_LIST_DNUPDATE = "K_LIST_DNUPDATE"  # list of all element key not to update through the normal methods (checkboxes, etc. that need to be updated differently)
K_LIST_KEYS_TIME = "K_LIST_KEYS_TIME"  #
K_LIST_POPUP = "K_LIST_POPUP"  # popup list
K_LIST_THIS_ALARM_POPUP_TEXT = "K_LIST_THIS_ALARM_POPUP_TEXT"  # collects the text to popup
K_MAINFRAME = "K_MAINFRAME"  #
K_MLCN = "K_MLCN"  # short cut to get mouse position
K_MPX = "K_MPX"  # comment
K_NAME = "K_NAME"  #
K_NAME_NEXT_EVENT = "K_NAME_NEXT_EVENT"  # interval count template
K_NAME_NEXT_EVENT_STR = "K_NAME_NEXT_EVENT_STR"  # comment
K_NOW_NOMS = "K_NOW_NOMS"  # comment
K_NOWM = "K_NOWM"  # comment
K_NOWMS = "K_NOWMS"  # comment
K_NOWS = "K_NOWS"  # comment
K_PERIODIC = "K_PERIODIC"  #
K_PKLJAR = "K_PKLJAR"  # comment
K_PREDISMISSABLE = "K_PREDISMISSABLE"  # is this event dismissable in advance
K_SCREEN_DIMS = "K_SCREEN_DIMS"  #
K_SIZE = "K_SIZE"  #
K_SNOOZABLE = "K_SNOOZABLE"  # can this event be snoozed
K_SNOOZED = "K_SNOOZED"  # is this event snoozed
K_SZ_ALERT_TEXT = "K_SZ_ALERT_TEXT"  # font size of alert text
K_SZ_ALPHA_DIM = "K_SZ_ALPHA_DIM"  # default alpha dim state
K_SZ_ALPHA_HIGH = "K_SZ_ALPHA_HIGH"  # high alpha
K_SZ_ALPHA_LOW = "K_SZ_ALPHA_LOW"  # low alpha
K_SZ_BORDER_DEPTH = "K_SZ_BORDER_DEPTH"  # border depth
K_SZ_BTNS = "K_SZ_BTNS"  # font size for button text
K_SZ_CLOCKS_TIME_S_CLOCK = "K_SZ_CLOCKS_TIME_S_CLOCK"  # font size of the main clock on the clocks only floating widget
K_SZ_CLOCKS_TIME_S_ELAPSED = "K_SZ_CLOCKS_TIME_S_ELAPSED"  # font size of the elapsed clock on the clocks only floating widget
K_SZ_CLOCKS_TIME_S_TOGO = "K_SZ_CLOCKS_TIME_S_TOGO"  # font size of the main togo clock on the clocks only floating widget
K_SZ_CLOSE = "K_SZ_CLOSE"  # close enough to move from the mouse
K_SZ_CURRENT_INTERVAL_COUNT = "K_SZ_CURRENT_INTERVAL_COUNT"  # font size of the main interval count
K_SZ_EDIT_TIME_S_CLOCK = "K_SZ_EDIT_TIME_S_CLOCK"  # font size of the main clock on the clocks only floating widget
K_SZ_EDIT_TIME_S_ELAPSED = "K_SZ_EDIT_TIME_S_ELAPSED"  # font size of the elapsed clock on the clocks only floating widget
K_SZ_EDIT_TIME_S_TOGO = "K_SZ_EDIT_TIME_S_TOGO"  # font size of the main togo clock on the clocks only floating widget
K_SZ_MAIN_TIME_S_CLOCK = "K_SZ_MAIN_TIME_S_CLOCK"  # font size of the main clock on the clocks only floating widget
K_SZ_MAIN_TIME_S_ELAPSED = "K_SZ_MAIN_TIME_S_ELAPSED"  # font size of the elapsed clock on the clocks only floating widget
K_SZ_MAIN_TIME_S_TOGO = "K_SZ_MAIN_TIME_S_TOGO"  # font size of the main togo clock on the clocks only floating widget
K_SZ_MARGINS_ALL = "K_SZ_MARGINS_ALL"  # all margins default
K_SZ_MAX_DELTA = "K_SZ_MAX_DELTA"  # maximum possible change per move
K_SZ_MOVE_DIST = "K_SZ_MOVE_DIST"  # move by this pixels each jump
K_SZ_PAD_ALL = "K_SZ_PAD_ALL"  # add padding to all the things
K_SZ_PKLNAME_DEV = "K_SZ_PKLNAME_DEV"  # name of the pkl file for the app in dev
K_SZ_PKLNAME_PROD = "K_SZ_PKLNAME_PROD"  # name of the pkl file for the app in use
K_SZ_RUNAWAY = "K_SZ_RUNAWAY"  # default runaway state
K_SZ_TIME_MS_BETWEEN_FLIPS = "K_SZ_TIME_MS_BETWEEN_FLIPS"  # throttle flips
K_SZ_TIME_MS_BETWEEN_MOUSE_CHECKS = "K_SZ_TIME_MS_BETWEEN_MOUSE_CHECKS"  # throttle mouse checking
K_SZ_TIME_MS_BETWEEN_MOVES = "K_SZ_TIME_MS_BETWEEN_MOVES"  # time_ms between moves
K_SZ_TIME_MS_BETWEEN_UPDATES = "K_SZ_TIME_MS_BETWEEN_UPDATES"  # time_ms between updating windows/frames/etc
K_SZ_TIME_MS_TO_HIDE = "K_SZ_TIME_MS_TO_HIDE"  # unhide after this time
K_SZ_TIME_S_BETWEEN_PERIODIC_JOB = "K_SZ_TIME_S_BETWEEN_PERIODIC_JOB"  # time between periodic job runnings
K_SZ_TIMEOUT_MS = "K_SZ_TIMEOUT_MS"  # timeout for PSG
K_THIS_FORM_NAME = "K_THIS_FORM_NAME"  # adopt formName_
K_THIS_KEY_BASE = "K_THIS_KEY_BASE"  # adopt keyBase_
K_TIME_H_ADJUST_HRS = "K_TIME_H_ADJUST_HRS"  # comment
K_TIME_M_ADJUST_MINS = "K_TIME_M_ADJUST_MINS"  # comment
K_TIME_MS_AT_CHECK_MOUSE = "K_TIME_MS_AT_CHECK_MOUSE"  #
K_TIME_MS_AT_FLIP = "K_TIME_MS_AT_FLIP"  #
K_TIME_MS_AT_MOVE = "K_TIME_MS_AT_MOVE"  #
K_TIME_MS_AT_NEXT_MOVE_VAL = "K_TIME_MS_AT_NEXT_MOVE_VAL"  # comment
K_TIME_MS_AT_NEXT_UPDATE_VAL = "K_TIME_MS_AT_NEXT_UPDATE_VAL"  # comment
K_TIME_MS_AT_UNHIDE = "K_TIME_MS_AT_UNHIDE"  # the time when the window will unhide
K_TIME_MS_AT_UPDATE = "K_TIME_MS_AT_UPDATE"  #
K_TIME_S_ADJUST_VALUE = "K_TIME_S_ADJUST_VALUE"  # comment
K_TIME_S_AT_ALARM = "K_TIME_S_AT_ALARM"  # time of this event if it an alarm
K_TIME_S_AT_LAST_RUN = "K_TIME_S_AT_LAST_RUN"  # time this alarm last ran, now if running
K_TIME_S_AT_NEXT_ALERT = "K_TIME_S_AT_NEXT_ALERT"  # interval count template
K_TIME_S_AT_NEXT_EVENT_VAL = "K_TIME_S_AT_NEXT_EVENT_VAL"  # comment
K_TIME_S_AT_NEXT_PERIODIC_JOB_VAL = "K_TIME_S_AT_NEXT_PERIODIC_JOB_VAL"  # seconds till next housekeeping, check for next times, etc.
K_TIME_F_AT_ZEROELAPSE = "K_TIME_F_AT_ZEROELAPSE"  # interval count template
K_TIME_S_CLOCK = "K_TIME_S_CLOCK"  # interval count template
K_TIME_S_ELAPSED = "K_TIME_S_ELAPSED"  # interval count template
K_TIME_S_INTERVAL = "K_TIME_S_INTERVAL"  # interval of this event
K_TIME_S_INTERVAL__BEGIN = "K_TIME_S_INTERVAL__BEGIN"  # time of the day this interval is made active
K_TIME_S_INTERVAL__END = "K_TIME_S_INTERVAL__END"  # time of the day this interval is no longer active
K_TIME_S_INTERVAL_START = "K_TIME_S_INTERVAL_START"  # time of the day this round of interval started
K_TIME_S_LEN_OF_ALERT = "K_TIME_S_LEN_OF_ALERT"  # length of time to alert this event before auto closing it
K_TIME_S_TOGO = "K_TIME_S_TOGO"  # interval count template
K_TITLE_ALARMPOPUP = "K_TITLE_ALARMPOPUP"  # string with window title for APPMODE_CLOCKS
K_TITLE_CLOCKS = "K_TITLE_CLOCKS"  # string with window title for APPMODE_CLOCKS
K_TITLE_EDIT = "K_TITLE_EDIT"  # string with window title for APPMODE_CLOCKS
K_TITLE_MAIN = "K_TITLE_MAIN"  # string with window title for APPMODE_CLOCKS
K_TITLE_THECLOCK = "K_TITLE_THECLOCK"  # string with window title for APPMODE_CLOCKS
K_VERSION = "K_VERSION"  # version number hex string
K_ZERO_CLOCK = "K_ZERO_CLOCK"  # all the zeros
K_ZERO_CLOCKSTR = "K_ZERO_CLOCKSTR"  # all the zeros
MOUSE_STATUS_CLOSE_E = "MOUSE_STATUS_CLOSE_E"  # mouse is east of checked element
MOUSE_STATUS_CLOSE_N = "MOUSE_STATUS_CLOSE_N"  # mouse is north of checked element
MOUSE_STATUS_CLOSE_NE = "MOUSE_STATUS_CLOSE_NE"  # mouse is northeast of checked element
MOUSE_STATUS_CLOSE_NW = "MOUSE_STATUS_CLOSE_NW"  # mouse is northwest of checked element
MOUSE_STATUS_CLOSE_S = "MOUSE_STATUS_CLOSE_S"  # mouse is south of checked element
MOUSE_STATUS_CLOSE_SE = "MOUSE_STATUS_CLOSE_SE"  # mouse is southeast of checked element
MOUSE_STATUS_CLOSE_SW = "MOUSE_STATUS_CLOSE_SW"  # mouse is southwest of checked element
MOUSE_STATUS_CLOSE_W = "MOUSE_STATUS_CLOSE_W"  # mouse is west of checked element
MOUSE_STATUS_E = "MOUSE_STATUS_E"  # mouse is east of checked element
MOUSE_STATUS_N = "MOUSE_STATUS_N"  # mouse is north of checked element
MOUSE_STATUS_NE = "MOUSE_STATUS_NE"  # mouse is northeast of checked element
MOUSE_STATUS_NONE = "MOUSE_STATUS_NONE"  # mouse is unknown
MOUSE_STATUS_NW = "MOUSE_STATUS_NW"  # mouse is northwest of checked element
MOUSE_STATUS_OVER = "MOUSE_STATUS_OVER"  # mouse is over top of checked element
MOUSE_STATUS_S = "MOUSE_STATUS_S"  # mouse is south of checked element
MOUSE_STATUS_SE = "MOUSE_STATUS_SE"  # mouse is southeast of checked element
MOUSE_STATUS_SW = "MOUSE_STATUS_SW"  # mouse is southwest of checked element
MOUSE_STATUS_W = "MOUSE_STATUS_W"  # mouse is west of checked element
TITLE_ALARMPOPUP = "ALERT"  # string with window title for APPMODE_CLOCKS
TITLE_CLOCKS = "CLOCKS"  # string with window title for APPMODE_CLOCKS
TITLE_EDIT = "edit an event"  # string with window title for APPMODE_CLOCKS
TITLE_MAIN = "Main window which is xpanded from CLOCKS window and pops up EDIT windows"  # string with window title for APPMODE_CLOCKS
TITLE_THECLOCK = "THECLOCK"  # string with window title for APPMODE_CLOCKS
