TBGLST = [
	# fold here ⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1⥥1
	("CFVAL", FMAX_NOP, "CFVAL_BEGINS",),
	("CFVAL_____", FMAX_NOP, "CFVAL_ENDS",),
	("FMAXCF", FMAX_NOP, "FMAXCF_BEGINS",),
	("FMAXCF_SCTN0003_LAMBDA_DEF", FMAXFM_SCTN0101_AX_DEF, "define a lambda function <NAC><NAME><lambda str>",),
	("FMAXCF_SCTN0003_TYPE_DEF", FMAXFM_SCTN0101_AX_DEF, "define a fake type used in the translation dict <NAC><NAME><TYPE>",),
	("FMAXCF_SCTN0201_STR_DEF", FMAXFM_SCTN0101_AX_DEF, "define a STR in SCTN21 <NAC><NAME><str>",),
	("FMAXCF_SCTN0201_VAL_DEF", FMAXFM_SCTN0101_AX_DEF, "define a VAL in SCTN21 <NAC><NAME><VAL>",),
	("FMAXCF_SCTN0202_OPTIONSDICT_STR_ADD", FMAXFM_SCTN0101_AX_DEF, "define a OPTNAME: 'str' in SCTN202 <NAC><KEY><PARM><STRDEFAULT>",),
	("FMAXCF_SCTN0202_OPTIONSDICT_VAL_ADD", FMAXFM_SCTN0101_AX_DEF, "define a OPTNAME: VAL in SCTN202 <NAC><KEY><PARM><VALDEFAULT>",),
	("FMAXCF_SCTN0202_OPTIONS_ADD_HELP_LINE", FMAXFM_SCTN0101_AX_DEF, "add a line to the help for a PARM, after the comment is automatically added<NAC><PARM><ADDONHELPLINE>",),
	("FMAXCF_SCTN0202_OPTIONS_STR_ADD", FMAXFM_SCTN0101_AX_DEF, "define a '-a[=]' in SCTN22 <NAC><PARM><KEY><VAL>",),
	("FMAXCF_SCTN0202_OPTIONS_VAL_ADD", FMAXFM_SCTN0101_AX_DEF, "define a '-a[=]' in SCTN22 <NAC><PARM><KEY><VAL>",),
	("FMAXCF_SCTN0203_DICT_DEF", FMAXFM_SCTN0101_AX_DEF, "define a dict in SCTN203 <NAC><DICTNAME><DICTMODE>",),
	("FMAXCF_SCTN0203_DICT_STR_ADD", FMAXFM_SCTN0101_AX_DEF, "define a dict STR in SCTN203 <NAC><DICTNAME><STR>",),
	("FMAXCF_SCTN0203_DICT_VAL_ADD", FMAXFM_SCTN0101_AX_DEF, "define a dict VAL in SCTN203 <NAC><DICTNAME><VAL>",),
	("FMAXCF_SCTN0204_LIST_DEF", FMAXFM_SCTN0101_AX_DEF, "define a list in SCTN204 <NAC><LISTNAME>",),
	("FMAXCF_SCTN0204_LIST_STR_ADD", FMAXFM_SCTN0101_AX_DEF, "define a list STR in SCTN204 <NAC><LISTNAME><STR>",),
	("FMAXCF_SCTN0204_LIST_VAL_ADD", FMAXFM_SCTN0101_AX_DEF, "define a VAL in a list in SCTN204 <NAC><LISTNAME><VAL>",),
	("FMAXCF_____", FMAX_NOP, "FMAXCF_ENDS",),
	("FMAXFM", FMAX_NOP, "FMAXFM_BEGINS",),
	("FMAXFM_SCTN0101_AX_DEF", FMAXFM_SCTN0101_AX_DEF, "define a new FM action <NAC>",),
	("FMAXFM_SCTN0102_STR_DEF", FMAXFM_SCTN0101_AX_DEF, "define a FM string <NAC><VALNAME><STR>",),
	("FMAXFM_SCTN0102_VAL_DEF", FMAXFM_SCTN0101_AX_DEF, "define a FM value_ <NAC><VALNAME><VAL>",),
	("FMAXFM_SCTN0103_DICT_DEF", FMAXFM_SCTN0101_AX_DEF, "define a dict for FM <NAC>",),
	("FMAXFM_SCTN0104_LIST_DEF", FMAXFM_SCTN0101_AX_DEF, "define a list in FM <NAC>",),
	("FMAXFM_____", FMAX_NOP, "FMAXFM_ENDS",),
	("FMAXPSG", FMAX_NOP, "FMAXPSG_BEGINS",),
	("FMAXPSG_SCTN0900_KEY_DEF", FMAXFM_SCTN0101_AX_DEF, "put a key in def1 of PSG.py",),
	("FMAXPSG_SCTN0900_STR_DEF", FMAXFM_SCTN0101_AX_DEF, "define a string in the first section (colors, etc.) of defines in PSG.py <NAC><VALNAME><VAL>",),
	("FMAXPSG_SCTN0900_VAL_DEF", FMAXFM_SCTN0101_AX_DEF, "define a value in the first define section in PSG.py <NAC><VALNAME><VAL>",),
	("FMAXPSG_SCTN0901_DUBLT_SS_DEF", FMAXFM_SCTN0101_AX_DEF, "define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>",),
	("FMAXPSG_SCTN0901_DUBLT_SV_DEF", FMAXFM_SCTN0101_AX_DEF, "define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>",),
	("FMAXPSG_SCTN0901_DUBLT_VS_DEF", FMAXFM_SCTN0101_AX_DEF, "define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>",),
	("FMAXPSG_SCTN0901_DUBLT_VV_DEF", FMAXFM_SCTN0101_AX_DEF, "define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>",),
	("FMAXPSG_SCTN0901_KEY_DEF", FMAXFM_SCTN0101_AX_DEF, "define a key in the second section of defines in PSG.py <NAC><VALNAME>",),
	("FMAXPSG_SCTN0901_STR_DEF", FMAXFM_SCTN0101_AX_DEF, "define a string in the second section of defines in PSG.py <NAC><VALNAME><VAL>",),
	("FMAXPSG_SCTN0901_VAL_DEF", FMAXFM_SCTN0101_AX_DEF, "define a value in the second define section in PSG.py <NAC><VALNAME><VAL>",),
	("FMAXPSG_SCTN0902_DICT_DEF", FMAXFM_SCTN0101_AX_DEF, "define a dict in PSG <NAC><DICTNAME>",),
	("FMAXPSG_SCTN0902_DICT_SS_ADD", FMAXFM_SCTN0101_AX_DEF, "add a str-str to a dict <NAC><DICTNAME><STR><STR>",),
	("FMAXPSG_SCTN0902_DICT_STR_ADD", FMAXFM_SCTN0101_AX_DEF, "add a str to a dict <NAC><DICTNAME><KEY><VAL>",),
	("FMAXPSG_SCTN0902_DICT_SV_ADD", FMAXFM_SCTN0101_AX_DEF, "add a str-val to a dict <NAC><DICTNAME><STR><VAL>",),
	("FMAXPSG_SCTN0902_DICT_VAL_ADD", FMAXFM_SCTN0101_AX_DEF, "add a val to a dict in PSG <NAC><DICTNAME><KEY><VAL>",),
	("FMAXPSG_SCTN0903_LIST_DEF", FMAXFM_SCTN0101_AX_DEF, "define a list in PSG <NAC><LISTNAME>",),
	("FMAXPSG_SCTN0903_LIST_STR_ADD", FMAXFM_SCTN0101_AX_DEF, "add a str to a list in PSG <NAC><LISTNAME><STR>",),
	("FMAXPSG_SCTN0903_LIST_VAL_ADD", FMAXFM_SCTN0101_AX_DEF, "add a val to a list in PSG <NAC><LISTNAME><VAL>",),
	("FMAXPSG_SCTN0904_PLATEQ_ELIF_ADD", FMAXFM_SCTN0101_AX_DEF, "platform equalizer define an elif <NAC><STRUCTNAME><CONDITION><VAL>",),
	("FMAXPSG_SCTN0904_PLATEQ_ELSE_ADD", FMAXFM_SCTN0101_AX_DEF, "platform equalizer define an else <NAC><STRUCTNAME><CONDITION>",),
	("FMAXPSG_SCTN0904_PLATEQ_FUNC_STR_ADD", FMAXFM_SCTN0101_AX_DEF, "add a function string line <NAC><STRUCTNAME><CONDITION>",),
	("FMAXPSG_SCTN0904_PLATEQ_IF_ADD", FMAXFM_SCTN0101_AX_DEF, "add the 1st if to a platform equalizer <NAC><STRUCTNAME><CONDITION>",),
	("FMAXPSG_SCTN0904_PLATEQ_PLAT_DEF", FMAXFM_SCTN0101_AX_DEF, "define a platform equalizer struct <NAC><STRUCTNAME>",),
	("FMAXPSG_SCTN0904_PLATEQ_STR_ADD", FMAXFM_SCTN0101_AX_DEF, "add a string to a PLATEQ <NAC><STRUCTNAME><VALNAME><VAL>",),
	("FMAXPSG_SCTN0904_PLATEQ_VAL_ADD", FMAXFM_SCTN0101_AX_DEF, "add a value to a PLATEQ <NAC><STRUCTNAME><VALNAME><VAL>",),
	("FMAXPSG_SCTN0905_TUPDICT_DEF", FMAXFM_SCTN0101_AX_DEF, "define a TUPDICT in the second define section in PSG.py <NAC><TUPDICTNAME>",),
	("FMAXPSG_SCTN0905_TUPDICT_SS_ADD", FMAXFM_SCTN0101_AX_DEF, "add a str to a tupdict <NAC><TUPDICTNAME><STR><STR>",),
	("FMAXPSG_SCTN0905_TUPDICT_STR_ADD", FMAXFM_SCTN0101_AX_DEF, "add a str to a tupdict <NAC><TUPDICTNAME><KEY><STR>",),
	("FMAXPSG_SCTN0905_TUPDICT_SV_ADD", FMAXFM_SCTN0101_AX_DEF, "add a value to a tupdict <NAC><TUPDICTNAME><STR><VAL>",),
	("FMAXPSG_SCTN0905_TUPDICT_VAL_ADD", FMAXFM_SCTN0101_AX_DEF, "add a value to a tupdict <NAC><TUPDICTNAME><KEY><VAL>",),
	("FMAXPSG_SCTN0906_BTN_DEF", FMAXFM_SCTN0101_AX_DEF, "define a button <NAC><BTNNAME>",),
	("FMAXPSG_SCTN0906_BTN_STRADD", FMAXFM_SCTN0101_AX_DEF, "add a (VAL,VAL) to a tupdict <NAC><BTNNAME><KEY><VAL>",),
	("FMAXPSG_SCTN0906_BTN_VALADD", FMAXFM_SCTN0101_AX_DEF, "add a (VAL,VAL) to a tupdict <NAC><BTNNAME><KEY><VAL>",),
	("FMAXPSG_SCTN0907_SPIN_DEF", FMAXFM_SCTN0101_AX_DEF, "define a spin box entry <NAC><SPINNAME>",),
	("FMAXPSG_SCTN0907_SPIN_DICT_STR_ADD", FMAXFM_SCTN0101_AX_DEF, "add a STR to the SPINDICT <NAC><SPINNAME><KEY><STR>",),
	("FMAXPSG_SCTN0907_SPIN_DICT_VAL_ADD", FMAXFM_SCTN0101_AX_DEF, "add a VAL to the SPINDICT <NAC><SPINNAME><KEY><VAL>",),
	("FMAXPSG_SCTN0907_SPIN_VALUES_STR_ADD", FMAXFM_SCTN0101_AX_DEF, "add a STR to the values list <NAC><SPINNAME><STR>",),
	("FMAXPSG_SCTN0907_SPIN_VALUES_VAL_ADD", FMAXFM_SCTN0101_AX_DEF, "add a VAL to the values list <NAC><SPINNAME><VAL>",),
	("FMAXPSG_SCTN0908_CHECKBOX_DEF", FMAXFM_SCTN0101_AX_DEF, "define a checkbox <NAC><CHECKBOXNAME>",),
	("FMAXPSG_SCTN0908_CHECKBOX_STR_ADD", FMAXFM_SCTN0101_AX_DEF, "add a str to a checkbox <NAC><CHECKBOXNAME><KEY><VAL>",),
	("FMAXPSG_SCTN0908_CHECKBOX_VAL_ADD", FMAXFM_SCTN0101_AX_DEF, "add a val to a checkbox <NAC><CHECKBOXNAME><KEY><VAL>",),
	("FMAXPSG_SCTN0909_TEXT_DEF", FMAXFM_SCTN0101_AX_DEF, "define a text <NAC><TEXTNAME>",),
	("FMAXPSG_SCTN0909_TEXT_STR_ADD", FMAXFM_SCTN0101_AX_DEF, "add a str to a text element <NAC><TEXTNAME><KEY><VAL>",),
	("FMAXPSG_SCTN0909_TEXT_VAL_ADD", FMAXFM_SCTN0101_AX_DEF, "add a val to a text element <NAC><TEXTNAME>",),
	("FMAXPSG_SCTN090A_RADIO_DEF", FMAXFM_SCTN0101_AX_DEF, "define a radio button element",),
	("FMAXPSG_SCTN090B_COLUMN_BUTTON_ADD", FMAXFM_SCTN0101_AX_DEF, "add a button to a row <NAC><COLUMNNAME><ROWKEY><BTNKEY><BTNDEF>",),
	("FMAXPSG_SCTN090B_COLUMN_COMBO_ADD", FMAXFM_SCTN0101_AX_DEF, "add a combo to a row <NAC><COLUMNNAME><ROWKEY><COMBOKEY><COMBODEF>",),
	("FMAXPSG_SCTN090B_COLUMN_DEF", FMAXFM_SCTN0101_AX_DEF, "define a column <NAC><COLUMNNAME>",),
	("FMAXPSG_SCTN090B_COLUMN_RADIO_ADD", FMAXFM_SCTN0101_AX_DEF, "add a radio to a row <NAC><COLUMNNAME><ROWKEY><RADIOKEY><RADIODEF>",),
	("FMAXPSG_SCTN090B_COLUMN_ROW_ADD", FMAXFM_SCTN0101_AX_DEF, "add a row [] to a column <NAC><COLUMNNAME><ROWKEY>",),
	("FMAXPSG_SCTN090B_COLUMN_SPIN_ADD", FMAXFM_SCTN0101_AX_DEF, "add a spinbox to a row <NAC><COLUMNNAME><ROWKEY><SPINKEY><SPINDEF>",),
	("FMAXPSG_SCTN090B_COLUMN_TEXT_ADD", FMAXFM_SCTN0101_AX_DEF, "add a text to a row <NAC><COLUMNNAME><ROWKEY><TEXTKEY><TEXTDEF>",),
	("FMAXPSG_SCTN090C_MAINAPP_DICT_DICT_DEF", FMAXFM_SCTN0101_AX_DEF, "add a dict to the mainapp dict <NAC><DICTNAME",),
	("FMAXPSG_SCTN090C_MAINAPP_DICT_DICT_STR_ADD", FMAXFM_SCTN0101_AX_DEF, "add a string to a dict mainapp dict <NAC><DICTNAME><KEY><STR>",),
	("FMAXPSG_SCTN090C_MAINAPP_DICT_DICT_VAL_ADD", FMAXFM_SCTN0101_AX_DEF, "add a value to a dict mainapp dict <NAC><DICTNAME><KEY><VAL>",),
	("FMAXPSG_SCTN090C_MAINAPP_DICT_STR_ADD", FMAXFM_SCTN0101_AX_DEF, "add a string to the mainapp dict <NAC><KEY><STR>",),
	("FMAXPSG_SCTN090C_MAINAPP_DICT_VAL_ADD", FMAXFM_SCTN0101_AX_DEF, "add a value to the mainapp dict <NAC><KEY><VAL>",),
	("FMAXPSG_SCTN090D_FRAME_DEF", FMAXFM_SCTN0101_AX_DEF, "define a frame <NAC><FRAMENAME>",),
	("FMAXPSG_SCTN090E_LAYOUT_DEF", FMAXFM_SCTN0101_AX_DEF, "define layouts",),
	("FMAXPSG_SCTN090F_MAINDICT_DEF", FMAXFM_SCTN0101_AX_DEF, "define a main dictdict <NAC><MAINNAME>",),
	("FMAXPSG_SCTN090F_MAINDICT_DICT_DEF", FMAXFM_SCTN0101_AX_DEF, "add a str to the main dictdict",),
	("FMAXPSG_SCTN090F_MAINDICT_DICT_STR_ADD", FMAXFM_SCTN0101_AX_DEF, "add a str to the main dictdict",),
	("FMAXPSG_SCTN090F_MAINDICT_DICT_VAL_ADD", FMAXFM_SCTN0101_AX_DEF, "add a str to the main dictdict",),
	("FMAXPSG_SCTN090F_MAINDICT_STR_ADD", FMAXFM_SCTN0101_AX_DEF, "add a str to the main dictdict",),
	("FMAXPSG_SCTN090F_MAINDICT_VAL_ADD", FMAXFM_SCTN0101_AX_DEF, "add a str to the main dictdict",),
	("FMAXPSG_SCTN0910_DUBLT_SS_DEF", FMAXFM_SCTN0101_AX_DEF, "define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>",),
	("FMAXPSG_SCTN0910_DUBLT_SV_DEF", FMAXFM_SCTN0101_AX_DEF, "define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>",),
	("FMAXPSG_SCTN0910_DUBLT_VS_DEF", FMAXFM_SCTN0101_AX_DEF, "define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>",),
	("FMAXPSG_SCTN0910_DUBLT_VV_DEF", FMAXFM_SCTN0101_AX_DEF, "define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>",),
	("FMAXPSG_SCTN0910_STR_DEF", FMAXFM_SCTN0101_AX_DEF, "define a string in the second section of defines in PSG.py <NAC><VALNAME><VAL>",),
	("FMAXPSG_SCTN0910_VAL_DEF", FMAXFM_SCTN0101_AX_DEF, "define a value in the second define section in PSG.py <NAC><VALNAME><VAL>",),
	("FMAXPSG_SCTN0911_COMBO_DEF", FMAXFM_SCTN0101_AX_DEF, "define a combo box",),
	("FMAXPSG_____", FMAX_NOP, "FMAXPSG_ENDS",),
	("FMAX_NOP", FMAXFM_SCTN0101_AX_DEF, "skip this entry",),
	("FMCF", FMAX_NOP, "FMCF_BEGINS",),
	("FMCF_SCTN0003_TYPE_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN009 types comments",),
	("FMCF_SCTN0003_TYPE_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN003 types",),
	("FMCF_SCTN0201_DEF_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN201 defines comments dict",),
	("FMCF_SCTN0201_DEF_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN201 defines dict",),
	("FMCF_SCTN0202_OPTIONSDICT_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN202 OPTIONSDICT comments dict",),
	("FMCF_SCTN0202_OPTIONSDICT_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN202 OPTIONSDICT",),
	("FMCF_SCTN0202_OPTIONSHELPDICT_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN202 OPTIONS HELPDICT",),
	("FMCF_SCTN0202_OPTIONS_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN202 OPTIONS comments dict",),
	("FMCF_SCTN0202_OPTIONS_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN202 OPTIONS dict",),
	("FMCF_SCTN0203_DICT_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN203 dict comments dict",),
	("FMCF_SCTN0203_DICT_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN203 dict dict",),
	("FMCF_SCTN0204_LIST_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN204 list comments dict",),
	("FMCF_SCTN0204_LIST_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN204 list dict",),
	("FMCF_____", FMAX_NOP, "FMCF_ENDS",),
	("FMFM", FMAX_NOP, "FMFM_BEGINS",),
	("FMFM_SCTN0101_AX_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN101 FMAX defined",),
	("FMFM_SCTN0101_AX_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN101 FMAX defined",),
	("FMFM_SCTN0102_VAL_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN102 val",),
	("FMFM_SCTN0102_VAL_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN102 val",),
	("FMFM_SCTN0103_DICT_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN103 dict defined",),
	("FMFM_SCTN0103_DICT_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN103 dict defined",),
	("FMFM_SCTN0104_LIST_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN201 device defines",),
	("FMFM_SCTN0104_LIST_DICT", FMAXFM_SCTN0103_DICT_DEF, "SCTN201 device defines",),
	("FMFM_____", FMAX_NOP, "FMFM_ENDS",),
	("FMPSG", FMAX_NOP, "FMPSG_BEGINS",),
	("FMPSG_SCTN0900_DEF1_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_SCTN0900_DEF1_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_SCTN0901_DEF2_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_SCTN0901_DEF2_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_SCTN0902_DICT_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_SCTN0902_DICT_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_SCTN0903_LIST_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_SCTN0903_LIST_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_SCTN0904_PLATEQ_INNER_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_SCTN0904_PLATEQ_INNER_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_SCTN0904_PLATEQ_OUTER_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_SCTN0904_PLATEQ_OUTER_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_SCTN0905_TUPDICT_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_SCTN0905_TUPDICT_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_SCTN0906_BTNS_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds all of the button entries (TUPDICT)",),
	("FMPSG_SCTN0906_BTNS_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds all of the button entriess (TUPDICT)",),
	("FMPSG_SCTN0907_SPIN_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds the spin element stuffs (TUPDICT)f",),
	("FMPSG_SCTN0907_SPIN_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds the spin element stuffs (TUPDICT)",),
	("FMPSG_SCTN0907_SPIN_VALUES_LIST_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds the spin element stuffs (TUPDICT)",),
	("FMPSG_SCTN0908_CHECKBOX_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds all of the button entriess (TUPDICT)",),
	("FMPSG_SCTN0908_CHECKBOX_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds all of the button entriess (TUPDICT)",),
	("FMPSG_SCTN0909_TEXT_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds all of the button entries (TUPDICT)",),
	("FMPSG_SCTN0909_TEXT_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds all of the button entriess (TUPDICT)",),
	("FMPSG_SCTN090A_RADIO_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds all of the button entries (TUPDICT)",),
	("FMPSG_SCTN090A_RADIO_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds all of the button entriess (TUPDICT)",),
	("FMPSG_SCTN090B_COLUMNSCMNTDICT", FMAXFM_SCTN0103_DICT_DEF, "holds all of the button entries (TUPDICT)",),
	("FMPSG_SCTN090B_COLUMNS_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds all of the button entriess (TUPDICT)",),
	("FMPSG_SCTN090C_MAINAPP_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "the main app dict for this app",),
	("FMPSG_SCTN090C_MAINAPP_DICT", FMAXFM_SCTN0103_DICT_DEF, "the main app dict for this app",),
	("FMPSG_SCTN090D_FRAME_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds all of the button entries (TUPDICT)",),
	("FMPSG_SCTN090D_FRAME_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds all of the button entriess (TUPDICT)",),
	("FMPSG_SCTN090E_LAYOUT_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds all of the button entries (TUPDICT)",),
	("FMPSG_SCTN090E_LAYOUT_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds all of the button entriess (TUPDICT)",),
	("FMPSG_SCTN090F_MAINDICT_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds all of the button entries (TUPDICT)",),
	("FMPSG_SCTN090F_MAINDICT_DICT", FMAXFM_SCTN0103_DICT_DEF, "holds all of the button entriess (TUPDICT)",),
	("FMPSG_SCTN0910_DEF3_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_SCTN0910_DEF3_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_SCTN0911_COMBO_CMNT_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_SCTN0911_COMBO_DICT", FMAXFM_SCTN0103_DICT_DEF, "define the dict to hold everything in SCTN0900",),
	("FMPSG_____", FMAX_NOP, "FMPSG_ENDS",),
	("PSGVAL", FMAX_NOP, "FMPSG_BEGINS",),
	("PSGVAL_APPMODE_CLOCKS", FMAXPSG_SCTN0900_KEY_DEF, "APPMODE_CLOCKS", "mode clocks only",),
	("PSGVAL_APPMODE_EDIT", FMAXPSG_SCTN0900_KEY_DEF, "APPMODE_EDIT", "edit mode on top of main window",),
	("PSGVAL_APPMODE_MAIN", FMAXPSG_SCTN0900_KEY_DEF, "APPMODE_MAIN", "main mode (xpand from clocks to this)",),
	("PSGVAL_CLOCKS_SZ_TIME_CLOCK", FMAXPSG_SCTN0900_VAL_DEF, "CLOCKS_SZ_TIME_CLOCK", "20", "size of the main clock on the clocks only floating widget",),
	("PSGVAL_CLOCKS_SZ_TIME_ELAPSED", FMAXPSG_SCTN0900_VAL_DEF, "CLOCKS_SZ_TIME_ELAPSED", "10", "size of the elapsed clock on the clocks only floating widget",),
	("PSGVAL_CLOCKS_SZ_TIME_TOGO", FMAXPSG_SCTN0900_VAL_DEF, "CLOCKS_SZ_TIME_TOGO", "10", "size of the main togo clock on the clocks only floating widget",),
	("PSGVAL_COLOR_BACKGROUND", FMAXPSG_SCTN0900_STR_DEF, "COLOR_BACKGROUND", "#331122", "the background of the main frames",),
	("PSGVAL_COLOR_BLACK", FMAXPSG_SCTN0900_STR_DEF, "BLACK", "#000000", "black",),
	("PSGVAL_COLOR_BTN_BACKGROUND", FMAXPSG_SCTN0901_STR_DEF, "COLOR_BTN_BACKGROUND", "#441133", "background color on buttons by default",),
	("PSGVAL_COLOR_BTN_TEXT", FMAXPSG_SCTN0901_STR_DEF, "COLOR_BTN_TEXT", "#660044", "text color on buttons by default",),
	("PSGVAL_COLOR_CLOCK_BACKGROUND", FMAXPSG_SCTN0900_STR_DEF, "COLOR_CLOCK_BACKGROUND", "#221133", "the background of the main frames",),
	("PSGVAL_COLOR_GRAY3", FMAXPSG_SCTN0900_STR_DEF, "GRAY3", "#333333", "gray 3",),
	("PSGVAL_COLOR_GRAY6", FMAXPSG_SCTN0900_STR_DEF, "GRAY6", "#666666", "gray 6",),
	("PSGVAL_COLOR_GRAY9", FMAXPSG_SCTN0900_STR_DEF, "GRAY9", "#999999", "gray 9",),
	("PSGVAL_COLOR_GRAYC", FMAXPSG_SCTN0900_STR_DEF, "GRAYC", "#CCCCCC", "gray C",),
	("PSGVAL_COLOR_TEXT_HIGH", FMAXPSG_SCTN0900_STR_DEF, "COLOR_TEXT_HIGH", "#CC0088", "the highlight color used in blinking bits when they are 'lit'",),
	("PSGVAL_COLOR_TEXT_LOW", FMAXPSG_SCTN0900_STR_DEF, "COLOR_TEXT_LOW", "#330022", "the color the clock digits are",),
	("PSGVAL_COLOR_TEXT_NORMAL", FMAXPSG_SCTN0900_STR_DEF, "COLOR_TEXT_NORMAL", "#660044", "the color the clock digits are",),
	("PSGVAL_COLOR_TIME_CLOCK", FMAXPSG_SCTN0900_STR_DEF, "COLOR_TIME_CLOCK", "#882299", "color of the clock on any window/frame/etc.",),
	("PSGVAL_COLOR_TIME_ELAPSED", FMAXPSG_SCTN0900_STR_DEF, "COLOR_TIME_ELAPSED", "#447733", "color of the clock on any window/frame/etc.",),
	("PSGVAL_COLOR_TIME_TOGO", FMAXPSG_SCTN0900_STR_DEF, "COLOR_TIME_TOGO", "#AA6600", "color of the clock on any window/frame/etc.",),
	("PSGVAL_COLOR_WHITE", FMAXPSG_SCTN0900_STR_DEF, "WHITE", "#FFFFFF", "white",),
	("PSGVAL_EDIT_SZ_CLOCK_TOGO", FMAXPSG_SCTN0900_VAL_DEF, "EDIT_SZ_CLOCK_TOGO", "10", "size of the main togo clock on the clocks only floating widget",),
	("PSGVAL_EDIT_SZ_TIME_CLOCK", FMAXPSG_SCTN0900_VAL_DEF, "EDIT_SZ_TIME_CLOCK", "20", "size of the main clock on the clocks only floating widget",),
	("PSGVAL_EDIT_SZ_TIME_ELAPSED", FMAXPSG_SCTN0900_VAL_DEF, "EDIT_SZ_TIME_ELAPSED", "10", "size of the elapsed clock on the clocks only floating widget",),
	("PSGVAL_EMPTY_ALARM", FMAXPSG_SCTN0905_TUPDICT_DEF, "EMPTY_ALARM", "a normal alarm entry",),
	("PSGVAL_EMPTY_ALARM_DISMISSED", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "EMPTY_ALARM", "DISMISSED", "False", "bool is this event dismissed already",),
	("PSGVAL_EMPTY_ALARM_ENABLED", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "EMPTY_ALARM", "ENABLED", "True", "enabled state of this entry",),
	("PSGVAL_EMPTY_ALARM_EVENT_MODE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "EMPTY_ALARM", "EVENT_MODE", "MODE_ALARM", "set the mode to MODE_ALARM by default of course",),
	("PSGVAL_EMPTY_ALARM_NAME", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "EMPTY_ALARM", "NAME", "", "name of this entry",),
	("PSGVAL_EMPTY_ALARM_PREDISMISSABLE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "EMPTY_ALARM", "PREDISMISSABLE", "True", "pre-dismissable state of this entry",),
	("PSGVAL_EMPTY_ALARM_REMIND", FMAXPSG_SCTN0905_TUPDICT_DEF, "EMPTY_ALARM_REMIND", "a normal alarm entry",),
	("PSGVAL_EMPTY_ALARM_REMIND_DISMISSED", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "EMPTY_ALARM_REMIND", "DISMISSED", "False", "bool is this event dismissed already",),
	("PSGVAL_EMPTY_ALARM_REMIND_ENABLED", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "EMPTY_ALARM_REMIND", "ENABLED", "True", "enabled state of this entry",),
	("PSGVAL_EMPTY_ALARM_REMIND_EVENT_MODE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "EMPTY_ALARM_REMIND", "EVENT_MODE", "MODE_ALARMREMIND", "set the mode to MODE_ALARM by default of course",),
	("PSGVAL_EMPTY_ALARM_REMIND_NAME", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "EMPTY_ALARM_REMIND", "NAME", "", "name of this entry",),
	("PSGVAL_EMPTY_ALARM_REMIND_PREDISMISSABLE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "EMPTY_ALARM_REMIND", "PREDISMISSABLE", "True", "pre-dismissable state of this entry",),
	("PSGVAL_EMPTY_ALARM_REMIND_SNOOZABLE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "EMPTY_ALARM_REMIND", "SNOOZABLE", "False", "enabled state of this entry",),
	("PSGVAL_EMPTY_ALARM_REMIND_SNOOZED", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "EMPTY_ALARM_REMIND", "SNOOZED", "True", "enabled state of this entry",),
	("PSGVAL_EMPTY_ALARM_REMIND_TIME_ALARM", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "EMPTY_ALARM_REMIND", "TIME_ALARM", "00:00:00", "time this alarm is set for",),
	("PSGVAL_EMPTY_ALARM_REMIND_TIME_OF_NEXT_EVENT", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "EMPTY_ALARM_REMIND", "TIME_OF_NEXT_EVENT", "00:00:00", "post snooze or tomorrow",),
	("PSGVAL_EMPTY_ALARM_REMIND_TIME_REMIND", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "EMPTY_ALARM_REMIND", "TIME_REMIND", "00:00:00", "time this alarm is set for",),
	("PSGVAL_EMPTY_ALARM_REMIND_TIME_TOGO", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "EMPTY_ALARM_REMIND", "TIME_TOGO", "00:00:00", "post snooze or tomorrow",),
	("PSGVAL_EMPTY_ALARM_SNOOZABLE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "EMPTY_ALARM", "SNOOZABLE", "False", "enabled state of this entry",),
	("PSGVAL_EMPTY_ALARM_SNOOZED", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "EMPTY_ALARM", "SNOOZED", "True", "enabled state of this entry",),
	("PSGVAL_EMPTY_ALARM_TIME_ALARM", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "EMPTY_ALARM", "TIME_ALARM", "00:00:00", "time this alarm is set for",),
	("PSGVAL_EMPTY_ALARM_TIME_OF_NEXT_EVENT", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "EMPTY_ALARM", "TIME_OF_NEXT_EVENT", "00:00:00", "post snooze or tomorrow",),
	("PSGVAL_EMPTY_ALARM_TIME_TOGO", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "EMPTY_ALARM", "TIME_TOGO", "00:00:00", "post snooze or tomorrow",),
	("PSGVAL_EMPTY_CLOCKS", FMAXPSG_SCTN0905_TUPDICT_DEF, "EMPTY_CLOCKS", "just the clocks window",),
	("PSGVAL_EMPTY_CLOCKS_TIME_CLOCK", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "EMPTY_CLOCKS", "TIME_CLOCK", "00:00:00", "the main clock time",),
	("PSGVAL_EMPTY_CLOCKS_TIME_ELAPSED", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "EMPTY_CLOCKS", "TIME_ELAPSED", "00:00:00", "the main elapsed time",),
	("PSGVAL_EMPTY_CLOCKS_TIME_OF_NEXT_EVENT", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "EMPTY_CLOCKS", "TIME_OF_NEXT_EVENT", "00:00:00", "the main count down to the next event time",),
	("PSGVAL_EMPTY_INTERVAL", FMAXPSG_SCTN0905_TUPDICT_DEF, "EMPTY_INTERVAL", "a normal alarm entry",),
	("PSGVAL_EMPTY_INTERVAL_ENABLED", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "EMPTY_INTERVAL", "ENABLED", "True", "enabled state of this entry",),
	("PSGVAL_EMPTY_INTERVAL_EVENT_MODE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "EMPTY_INTERVAL", "EVENT_MODE", "MODE_INTERVAL", "set the mode to MODE_ALARM by default of course",),
	("PSGVAL_EMPTY_INTERVAL_NAME", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "EMPTY_INTERVAL", "NAME", "", "name of this entry",),
	("PSGVAL_EMPTY_INTERVAL_RUNNING", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "EMPTY_INTERVAL", "RUNNING", "True", "running state of this entry",),
	("PSGVAL_EMPTY_INTERVAL_TIME_INTERVAL", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "EMPTY_INTERVAL", "TIME_INTERVAL", "00:00:00", "time this alarm is set for",),
	("PSGVAL_EMPTY_INTERVAL_TIME_OF_NEXT_EVENT", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "EMPTY_INTERVAL", "TIME_OF_NEXT_EVENT", "00:00:00", "post snooze or tomorrow",),
	("PSGVAL_EMPTY_INTERVAL_TIME_TOGO", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "EMPTY_INTERVAL", "TIME_TOGO", "00:00:00", "post snooze or tomorrow",),
	("PSGVAL_FONT_DEFAULT", FMAXPSG_SCTN0900_STR_DEF, "FONT_DEFAULT", "Source Code Pro", "set the main font",),
	("PSGVAL_FULL_BUTTON", FMAXPSG_SCTN0905_TUPDICT_DEF, "FULL_BUTTON", "define the button empty tupdict",),
	("PSGVAL_FULL_BUTTON_AUTO_SIZE_BUTTON", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "AUTO_SIZE_BUTTON", "None", "if True the button size is sized to fit the text",),
	("PSGVAL_FULL_BUTTON_BIND_RETURN_KEY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "BIND_RETURN_KEY", "False", "If True the return key will cause this button to be pressed",),
	("PSGVAL_FULL_BUTTON_BORDER_WIDTH", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "BORDER_WIDTH", "None", "width of border around button in pixels",),
	("PSGVAL_FULL_BUTTON_BUTTON_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "BUTTON_COLOR", "None", "Color of button. default is from theme or the window. Easy to remember which is which if you say 'ON' between colors. 'red' on 'green'. Normally a tuple, but can be a simplified-button-color-string 'foreground on background'. Can be a single color if want to set only the background.",),
	("PSGVAL_FULL_BUTTON_BUTTON_TEXT", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "FULL_BUTTON", "BUTTON_TEXT", "", "str text to display on the button",),
	("PSGVAL_FULL_BUTTON_BUTTON_TYPE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "BUTTON_TYPE", "7", "You  should NOT be setting this directly. ONLY the shortcut functions set this",),
	("PSGVAL_FULL_BUTTON_CHANGE_SUBMITS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "CHANGE_SUBMITS", "False", "DO NOT USE. Only listed for backwards compat - Use enable_events instead",),
	("PSGVAL_FULL_BUTTON_DEFAULT_EXTENSION", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "FULL_BUTTON", "DEFAULT_EXTENSION", "", "If no extension entered by user, add this to filename (only used in saveas dialogs)",),
	("PSGVAL_FULL_BUTTON_DISABLED", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "DISABLED", "False", "If True button will be created disabled. If FULL_BUTTON_DISABLED_MEANS_IGNORE then the button will be ignored rather than disabled using tkinter",),
	("PSGVAL_FULL_BUTTON_DISABLED_BUTTON_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "DISABLED_BUTTON_COLOR", "None", "colors to use when button is disabled (text, background). Use None for a color if don't want to change. Only ttk buttons support both text and background colors. tk buttons only support changing text color",),
	("PSGVAL_FULL_BUTTON_ENABLE_EVENTS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "ENABLE_EVENTS", "False", "Turns on the element specific events. If this button is a target, should it generate an event when filled in",),
	("PSGVAL_FULL_BUTTON_FILE_TYPES", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "FILE_TYPES", "(('ALL FILES', '*.*'),)", "the filetypes that will be used to match files. To indicate all files: (('ALL Files', '*.*'),).  Note - NOT SUPPORTED ON MAC",),
	("PSGVAL_FULL_BUTTON_FOCUS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "FOCUS", "False", "if True, initial focus will be put on this button",),
	("PSGVAL_FULL_BUTTON_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "FONT", "None", "specifies the font family, size, etc",),
	("PSGVAL_FULL_BUTTON_HIGHLIGHT_COLORS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "HIGHLIGHT_COLORS", "None", "colors to use when button has focus (highlight, background). None will use computed colors. Only used by Linux and only for non-TTK button",),
	("PSGVAL_FULL_BUTTON_IMAGE_DATA", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "IMAGE_DATA", "None", "Raw or Base64 representation of the image to put on button. Choose either filename or data",),
	("PSGVAL_FULL_BUTTON_IMAGE_FILENAME", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "IMAGE_FILENAME", "None", "image filename if there is a button image. GIFs and PNGs only.",),
	("PSGVAL_FULL_BUTTON_IMAGE_SIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "IMAGE_SIZE", "(None, None)", "Size of the image in pixels (width, height)",),
	("PSGVAL_FULL_BUTTON_IMAGE_SUBSAMPLE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "IMAGE_SUBSAMPLE", "None", "amount to reduce the size of the image. Divides the size by this number. 2=1/2, 3=1/3, 4=1/4, etc",),
	("PSGVAL_FULL_BUTTON_INITIAL_FOLDER", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "INITIAL_FOLDER", "None", "starting path for folders and files",),
	("PSGVAL_FULL_BUTTON_K", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "K", "None", "Used with window.FindElement and with return values to uniquely identify this element to uniquely identify this element",),
	("PSGVAL_FULL_BUTTON_KEY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "KEY", "None", "Used with window.FindElement and with return values to uniquely identify this element to uniquely identify this element",),
	("PSGVAL_FULL_BUTTON_METADATA", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "METADATA", "None", "User metadata that can be set to ANYTHING",),
	("PSGVAL_FULL_BUTTON_PAD", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "PAD", "None", "Amount of padding to put around element (left/right, top/bottom) or ((left, right), (top, bottom))",),
	("PSGVAL_FULL_BUTTON_RIGHT_CLICK_MENU", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "RIGHT_CLICK_MENU", "None", "A list of lists of Menu items to show when this element is right clicked. See user docs for exact format.",),
	("PSGVAL_FULL_BUTTON_S", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "S", "(None, None)", "(width, height) of the button in characters wide, rows high",),
	("PSGVAL_FULL_BUTTON_SIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "SIZE", "(None, None)", "(width, height) of the button in characters wide, rows high",),
	("PSGVAL_FULL_BUTTON_TARGET", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "TARGET", "(None, None)", "str | Tuple[int, int] key or (row,col) target for the button. Note that -1 for column means 1 element to the left of this one. The constant ThisRow is used to indicate the current row. The Button itself is a valid target for some types of button",),
	("PSGVAL_FULL_BUTTON_TOOLTIP", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "TOOLTIP", "None", "text, that will appear when mouse hovers over the element",),
	("PSGVAL_FULL_BUTTON_USE_TTK_BUTTONS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "USE_TTK_BUTTONS", "None", "True = use ttk buttons. False = do not use ttk buttons.  None (Default) = use ttk buttons only if on a Mac and not with button images",),
	("PSGVAL_FULL_BUTTON_VISIBLE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_BUTTON", "VISIBLE", "True", "set visibility state of the element",),
	("PSGVAL_FULL_CHECKBOX", FMAXPSG_SCTN0905_TUPDICT_DEF, "FULL_CHECKBOX", "set a checkbox in motion",),
	("PSGVAL_FULL_CHECKBOX_AUTO_SIZE_TEXT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_CHECKBOX", "AUTO_SIZE_TEXT", "None", "if True will size the element to match the length of the text",),
	("PSGVAL_FULL_CHECKBOX_BACKGROUND_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_CHECKBOX", "BACKGROUND_COLOR", "None", "color of background",),
	("PSGVAL_FULL_CHECKBOX_CHANGE_SUBMITS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_CHECKBOX", "CHANGE_SUBMITS", "False", "DO NOT USE. Only listed for backwards compat - Use enable_events instead",),
	("PSGVAL_FULL_CHECKBOX_CHECKBOX_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_CHECKBOX", "CHECKBOX_COLOR", "None", "color of background of the box that has the check mark in it. The checkmark is the same color as the text",),
	("PSGVAL_FULL_CHECKBOX_DEFAULT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_CHECKBOX", "DEFAULT", "False", "Set to True if you want this checkbox initially checked",),
	("PSGVAL_FULL_CHECKBOX_DISABLED", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_CHECKBOX", "DISABLED", "False", "set disable state",),
	("PSGVAL_FULL_CHECKBOX_ENABLE_EVENTS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_CHECKBOX", "ENABLE_EVENTS", "False", "Turns on the element specific events. Checkbox events happen when an item changes",),
	("PSGVAL_FULL_CHECKBOX_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_CHECKBOX", "FONT", "None", "specifies the font family, size, etc",),
	("PSGVAL_FULL_CHECKBOX_K", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_CHECKBOX", "K", "None", "Used with window.FindElement and with return values to uniquely identify this element",),
	("PSGVAL_FULL_CHECKBOX_KEY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_CHECKBOX", "KEY", "None", "Used with window.FindElement and with return values to uniquely identify this element",),
	("PSGVAL_FULL_CHECKBOX_METADATA", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_CHECKBOX", "METADATA", "None", "User metadata that can be set to ANYTHING",),
	("PSGVAL_FULL_CHECKBOX_PAD", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_CHECKBOX", "PAD", "None", "Amount of padding to put around element (left/right, top/bottom) or ((left, right), (top, bottom))",),
	("PSGVAL_FULL_CHECKBOX_S", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_CHECKBOX", "S", "(None, None)", "(width, height) width = characters-wide, height = rows-high",),
	("PSGVAL_FULL_CHECKBOX_SIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_CHECKBOX", "SIZE", "(None, None)", "(width, height) width = characters-wide, height = rows-high",),
	("PSGVAL_FULL_CHECKBOX_TEXT", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "FULL_CHECKBOX", "TEXT", "", "Text to display next to checkbox",),
	("PSGVAL_FULL_CHECKBOX_TEXT_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_CHECKBOX", "TEXT_COLOR", "None", "color of the text",),
	("PSGVAL_FULL_CHECKBOX_TOOLTIP", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_CHECKBOX", "TOOLTIP", "None", "that will appear when mouse hovers over the element",),
	("PSGVAL_FULL_CHECKBOX_VISIBLE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_CHECKBOX", "VISIBLE", "True", "set visibility state of the element",),
	("PSGVAL_FULL_COLUMN", FMAXPSG_SCTN0905_TUPDICT_DEF, "FULL_COLUMN", "full column entry",),
	("PSGVAL_FULL_COLUMN_BACKGROUND_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "BACKGROUND_COLOR", "None", "color of background of entire Column",),
	("PSGVAL_FULL_COLUMN_ELEMENT_JUSTIFICATION", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "ELEMENT_JUSTIFICATION", "None", "All elements inside the Column will have this justification 'left', 'right', 'center' are valid values",),
	("PSGVAL_FULL_COLUMN_EXPAND_X", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "EXPAND_X", "None", "If True the column will automatically expand in the X direction to fill available space",),
	("PSGVAL_FULL_COLUMN_EXPAND_Y", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "EXPAND_Y", "None", "If True the column will automatically expand in the X direction to fill available space",),
	("PSGVAL_FULL_COLUMN_GRAB", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "GRAB", "None", "If True can grab this element and move the window around. Default is False",),
	("PSGVAL_FULL_COLUMN_JUSTIFICATION", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "JUSTIFICATION", "None", "set justification for the Column itself. Note entire row containing the Column will be affected",),
	("PSGVAL_FULL_COLUMN_K", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "K", "None", "Value that uniquely identifies this element from all other elements. Used when Finding an element or in return values. Must be unique to the window",),
	("PSGVAL_FULL_COLUMN_KEY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "KEY", "None", "Value that uniquely identifies this element from all other elements. Used when Finding an element or in return values. Must be unique to the window",),
	("PSGVAL_FULL_COLUMN_LAYOUT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "LAYOUT", "[]", "Layout that will be shown in the Column container",),
	("PSGVAL_FULL_COLUMN_METADATA", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "METADATA", "None", "User metadata that can be set to ANYTHING",),
	("PSGVAL_FULL_COLUMN_PAD", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "PAD", "None", "Amount of padding to put around element (left/right, top/bottom) or ((left, right), (top, bottom))",),
	("PSGVAL_FULL_COLUMN_RIGHT_CLICK_MENU", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "RIGHT_CLICK_MENU", "None", "A list of lists of Menu items to show when this element is right clicked. See user docs for exact format.",),
	("PSGVAL_FULL_COLUMN_S", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "S", "(None, None)", "(width, height) size in pixels (doesn't work quite right, sometimes only 1 dimension is set by tkinter",),
	("PSGVAL_FULL_COLUMN_SCROLLABLE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "SCROLLABLE", "False", "if True then scrollbars will be added to the column",),
	("PSGVAL_FULL_COLUMN_SIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "SIZE", "(None, None)", "(width, height) size in pixels (doesn't work quite right, sometimes only 1 dimension is set by tkinter",),
	("PSGVAL_FULL_COLUMN_VERTACLE_SCROLL_ONLY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "VERTICAL_SCROLL_ONLY", "False", "if Truen then no horizontal scrollbar will be shown",),
	("PSGVAL_FULL_COLUMN_VERTICAL_ALIGNMENT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "VERTICAL_ALIGNMENT", "None", "Place the column at the 'top', 'center', 'bottom' of the row (can also use t,c,r). Defaults to no setting (tkinter decides)",),
	("PSGVAL_FULL_COLUMN_VISIBLE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COLUMN", "VISIBLE", "True", "set visibility state of the element",),
	("PSGVAL_FULL_COMBO", FMAXPSG_SCTN0905_TUPDICT_DEF, "FULL_COMBO", "a full combo tupdict",),
	("PSGVAL_FULL_COMBO_AUTO_SIZE_TEXT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "AUTO_SIZE_TEXT", "None", "True if element should be the same size as the contents",),
	("PSGVAL_FULL_COMBO_BACKGROUND_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "BACKGROUND_COLOR", "None", "color of background",),
	("PSGVAL_FULL_COMBO_CHANGE_SUBMITS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "CHANGE_SUBMITS", "False", "DEPRICATED DO NOT USE. Use `enable_events` instead",),
	("PSGVAL_FULL_COMBO_DEFAULT_VALUE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "DEFAULT_VALUE", "None", "Choice to be displayed as initial value. Must match one of values variable contents",),
	("PSGVAL_FULL_COMBO_DISABLED", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "DISABLED", "False", "set disable state for element",),
	("PSGVAL_FULL_COMBO_ENABLE_EVENTS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "ENABLE_EVENTS", "False", "",),
	("PSGVAL_FULL_COMBO_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "FONT", "None", "specifies the font family, size, etc",),
	("PSGVAL_FULL_COMBO_K", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "K", "None", "Used with window.FindElement and with return values to uniquely identify this element",),
	("PSGVAL_FULL_COMBO_KEY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "KEY", "None", "Used with window.FindElement and with return values to uniquely identify this element",),
	("PSGVAL_FULL_COMBO_METADATA", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "METADATA", "None", "User metadata that can be set to ANYTHING",),
	("PSGVAL_FULL_COMBO_PAD", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "PAD", "None", "Amount of padding to put around element (left/right, top/bottom) or ((left, right), (top, bottom))",),
	("PSGVAL_FULL_COMBO_READONLY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "READONLY", "False", "make element readonly (user can't change). True means user cannot change",),
	("PSGVAL_FULL_COMBO_S", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "S", "(None, None)", "width, height. Width = characters-wide, height = NOTE it's the number of entries to show in the list",),
	("PSGVAL_FULL_COMBO_SIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "SIZE", "(None, None)", "width, height. Width = characters-wide, height = NOTE it's the number of entries to show in the list",),
	("PSGVAL_FULL_COMBO_TEXT_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "TEXT_COLOR", "None", "color of the text",),
	("PSGVAL_FULL_COMBO_TOOLTIP", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "TOOLTIP", "None", "text that will appear when mouse hovers over this element",),
	("PSGVAL_FULL_COMBO_VALUES", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "VALUES", "[]", "values to choose. While displayed as text, the items returned are what the caller supplied, not text",),
	("PSGVAL_FULL_COMBO_VISIBLE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_COMBO", "VISIBLE", "True", "set visibility state of the element",),
	("PSGVAL_FULL_RADIO", FMAXPSG_SCTN0905_TUPDICT_DEF, "FULL_RADIO", "define a full radio button entity",),
	("PSGVAL_FULL_RADIO_AUTO_SIZE_TEXT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_RADIO", "AUTO_SIZE_TEXT", "None,", "",),
	("PSGVAL_FULL_RADIO_BACKGROUND_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_RADIO", "BACKGROUND_COLOR", "None,", "",),
	("PSGVAL_FULL_RADIO_CHANGE_SUBMITS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_RADIO", "CHANGE_SUBMITS", "False,", "",),
	("PSGVAL_FULL_RADIO_CIRCLE_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_RADIO", "CIRCLE_COLOR", "None,", "",),
	("PSGVAL_FULL_RADIO_DEFAULT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_RADIO", "DEFAULT", "False,", "",),
	("PSGVAL_FULL_RADIO_DISABLED", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_RADIO", "DISABLED", "False,", "",),
	("PSGVAL_FULL_RADIO_ENABLE_EVENTS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_RADIO", "ENABLE_EVENTS", "False,", "",),
	("PSGVAL_FULL_RADIO_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_RADIO", "FONT", "None,", "",),
	("PSGVAL_FULL_RADIO_GROUP_ID", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "FULL_RADIO", "GROUP_ID", "", "Groups together multiple Radio Buttons. Any type works",),
	("PSGVAL_FULL_RADIO_K", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_RADIO", "K", "None,", "",),
	("PSGVAL_FULL_RADIO_KEY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_RADIO", "KEY", "None,", "",),
	("PSGVAL_FULL_RADIO_METADATA", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_RADIO", "METADATA", "None", "",),
	("PSGVAL_FULL_RADIO_PAD", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_RADIO", "PAD", "None,", "",),
	("PSGVAL_FULL_RADIO_S", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_RADIO", "S", "(None, None),", "",),
	("PSGVAL_FULL_RADIO_SIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_RADIO", "SIZE", "(None, None),", "",),
	("PSGVAL_FULL_RADIO_TEXT", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "FULL_RADIO", "TEXT", "", "",),
	("PSGVAL_FULL_RADIO_TEXT_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_RADIO", "TEXT_COLOR", "None,", "",),
	("PSGVAL_FULL_RADIO_TOOLTIP", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_RADIO", "TOOLTIP", "None,", "",),
	("PSGVAL_FULL_RADIO_VISIBLE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_RADIO", "VISIBLE", "True,", "",),
	("PSGVAL_FULL_SPIN", FMAXPSG_SCTN0905_TUPDICT_DEF, "FULL_SPIN", "full spin dict",),
	("PSGVAL_FULL_SPIN_AUTO_SIZE_TEXT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "AUTO_SIZE_TEXT", "None", "if True will size the element to match the length of the text",),
	("PSGVAL_FULL_SPIN_BACKGROUND_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "BACKGROUND_COLOR", "None", "color of background",),
	("PSGVAL_FULL_SPIN_CHANGE_SUBMITS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "CHANGE_SUBMITS", "False", "DO NOT USE. Only listed for backwards compat - Use enable_events instead",),
	("PSGVAL_FULL_SPIN_DISABLED", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "DISABLED", "False", "set disable state",),
	("PSGVAL_FULL_SPIN_ENABLE_EVENTS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "ENABLE_EVENTS", "False", "Turns on the element specific events. Spin events happen when an item changes",),
	("PSGVAL_FULL_SPIN_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "FONT", "None", "specifies the font family, size, etc",),
	("PSGVAL_FULL_SPIN_INITIAL_VALUE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "INITIAL_VALUE", "None", "Initial item to show in window. Choose from list of values supplied",),
	("PSGVAL_FULL_SPIN_K", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "K", "None", "Used with window.FindElement and with return values to uniquely identify this element",),
	("PSGVAL_FULL_SPIN_KEY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "KEY", "None", "Used with window.FindElement and with return values to uniquely identify this element",),
	("PSGVAL_FULL_SPIN_METADATA", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "METADATA", "None", "User metadata that can be set to ANYTHING",),
	("PSGVAL_FULL_SPIN_PAD", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "PAD", "None", "Amount of padding to put around element (left/right, top/bottom) or ((left, right), (top, bottom))",),
	("PSGVAL_FULL_SPIN_READONLY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "READONLY", "False", "readonly bool",),
	("PSGVAL_FULL_SPIN_S", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "S", "(None, None)", "(width, height) width = characters-wide, height = rows-high",),
	("PSGVAL_FULL_SPIN_SIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "SIZE", "(None, None)", "(width, height) width = characters-wide, height = rows-high",),
	("PSGVAL_FULL_SPIN_TEXT_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "TEXT_COLOR", "None", "color of the text",),
	("PSGVAL_FULL_SPIN_TOOLTIP", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "TOOLTIP", "None", "text, that will appear when mouse hovers over the element",),
	("PSGVAL_FULL_SPIN_VALUES", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "VALUES", "[]", "List of valid values",),
	("PSGVAL_FULL_SPIN_VISIBLE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_SPIN", "VISIBLE", "True", "set visibility state of the element",),
	("PSGVAL_FULL_TEXT", FMAXPSG_SCTN0905_TUPDICT_DEF, "FULL_TEXT", "the full monty for text elements",),
	("PSGVAL_FULL_TEXT_AUTO_SIZE_TEXT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "AUTO_SIZE_TEXT", "None", "if True size of the Text Element will be sized to fit the string provided in 'text' parm",),
	("PSGVAL_FULL_TEXT_BACKGROUND_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "BACKGROUND_COLOR", "None", "color of background",),
	("PSGVAL_FULL_TEXT_BORDER_WIDTH", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "BORDER_WIDTH", "None", "number of pixels for the border (if using a relief)",),
	("PSGVAL_FULL_TEXT_CLICK_SUBMITS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "CLICK_SUBMITS", "False", "DO NOT USE. Only listed for backwards compat - Use enable_events instead",),
	("PSGVAL_FULL_TEXT_ENABLE_EVENTS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "ENABLE_EVENTS", "False", "Turns on the element specific events. Text events happen when the text is clicked",),
	("PSGVAL_FULL_TEXT_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "FONT", "None", "specifies the font family, size, etc",),
	("PSGVAL_FULL_TEXT_GRAB", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "GRAB", "None", "If True can grab this element and move the window around. Default is False",),
	("PSGVAL_FULL_TEXT_JUSTIFICATION", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "JUSTIFICATION", "None", "how string should be aligned within space provided by size. Valid choices = `left`, `right`, `center`",),
	("PSGVAL_FULL_TEXT_K", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "K", "None", "Same as the Key. You can use either k or key. Which ever is set will be used.",),
	("PSGVAL_FULL_TEXT_KEY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "KEY", "None", "Used with window.FindElement and with return values to uniquely identify this element to uniquely identify this element",),
	("PSGVAL_FULL_TEXT_METADATA", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "METADATA", "None", "User metadata that can be set to ANYTHING",),
	("PSGVAL_FULL_TEXT_PAD", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "PAD", "None", "Amount of padding to put around element (left/right, top/bottom) or ((left, right), (top, bottom))",),
	("PSGVAL_FULL_TEXT_RELIEF", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "RELIEF", "None", "relief style around the text. Values are same as progress meter relief values. Should be a constant that is defined at starting with 'RELIEF_' - `RELIEF_RAISED, RELIEF_SUNKEN, RELIEF_FLAT, RELIEF_RIDGE, RELIEF_GROOVE, RELIEF_SOLID`",),
	("PSGVAL_FULL_TEXT_RIGHT_CLICK_MENU", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "RIGHT_CLICK_MENU", "None", "A list of lists of Menu items to show when this element is right clicked. See user docs for exact format.",),
	("PSGVAL_FULL_TEXT_S", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "S", "(None, None)", "Same as size parameter.  It's an alias. If EITHER of them are set, then the one that's set will be used. If BOTH are set, size will be used",),
	("PSGVAL_FULL_TEXT_SIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "SIZE", "(None, None)", "(width, height) width = characters-wide, height = rows-high",),
	("PSGVAL_FULL_TEXT_TEXT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "TEXT", "", "The text to display. Can include /n to achieve multiple lines.  Will convert (optional) parameter into a string",),
	("PSGVAL_FULL_TEXT_TEXT_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "TEXT_COLOR", "None", "color of the text",),
	("PSGVAL_FULL_TEXT_TOOLTIP", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "TOOLTIP", "None", "text, that will appear when mouse hovers over the element",),
	("PSGVAL_FULL_TEXT_VISIBLE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_TEXT", "VISIBLE", "True", "set visibility state of the element",),
	("PSGVAL_FULL_WINDOW", FMAXPSG_SCTN0905_TUPDICT_DEF, "FULL_WINDOW", "define the FULL_WINDOW tupdict",),
	("PSGVAL_FULL_WINDOW_ALPHA_CHANNEL", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "ALPHA_CHANNEL", "1", "Sets the opacity of the window. 0 = invisible 1 = completely visible. Values bewteen 0 & 1 will produce semi-transparent windows in SOME environments (The Raspberry Pi always has this value at 1 and cannot change.",),
	("PSGVAL_FULL_WINDOW_AUTO_CLOSE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "AUTO_CLOSE", "False", "If True, the window will automatically close itself",),
	("PSGVAL_FULL_WINDOW_AUTO_CLOSE_DURATION", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "AUTO_CLOSE_DURATION", "3", "Number of seconds to wait before closing the window",),
	("PSGVAL_FULL_WINDOW_AUTO_SIZE_BUTTONS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "AUTO_SIZE_BUTTONS", "None", "True if Buttons in this Window should be sized to exactly fit the text on this.",),
	("PSGVAL_FULL_WINDOW_AUTO_SIZE_TEXT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "AUTO_SIZE_TEXT", "None", "True if Elements in Window should be sized to exactly fir the length of text",),
	("PSGVAL_FULL_WINDOW_BACKGROUND_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "BACKGROUND_COLOR", "None", "color of background",),
	("PSGVAL_FULL_WINDOW_BORDER_DEPTH", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "BORDER_DEPTH", "None", "Default border depth (width) for all elements in the window",),
	("PSGVAL_FULL_WINDOW_BUTTON_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "BUTTON_COLOR", "None", "Default button colors for all buttons in the window",),
	("PSGVAL_FULL_WINDOW_DEBUGGER_ENABLED", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "DEBUGGER_ENABLED", "True", "Default border depth (width) for all elements in the window",),
	("PSGVAL_FULL_WINDOW_DEFAULT_BUTTON_ELEMENT_SIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "DEFAULT_BUTTON_ELEMENT_SIZE", "(None, None)", "(width, height) size in characters (wide) and rows (high) for all Button elements in this window",),
	("PSGVAL_FULL_WINDOW_DEFAULT_ELEMENT_SIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "DEFAULT_ELEMENT_SIZE", "(45, 1)", "size in characters (wide) and rows (high) for all elements in this window",),
	("PSGVAL_FULL_WINDOW_DISABLE_CLOSE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "DISABLE_CLOSE", "False", "If True, the X button in the top right corner of the window will no work.  Use with caution and always give a way out toyour users",),
	("PSGVAL_FULL_WINDOW_DISABLE_MINIMIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "DISABLE_MINIMIZE", "False", "if True the user won't be able to minimize window.  Good for taking over entire screen and staying that way.",),
	("PSGVAL_FULL_WINDOW_ELEMENT_JUSTIFICATION", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "FULL_WINDOW", "ELEMENT_JUSTIFICATION", "left", "All elements in the Window itself will have this justification 'left', 'right', 'center' are valid values",),
	("PSGVAL_FULL_WINDOW_ELEMENT_PADDING", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "ELEMENT_PADDING", "None", "Default amount of padding to put around elements in window (left/right, top/bottom) or ((left, right), (top, bottom))",),
	("PSGVAL_FULL_WINDOW_ENABLE_CLOSE_ATTEMPTED_EVENT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "ENABLE_CLOSE_ATTEMPTED_EVENT", "False", "If True then the window will not close when 'X' clicked. Instead an event FULL_WINDOW_CLOSE_ATTEMPTED_EVENT if returned from window.read",),
	("PSGVAL_FULL_WINDOW_FINALIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "FINALIZE", "False", "If True then the Finalize method will be called. Use this rather than chaining .Finalize for cleaner code",),
	("PSGVAL_FULL_WINDOW_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "FONT", "None", "specifies the font family, size, etc",),
	("PSGVAL_FULL_WINDOW_FORCE_TOPLEVEL", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "FORCE_TOPLEVEL", "False", "If True will cause this window to skip the normal use of a hidden master window",),
	("PSGVAL_FULL_WINDOW_GRAB_ANYWHERE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "GRAB_ANYWHERE", "False", "If True can use mouse to click and drag to move the window. Almost every location of the window will work except input fields on some systems",),
	("PSGVAL_FULL_WINDOW_ICON", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "ICON", "None", "Can be either a filename or Base64 value. For Windows if filename, it MUST be ICO format. For Linux, must NOT be ICO",),
	("PSGVAL_FULL_WINDOW_KEEP_ON_TOP", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "KEEP_ON_TOP", "False", "If True, window will be created on top of all other windows on screen. It can be bumped down if another window created with this parm",),
	("PSGVAL_FULL_WINDOW_LAYOUT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "LAYOUT", "None", "The layout for the window. Can also be specified in the Layout method",),
	("PSGVAL_FULL_WINDOW_LOCATION", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "LOCATION", "(None, None)", "(x,y) location, in pixels, to locate the upper left corner of the window on the screen. Default is to center on screen.",),
	("PSGVAL_FULL_WINDOW_MARGINS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "MARGINS", "(None, None)", "(left/right, top/bottom) Amount of pixels to leave inside the window's frame around the edges before your elements are shown.",),
	("PSGVAL_FULL_WINDOW_METADATA", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "METADATA", "None", "User metadata that can be set to ANYTHING",),
	("PSGVAL_FULL_WINDOW_MODAL", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "MODAL", "False", "If True then this window will be the only window a user can interact with until it is closed",),
	("PSGVAL_FULL_WINDOW_NO_TITLEBAR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "NO_TITLEBAR", "False", "If true, no titlebar nor frame will be shown on window. This means you cannot minimize the window and it will not show up on the taskbar",),
	("PSGVAL_FULL_WINDOW_PROGRESS_BAR_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "PROGRESS_BAR_COLOR", "(None, None)", "(bar color, background color) Sets the default colors for all progress bars in the window",),
	("PSGVAL_FULL_WINDOW_RESIZABLE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "RESIZABLE", "False", "If True, allows the user to resize the window. Note the not all Elements will change size or location when resizing.",),
	("PSGVAL_FULL_WINDOW_RETURN_KEYBOARD_EVENTS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "RETURN_KEYBOARD_EVENTS", "False", "if True key presses on the keyboard will be returned as Events from Read calls",),
	("PSGVAL_FULL_WINDOW_RIGHT_CLICK_MENU", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "RIGHT_CLICK_MENU", "None", "A list of lists of Menu items to show when this element is right clicked. See user docs for exact format.",),
	("PSGVAL_FULL_WINDOW_RIGHT_CLICK_MENU_BACKGROUND_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "RIGHT_CLICK_MENU_BACKGROUND_COLOR", "None", "Background color for right click menus",),
	("PSGVAL_FULL_WINDOW_RIGHT_CLICK_MENU_DISABLED_TEXT_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "RIGHT_CLICK_MENU_DISABLED_TEXT_COLOR", "None", "Text color for disabled right click menu items",),
	("PSGVAL_FULL_WINDOW_RIGHT_CLICK_MENU_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "RIGHT_CLICK_MENU_FONT", "None", "Font for right click menus",),
	("PSGVAL_FULL_WINDOW_RIGHT_CLICK_MENU_SELECTED_COLORS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "RIGHT_CLICK_MENU_SELECTED_COLORS", "(None, None)", "Text AND background colors for a selected item. Can be a Tuple OR a color string. simplified-button-color-string 'foreground on background'. Can be a single color if want to set only the background.",),
	("PSGVAL_FULL_WINDOW_RIGHT_CLICK_MENU_TEAROFF", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "RIGHT_CLICK_MENU_TEAROFF", "False", "If True then all right click menus can be torn off",),
	("PSGVAL_FULL_WINDOW_RIGHT_CLICK_MENU_TEXT_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "RIGHT_CLICK_MENU_TEXT_COLOR", "None", "Text color for right click menus",),
	("PSGVAL_FULL_WINDOW_SIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "SIZE", "(None, None)", "(width, height) size in pixels for this window. Normally the window is autosized to fit contents, not set to an absolute size by the user",),
	("PSGVAL_FULL_WINDOW_TEXT_JUSTIFICATION", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "TEXT_JUSTIFICATION", "None", "Default text justification for all Text Elements in window",),
	("PSGVAL_FULL_WINDOW_TITLE", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "FULL_WINDOW", "TITLE", "", "The title that will be displayed in the Titlebar and on the Taskbar",),
	("PSGVAL_FULL_WINDOW_TITLEBAR_BACKGROUND_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "TITLEBAR_BACKGROUND_COLOR", "None", "If custom titlebar indicated by use_custom_titlebar, then use this as background color",),
	("PSGVAL_FULL_WINDOW_TITLEBAR_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "TITLEBAR_FONT", "None", "If custom titlebar indicated by use_custom_titlebar, then use this as title font",),
	("PSGVAL_FULL_WINDOW_TITLEBAR_ICON", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "TITLEBAR_ICON", "None", "If custom titlebar indicated by use_custom_titlebar, then use this as the icon (file or base64 bytes)",),
	("PSGVAL_FULL_WINDOW_TITLEBAR_TEXT_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "TITLEBAR_TEXT_COLOR", "None", "If custom titlebar indicated by use_custom_titlebar, then use this as text color",),
	("PSGVAL_FULL_WINDOW_TRANSPARENT_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "TRANSPARENT_COLOR", "None", "Any portion of the window that has this color will be completely transparent. You can even click through these spots to the window under this window.",),
	("PSGVAL_FULL_WINDOW_TTK_THEME", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "TTK_THEME", "None", "Set the tkinter ttk 'theme' of the window.  Default = DEFAULT_TTK_THEME.  Sets all ttk widgets to this theme as their default",),
	("PSGVAL_FULL_WINDOW_USE_CUSTOM_TITLEBAR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "USE_CUSTOM_TITLEBAR", "None", "If True, then a custom titlebar will be used instead of the normal titlebar",),
	("PSGVAL_FULL_WINDOW_USE_DEFAULT_FOCUS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "USE_DEFAULT_FOCUS", "True", "If True will use the default focus algorithm to set the focus to the 'Correct' element",),
	("PSGVAL_FULL_WINDOW_USE_TTK_BUTTONS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "FULL_WINDOW", "USE_TTK_BUTTONS", "None", "Affects all buttons in window. True = use ttk buttons. False = do not use ttk buttons.  None = use ttk buttons only if on a Mac",),
	("PSGVAL_JUSTIFICATION_CENTER", FMAXPSG_SCTN0900_STR_DEF, "JUSTIFICATION_CENTER", "center", "comment",),
	("PSGVAL_JUSTIFICATION_LEFT", FMAXPSG_SCTN0900_STR_DEF, "JUSTIFICATION_LEFT", "left", "comment",),
	("PSGVAL_JUSTIFICATION_RIGHT", FMAXPSG_SCTN0900_STR_DEF, "JUSTIFICATION_RIGHT", "right", "comment",),
	("PSGVAL_MAIN_SZ_TIME_CLOCK", FMAXPSG_SCTN0900_VAL_DEF, "MAIN_SZ_TIME_CLOCK", "60", "size of the main clock on the clocks only floating widget",),
	("PSGVAL_MAIN_SZ_TIME_ELAPSED", FMAXPSG_SCTN0900_VAL_DEF, "MAIN_SZ_TIME_ELAPSED", "30", "size of the elapsed clock on the clocks only floating widget",),
	("PSGVAL_MAIN_SZ_TIME_TOGO", FMAXPSG_SCTN0900_VAL_DEF, "MAIN_SZ_TIME_TOGO", "30", "size of the main togo clock on the clocks only floating widget",),
	("PSGVAL_NORMAL_BUTTON", FMAXPSG_SCTN0905_TUPDICT_DEF, "NORMAL_BUTTON", "define the button empty tupdict",),
	("PSGVAL_NORMAL_BUTTON_BUTTON_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_BUTTON", "BUTTON_COLOR", "None", "Color of button. default is from theme or the window. Easy to remember which is which if you say 'ON' between colors. 'red' on 'green'. Normally a tuple, but can be a simplified-button-color-string 'foreground on background'. Can be a single color if want to set only the background.",),
	("PSGVAL_NORMAL_BUTTON_BUTTON_TEXT", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "NORMAL_BUTTON", "BUTTON_TEXT", "", "str text to display on the button",),
	("PSGVAL_NORMAL_BUTTON_FOCUS", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_BUTTON", "FOCUS", "False", "if True, initial focus will be put on this button",),
	("PSGVAL_NORMAL_BUTTON_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_BUTTON", "FONT", "None", "specifies the font family, size, etc",),
	("PSGVAL_NORMAL_BUTTON_IMAGE_DATA", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_BUTTON", "IMAGE_DATA", "None", "Raw or Base64 representation of the image to put on button. Choose either filename or data",),
	("PSGVAL_NORMAL_BUTTON_IMAGE_FILENAME", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_BUTTON", "IMAGE_FILENAME", "None", "image filename if there is a button image. GIFs and PNGs only.",),
	("PSGVAL_NORMAL_BUTTON_KEY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_BUTTON", "KEY", "None", "Used with window.FindElement and with return values to uniquely identify this element to uniquely identify this element",),
	("PSGVAL_NORMAL_CHECKBOX", FMAXPSG_SCTN0905_TUPDICT_DEF, "NORMAL_CHECKBOX", "set a checkbox in motion",),
	("PSGVAL_NORMAL_CHECKBOX_BACKGROUND_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_CHECKBOX", "BACKGROUND_COLOR", "None", "color of background",),
	("PSGVAL_NORMAL_CHECKBOX_CHECKBOX_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_CHECKBOX", "CHECKBOX_COLOR", "None", "color of background of the box that has the check mark in it. The checkmark is the same color as the text",),
	("PSGVAL_NORMAL_CHECKBOX_DEFAULT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_CHECKBOX", "DEFAULT", "False", "Set to True if you want this checkbox initially checked",),
	("PSGVAL_NORMAL_CHECKBOX_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_CHECKBOX", "FONT", "None", "specifies the font family, size, etc",),
	("PSGVAL_NORMAL_CHECKBOX_KEY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_CHECKBOX", "KEY", "None", "Used with window.FindElement and with return values to uniquely identify this element",),
	("PSGVAL_NORMAL_CHECKBOX_TEXT", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "NORMAL_CHECKBOX", "TEXT", "", "Text to display next to checkbox",),
	("PSGVAL_NORMAL_CHECKBOX_TEXT_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_CHECKBOX", "TEXT_COLOR", "None", "color of the text",),
	("PSGVAL_NORMAL_COMBO", FMAXPSG_SCTN0905_TUPDICT_DEF, "NORMAL_COMBO", "a full combo tupdict",),
	("PSGVAL_NORMAL_COMBO_BACKGROUND_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_COMBO", "BACKGROUND_COLOR", "None", "color of background",),
	("PSGVAL_NORMAL_COMBO_DEFAULT_VALUE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_COMBO", "DEFAULT_VALUE", "None", "Choice to be displayed as initial value. Must match one of values variable contents",),
	("PSGVAL_NORMAL_COMBO_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_COMBO", "FONT", "None", "specifies the font family, size, etc",),
	("PSGVAL_NORMAL_COMBO_KEY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_COMBO", "KEY", "None", "Used with window.FindElement and with return values to uniquely identify this element",),
	("PSGVAL_NORMAL_COMBO_SIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_COMBO", "SIZE", "None", "width, height. Width = characters-wide, height = NOTE it's the number of entries to show in the list",),
	("PSGVAL_NORMAL_COMBO_TEXT_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_COMBO", "TEXT_COLOR", "None", "color of the text",),
	("PSGVAL_NORMAL_COMBO_VALUES", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_COMBO", "VALUES", "[]", "values to choose. While displayed as text, the items returned are what the caller supplied, not text",),
	("PSGVAL_NORMAL_RADIO", FMAXPSG_SCTN0905_TUPDICT_DEF, "NORMAL_RADIO", "define a full radio button entity",),
	("PSGVAL_NORMAL_RADIO_BACKGROUND_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_RADIO", "BACKGROUND_COLOR", "None,", "",),
	("PSGVAL_NORMAL_RADIO_CIRCLE_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_RADIO", "CIRCLE_COLOR", "None,", "",),
	("PSGVAL_NORMAL_RADIO_DEFAULT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_RADIO", "DEFAULT", "False,", "",),
	("PSGVAL_NORMAL_RADIO_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_RADIO", "FONT", "None,", "",),
	("PSGVAL_NORMAL_RADIO_GROUP_ID", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "NORMAL_RADIO", "GROUP_ID", "", "Groups together multiple Radio Buttons. Any type works",),
	("PSGVAL_NORMAL_RADIO_KEY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_RADIO", "KEY", "None,", "",),
	("PSGVAL_NORMAL_RADIO_SIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_RADIO", "SIZE", "(None, None),", "",),
	("PSGVAL_NORMAL_RADIO_TEXT", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "NORMAL_RADIO", "TEXT", "", "",),
	("PSGVAL_NORMAL_RADIO_TEXT_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_RADIO", "TEXT_COLOR", "None,", "",),
	("PSGVAL_NORMAL_SPIN", FMAXPSG_SCTN0905_TUPDICT_DEF, "NORMAL_SPIN", "full spin dict",),
	("PSGVAL_NORMAL_SPIN_BACKGROUND_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_SPIN", "BACKGROUND_COLOR", "None", "color of background",),
	("PSGVAL_NORMAL_SPIN_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_SPIN", "FONT", "None", "specifies the font family, size, etc",),
	("PSGVAL_NORMAL_SPIN_INITIAL_VALUE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_SPIN", "INITIAL_VALUE", "None", "Initial item to show in window. Choose from list of values supplied",),
	("PSGVAL_NORMAL_SPIN_KEY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_SPIN", "KEY", "None", "Used with window.FindElement and with return values to uniquely identify this element",),
	("PSGVAL_NORMAL_SPIN_SIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_SPIN", "SIZE", "(None, None)", "(width, height) width = characters-wide, height = rows-high",),
	("PSGVAL_NORMAL_SPIN_TEXT_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_SPIN", "TEXT_COLOR", "None", "color of the text",),
	("PSGVAL_NORMAL_SPIN_VALUES", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_SPIN", "VALUES", "[]", "List of valid values",),
	("PSGVAL_NORMAL_TEXT", FMAXPSG_SCTN0905_TUPDICT_DEF, "NORMAL_TEXT", "the full monty for text elements",),
	("PSGVAL_NORMAL_TEXT_BACKGROUND_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_TEXT", "BACKGROUND_COLOR", "None", "color of background",),
	("PSGVAL_NORMAL_TEXT_BORDER_WIDTH", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_TEXT", "BORDER_WIDTH", "None", "number of pixels for the border (if using a relief)",),
	("PSGVAL_NORMAL_TEXT_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_TEXT", "FONT", "None", "specifies the font family, size, etc",),
	("PSGVAL_NORMAL_TEXT_GRAB", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_TEXT", "GRAB", "None", "If True can grab this element and move the window around. Default is False",),
	("PSGVAL_NORMAL_TEXT_JUSTIFICATION", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_TEXT", "JUSTIFICATION", "None", "how string should be aligned within space provided by size. Valid choices = `left`, `right`, `center`",),
	("PSGVAL_NORMAL_TEXT_KEY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_TEXT", "KEY", "None", "Used with window.FindElement and with return values to uniquely identify this element to uniquely identify this element",),
	("PSGVAL_NORMAL_TEXT_RELIEF", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_TEXT", "RELIEF", "None", "relief style around the text. Values are same as progress meter relief values. Should be a constant that is defined at starting with 'RELIEF_' - `RELIEF_RAISED, RELIEF_SUNKEN, RELIEF_FLAT, RELIEF_RIDGE, RELIEF_GROOVE, RELIEF_SOLID`",),
	("PSGVAL_NORMAL_TEXT_SIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_TEXT", "SIZE", "(None, None)", "(width, height) width = characters-wide, height = rows-high",),
	("PSGVAL_NORMAL_TEXT_TEXT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_TEXT", "TEXT", "", "The text to display. Can include /n to achieve multiple lines.  Will convert (optional) parameter into a string",),
	("PSGVAL_NORMAL_TEXT_TEXT_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_TEXT", "TEXT_COLOR", "None", "color of the text",),
	("PSGVAL_NORMAL_WINDOW", FMAXPSG_SCTN0905_TUPDICT_DEF, "NORMAL_WINDOW", "define the NORMAL_WINDOW tupdict",),
	("PSGVAL_NORMAL_WINDOW_BACKGROUND_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_WINDOW", "BACKGROUND_COLOR", "None", "color of background",),
	("PSGVAL_NORMAL_WINDOW_FINALIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_WINDOW", "FINALIZE", "False", "If True then the Finalize method will be called. Use this rather than chaining .Finalize for cleaner code",),
	("PSGVAL_NORMAL_WINDOW_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_WINDOW", "FONT", "None", "specifies the font family, size, etc",),
	("PSGVAL_NORMAL_WINDOW_GRAB_ANYWHERE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_WINDOW", "GRAB_ANYWHERE", "False", "If True can use mouse to click and drag to move the window. Almost every location of the window will work except input fields on some systems",),
	("PSGVAL_NORMAL_WINDOW_ICON", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_WINDOW", "ICON", "None", "Can be either a filename or Base64 value. For Windows if filename, it MUST be ICO format. For Linux, must NOT be ICO",),
	("PSGVAL_NORMAL_WINDOW_KEEP_ON_TOP", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_WINDOW", "KEEP_ON_TOP", "False", "If True, window will be created on top of all other windows on screen. It can be bumped down if another window created with this parm",),
	("PSGVAL_NORMAL_WINDOW_LAYOUT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_WINDOW", "LAYOUT", "None", "The layout for the window. Can also be specified in the Layout method",),
	("PSGVAL_NORMAL_WINDOW_LOCATION", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_WINDOW", "LOCATION", "(None, None)", "(x,y) location, in pixels, to locate the upper left corner of the window on the screen. Default is to center on screen.",),
	("PSGVAL_NORMAL_WINDOW_MODAL", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_WINDOW", "MODAL", "False", "If True then this window will be the only window a user can interact with until it is closed",),
	("PSGVAL_NORMAL_WINDOW_NO_TITLEBAR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_WINDOW", "NO_TITLEBAR", "False", "If true, no titlebar nor frame will be shown on window. This means you cannot minimize the window and it will not show up on the taskbar",),
	("PSGVAL_NORMAL_WINDOW_TITLE", FMAXPSG_SCTN0905_TUPDICT_STR_ADD, "NORMAL_WINDOW", "TITLE", "", "The title that will be displayed in the Titlebar and on the Taskbar",),
	("PSGVAL_NORMAL_WINDOW_TITLEBAR_BACKGROUND_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_WINDOW", "TITLEBAR_BACKGROUND_COLOR", "None", "If custom titlebar indicated by use_custom_titlebar, then use this as background color",),
	("PSGVAL_NORMAL_WINDOW_TITLEBAR_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_WINDOW", "TITLEBAR_FONT", "None", "If custom titlebar indicated by use_custom_titlebar, then use this as title font",),
	("PSGVAL_NORMAL_WINDOW_TITLEBAR_ICON", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_WINDOW", "TITLEBAR_ICON", "None", "If custom titlebar indicated by use_custom_titlebar, then use this as the icon (file or base64 bytes)",),
	("PSGVAL_NORMAL_WINDOW_TITLEBAR_TEXT_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_WINDOW", "TITLEBAR_TEXT_COLOR", "None", "If custom titlebar indicated by use_custom_titlebar, then use this as text color",),
	("PSGVAL_NORMAL_WINDOW_TRANSPARENT_COLOR", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "NORMAL_WINDOW", "TRANSPARENT_COLOR", "None", "Any portion of the window that has this color will be completely transparent. You can even click through these spots to the window under this window.",),
	("PSGVAL_UPDATE_COMBO", FMAXPSG_SCTN0905_TUPDICT_DEF, "UPDATE_COMBO", "holds the update combo entity",),
	("PSGVAL_UPDATE_COMBO_DISABLED", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "UPDATE_COMBO", "DISABLED", "None", "set disable state for element",),
	("PSGVAL_UPDATE_COMBO_FONT", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "UPDATE_COMBO", "FONT", "None", "specifies the font family, size, etc",),
	("PSGVAL_UPDATE_COMBO_READONLY", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "UPDATE_COMBO", "READONLY", "None", "make element readonly (user can't change). True means user cannot change",),
	("PSGVAL_UPDATE_COMBO_SET_TO_INDEX", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "UPDATE_COMBO", "SET_TO_INDEX", "None", "",),
	("PSGVAL_UPDATE_COMBO_SIZE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "UPDATE_COMBO", "SIZE", "None", "width, height. Width = characters-wide, height = NOTE it's the number of entries to show in the list",),
	("PSGVAL_UPDATE_COMBO_VALUE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "UPDATE_COMBO", "VALUE", "None", "change which value is current selected based on new list of previous list of choices",),
	("PSGVAL_UPDATE_COMBO_VALUES", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "UPDATE_COMBO", "VALUES", "None", "values to choose. While displayed as text, the items returned are what the caller supplied, not text",),
	("PSGVAL_UPDATE_COMBO_VISIBLE", FMAXPSG_SCTN0905_TUPDICT_VAL_ADD, "UPDATE_COMBO", "VISIBLE", "None", "set visibility state of the element",),
	("PSGVAL__APPMODE", FMAXPSG_SCTN0901_VAL_DEF, "APPMODE", "APPMODE_CLOCKS", "what screen are we showing APPMODE_CLOCKS or APPMODE_CLOCKS+APPMODE_MAIN[+APPMODE_EDIT]",),
	("PSGVAL__AVOID_MOUSE", FMAXPSG_SCTN0901_KEY_DEF, "AVOID_MOUSE", "key for avoiding the mouse bool",),
	("PSGVAL__CLOCKS_BTN_XPAND00", FMAXPSG_SCTN0906_BTN_DEF, "CLOCKS_BTN_XPAND", "",),
	("PSGVAL__CLOCKS_BTN_XPAND01", FMAXPSG_SCTN0906_BTN_STRADD, "CLOCKS_BTN_XPAND", "BUTTON_TEXT", "", "button_text empty for the XPAND button",),
	("PSGVAL__CLOCKS_BTN_XPAND01", FMAXPSG_SCTN0906_BTN_STRADD, "CLOCKS_BTN_XPAND", "IMAGE_FILENAME", "res/xpand.png", "filename for the button icon",),
	("PSGVAL__CLOCKS_BTN_XPAND01", FMAXPSG_SCTN0906_BTN_VALADD, "CLOCKS_BTN_XPAND", "BUTTON_COLOR", "COLORS_BTN_NORMAL", "default button color",),
	("PSGVAL__CLOCKS_BTN_XPAND01", FMAXPSG_SCTN0906_BTN_VALADD, "CLOCKS_BTN_XPAND", "FOCUS", "True", "focus on click",),
	("PSGVAL__CLOCKS_BTN_XPAND01", FMAXPSG_SCTN0906_BTN_VALADD, "CLOCKS_BTN_XPAND", "FONT", "FONT_DEFAULT", "comment",),
	("PSGVAL__CLOCKS_DICT00", FMAXPSG_SCTN0902_DICT_DEF, "CLOCKS_DICT", "holds the values for the clocks frame",),
	("PSGVAL__CLOCKS_DICT01", FMAXPSG_SCTN0902_DICT_STR_ADD, "CLOCKS_DICT", "KEY_TIME_CLOCK", "00:00:00", "holds the values for the clocks frame",),
	("PSGVAL__CLOCKS_DICT01", FMAXPSG_SCTN0902_DICT_STR_ADD, "CLOCKS_DICT", "KEY_TIME_ELAPSED", "00:00:00", "holds the values for the clocks frame",),
	("PSGVAL__CLOCKS_DICT01", FMAXPSG_SCTN0902_DICT_STR_ADD, "CLOCKS_DICT", "KEY_TIME_TOGO", "00:00:00", "holds the values for the clocks frame",),
	("PSGVAL__CLOCKS_FONTSZ_TIME_CLOCK", FMAXPSG_SCTN0901_VAL_DEF, "CLOCKS_FONTSZ_TIME_CLOCK", "(FONT_DEFAULT, CLOCKS_SZ_TIME_CLOCK)", "the font for the clocks only clock",),
	("PSGVAL__CLOCKS_FONTSZ_TIME_ELAPSED", FMAXPSG_SCTN0901_VAL_DEF, "CLOCKS_FONTSZ_TIME_ELAPSED", "(FONT_DEFAULT, CLOCKS_SZ_TIME_ELAPSED)", "the font for the clocks only clock",),
	("PSGVAL__CLOCKS_FONTSZ_TIME_TOGO", FMAXPSG_SCTN0901_VAL_DEF, "CLOCKS_FONTSZ_TIME_TOGO", "(FONT_DEFAULT, CLOCKS_SZ_TIME_TOGO)", "the font for the clocks only clock",),
	("PSGVAL__CLOCKS_TEXT_TIME_CLOCK00", FMAXPSG_SCTN0909_TEXT_DEF, "CLOCKS_TEXT_TIME_CLOCK", "define the text element for CLOCKS_CLOCK_TIME",),
	("PSGVAL__CLOCKS_TEXT_TIME_CLOCK01", FMAXPSG_SCTN0909_TEXT_STR_ADD, "CLOCKS_TEXT_TIME_CLOCK", "JUSTIFICATION", "JUSTIFICATION_CENTER", "center everything",),
	("PSGVAL__CLOCKS_TEXT_TIME_CLOCK01", FMAXPSG_SCTN0909_TEXT_VAL_ADD, "CLOCKS_TEXT_TIME_CLOCK", "BACKGROUND_COLOR", "COLOR_CLOCK_BACKGROUND", "background color for the clock elements",),
	("PSGVAL__CLOCKS_TEXT_TIME_CLOCK01", FMAXPSG_SCTN0909_TEXT_VAL_ADD, "CLOCKS_TEXT_TIME_CLOCK", "FONT", "CLOCKS_FONTSZ_TIME_CLOCK", "font+size line",),
	("PSGVAL__CLOCKS_TEXT_TIME_CLOCK01", FMAXPSG_SCTN0909_TEXT_VAL_ADD, "CLOCKS_TEXT_TIME_CLOCK", "KEY", "KEY_TIME_CLOCK", "characters, line size line",),
	("PSGVAL__CLOCKS_TEXT_TIME_CLOCK01", FMAXPSG_SCTN0909_TEXT_VAL_ADD, "CLOCKS_TEXT_TIME_CLOCK", "SIZE", "(5, 1)", "characters, lines size line",),
	("PSGVAL__CLOCKS_TEXT_TIME_CLOCK01", FMAXPSG_SCTN0909_TEXT_VAL_ADD, "CLOCKS_TEXT_TIME_CLOCK", "TEXT_COLOR", "COLOR_TIME_CLOCK", "the text color for a clock_time element",),
	("PSGVAL__CLOCKS_TEXT_TIME_ELAPSED00", FMAXPSG_SCTN0909_TEXT_DEF, "CLOCKS_TEXT_TIME_ELAPSED", "define the text element for CLOCKS_CLOCK_TIME",),
	("PSGVAL__CLOCKS_TEXT_TIME_ELAPSED01", FMAXPSG_SCTN0909_TEXT_STR_ADD, "CLOCKS_TEXT_TIME_ELAPSED", "JUSTIFICATION", "JUSTIFICATION_CENTER", "center everything",),
	("PSGVAL__CLOCKS_TEXT_TIME_ELAPSED01", FMAXPSG_SCTN0909_TEXT_VAL_ADD, "CLOCKS_TEXT_TIME_ELAPSED", "BACKGROUND_COLOR", "COLOR_CLOCK_BACKGROUND", "background color for the clock elements",),
	("PSGVAL__CLOCKS_TEXT_TIME_ELAPSED01", FMAXPSG_SCTN0909_TEXT_VAL_ADD, "CLOCKS_TEXT_TIME_ELAPSED", "FONT", "CLOCKS_FONTSZ_TIME_CLOCK", "font+size line",),
	("PSGVAL__CLOCKS_TEXT_TIME_ELAPSED01", FMAXPSG_SCTN0909_TEXT_VAL_ADD, "CLOCKS_TEXT_TIME_ELAPSED", "KEY", "KEY_TIME_ELAPSED", "characters, line size line",),
	("PSGVAL__CLOCKS_TEXT_TIME_ELAPSED01", FMAXPSG_SCTN0909_TEXT_VAL_ADD, "CLOCKS_TEXT_TIME_ELAPSED", "SIZE", "(5, 1)", "characters, lines size line",),
	("PSGVAL__CLOCKS_TEXT_TIME_ELAPSED01", FMAXPSG_SCTN0909_TEXT_VAL_ADD, "CLOCKS_TEXT_TIME_ELAPSED", "TEXT_COLOR", "COLOR_TIME_ELAPSED", "the text color for a clock_time element",),
	("PSGVAL__CLOCKS_TEXT_TIME_TOGO00", FMAXPSG_SCTN0909_TEXT_DEF, "CLOCKS_TEXT_TIME_TOGO", "define the text element for CLOCKS_CLOCK_TIME",),
	("PSGVAL__CLOCKS_TEXT_TIME_TOGO01", FMAXPSG_SCTN0909_TEXT_STR_ADD, "CLOCKS_TEXT_TIME_TOGO", "JUSTIFICATION", "JUSTIFICATION_CENTER", "center everything",),
	("PSGVAL__CLOCKS_TEXT_TIME_TOGO01", FMAXPSG_SCTN0909_TEXT_VAL_ADD, "CLOCKS_TEXT_TIME_TOGO", "BACKGROUND_COLOR", "COLOR_CLOCK_BACKGROUND", "background color for the clock elements",),
	("PSGVAL__CLOCKS_TEXT_TIME_TOGO01", FMAXPSG_SCTN0909_TEXT_VAL_ADD, "CLOCKS_TEXT_TIME_TOGO", "FONT", "CLOCKS_FONTSZ_TIME_CLOCK", "font+size line",),
	("PSGVAL__CLOCKS_TEXT_TIME_TOGO01", FMAXPSG_SCTN0909_TEXT_VAL_ADD, "CLOCKS_TEXT_TIME_TOGO", "KEY", "KEY_TIME_TOGO", "characters, line size line",),
	("PSGVAL__CLOCKS_TEXT_TIME_TOGO01", FMAXPSG_SCTN0909_TEXT_VAL_ADD, "CLOCKS_TEXT_TIME_TOGO", "SIZE", "(5, 1)", "characters, lines size line",),
	("PSGVAL__CLOCKS_TEXT_TIME_TOGO01", FMAXPSG_SCTN0909_TEXT_VAL_ADD, "CLOCKS_TEXT_TIME_TOGO", "TEXT_COLOR", "COLOR_TIME_TOGO", "the text color for a clock_time element",),
	("PSGVAL__COLORS_BTN_NORMAL", FMAXPSG_SCTN0901_VAL_DEF, "COLORS_BTN_NORMAL", "(COLOR_TEXT_NORMAL, COLOR_BACKGROUND)", "comment",),
	("PSGVAL__COLORS_TEXT_HIGH", FMAXPSG_SCTN0901_VAL_DEF, "COLORS_TEXT_HIGH", "(COLOR_TEXT_HIGH, COLOR_BACKGROUND)", "combined colors for a clock text element",),
	("PSGVAL__COLORS_TEXT_LOW", FMAXPSG_SCTN0901_VAL_DEF, "COLORS_TEXT_LOW", "(COLOR_TEXT_LOW, COLOR_BACKGROUND)", "combined colors for a clock text element",),
	("PSGVAL__COLORS_TEXT_NORMAL", FMAXPSG_SCTN0901_VAL_DEF, "COLORS_TEXT_NORMAL", "(COLOR_TEXT_NORMAL, COLOR_BACKGROUND)", "combined colors for a clock text element",),
	("PSGVAL__COLORS_TIME_CLOCK", FMAXPSG_SCTN0901_VAL_DEF, "COLORS_TIME_CLOCK", "(COLOR_TIME_CLOCK, COLOR_CLOCK_BACKGROUND)", "combined colors for a clock text element",),
	("PSGVAL__COLORS_TIME_ELAPSED", FMAXPSG_SCTN0901_VAL_DEF, "COLORS_TIME_ELAPSED", "(COLOR_TIME_ELAPSED, COLOR_CLOCK_BACKGROUND)", "combined colors for a clock text element",),
	("PSGVAL__COLORS_TIME_TOGO", FMAXPSG_SCTN0901_VAL_DEF, "COLORS_TIME_TOGO", "(COLOR_TIME_TOGO, COLOR_CLOCK_BACKGROUND)", "combined colors for a clock text element",),
	("PSGVAL__EVENT_MODE", FMAXPSG_SCTN0901_KEY_DEF, "EVENT_MODE", "",),
	("PSGVAL__EVENT_MODE_ALARM", FMAXPSG_SCTN0901_KEY_DEF, "EVENT_MODE_ALARM", "",),
	("PSGVAL__EVENT_MODE_ALARMREMIND", FMAXPSG_SCTN0901_KEY_DEF, "EVENT_MODE_ALARMREMIND", "",),
	("PSGVAL__EVENT_MODE_INTERVAL", FMAXPSG_SCTN0901_KEY_DEF, "EVENT_MODE_INTERVAL", "",),
	("PSGVAL__INDEX_OF_NEXT_EVENT", FMAXPSG_SCTN0901_KEY_DEF, "INDEX_OF_NEXT_EVENT", "",),
	("PSGVAL__KEY_TIME_CLOCK", FMAXPSG_SCTN0901_KEY_DEF, "KEY_TIME_CLOCK", "key for all clocks time",),
	("PSGVAL__KEY_TIME_ELAPSED", FMAXPSG_SCTN0901_KEY_DEF, "KEY_TIME_ELAPSED", "key for all clocks elapsed",),
	("PSGVAL__KEY_TIME_TOGO", FMAXPSG_SCTN0901_KEY_DEF, "KEY_TIME_TOGO", "key for all clocks togo",),
	("PSGVAL__NAME", FMAXPSG_SCTN0901_KEY_DEF, "NAME", "",),
	("PSGVAL__PREDISMISSABLE", FMAXPSG_SCTN0901_KEY_DEF, "PREDISMISSABLE", "",),
	("PSGVAL__RUNNING", FMAXPSG_SCTN0901_KEY_DEF, "RUNNING", "is this interval running or not",),
	("PSGVAL__SNOOZABLE", FMAXPSG_SCTN0901_KEY_DEF, "SNOOZABLE", "",),
	("PSGVAL__SNOOZED", FMAXPSG_SCTN0901_KEY_DEF, "SNOOZED", "snoozed bool",),
	("PSGVAL__TIME_ALARM", FMAXPSG_SCTN0901_KEY_DEF, "TIME_ALARM", "the alarm time",),
	("PSGVAL__TIME_CLOCK", FMAXPSG_SCTN0901_KEY_DEF, "TIME_CLOCK", "the main clock time",),
	("PSGVAL__TIME_ELAPSED", FMAXPSG_SCTN0901_KEY_DEF, "TIME_ELAPSED", "24 hour centric elapsed time running, can be reset, may go to 99h",),
	("PSGVAL__TIME_INTERVAL", FMAXPSG_SCTN0901_KEY_DEF, "TIME_INTERVAL", "",),
	("PSGVAL__TIME_OF_NEXT_EVENT", FMAXPSG_SCTN0901_KEY_DEF, "TIME_OF_NEXT_EVENT", "what time is the next alarm, == TIME_ALARM is tomorrow",),
	("PSGVAL__TIME_REMIND", FMAXPSG_SCTN0901_KEY_DEF, "TIME_REMIND", "",),
	("PSGVAL__TIME_TOGO", FMAXPSG_SCTN0901_KEY_DEF, "TIME_TOGO", "down counter to next event on this window/alarm/interval/reminder",),
	("PSGVAL__TRANSPARENT", FMAXPSG_SCTN0901_KEY_DEF, "TRANSPARENT", "",),
	("PSGVAL__TRANSPARENT_UNDER_MOUSE", FMAXPSG_SCTN0901_KEY_DEF, "TRANSPARENT_UNDER_MOUSE", "is the clock transparent under mouse (ineffective if mouse is avoided)",),
	("PSGVAL___ALPHA_CHANNEL", FMAXPSG_SCTN0910_STR_DEF, "ALPHA_CHANNEL", "alpha_channel", "",),
	("PSGVAL___AUTO_CLOSE", FMAXPSG_SCTN0910_STR_DEF, "AUTO_CLOSE", "auto_close", "",),
	("PSGVAL___AUTO_CLOSE_DURATION", FMAXPSG_SCTN0910_STR_DEF, "AUTO_CLOSE_DURATION", "auto_close_duration", "",),
	("PSGVAL___AUTO_SIZE_BUTTON", FMAXPSG_SCTN0910_STR_DEF, "AUTO_SIZE_BUTTON", "auto_size_button", "",),
	("PSGVAL___AUTO_SIZE_BUTTONS", FMAXPSG_SCTN0910_STR_DEF, "AUTO_SIZE_BUTTONS", "auto_size_buttons", "",),
	("PSGVAL___AUTO_SIZE_TEXT", FMAXPSG_SCTN0910_STR_DEF, "AUTO_SIZE_TEXT", "auto_size_text", "",),
	("PSGVAL___AUTO_SIZE_TEXT", FMAXPSG_SCTN0910_STR_DEF, "AUTO_SIZE_TEXT", "auto_size_text", "",),
	("PSGVAL___BACKGROUND_COLOR", FMAXPSG_SCTN0910_STR_DEF, "BACKGROUND_COLOR", "background_color", "",),
	("PSGVAL___BIND_RETURN_KEY", FMAXPSG_SCTN0910_STR_DEF, "BIND_RETURN_KEY", "bind_return_key", "",),
	("PSGVAL___BORDER_DEPTH", FMAXPSG_SCTN0910_STR_DEF, "BORDER_DEPTH", "border_depth", "",),
	("PSGVAL___BORDER_WIDTH", FMAXPSG_SCTN0910_STR_DEF, "BORDER_WIDTH", "border_width", "",),
	("PSGVAL___BUTTON_COLOR", FMAXPSG_SCTN0910_STR_DEF, "BUTTON_COLOR", "button_color", "",),
	("PSGVAL___BUTTON_TEXT", FMAXPSG_SCTN0910_STR_DEF, "BUTTON_TEXT", "button_text", "",),
	("PSGVAL___BUTTON_TYPE", FMAXPSG_SCTN0910_STR_DEF, "BUTTON_TYPE", "button_type", "",),
	("PSGVAL___CHANGE_SUBMITS", FMAXPSG_SCTN0910_STR_DEF, "CHANGE_SUBMITS", "change_submits", "",),
	("PSGVAL___CHECKBOX_COLOR", FMAXPSG_SCTN0910_STR_DEF, "CHECKBOX_COLOR", "checkbox_color", "color of background of the box that has the check mark in it. The checkmark is the same color as the text",),
	("PSGVAL___CIRCLE_COLOR", FMAXPSG_SCTN0910_STR_DEF, "CIRCLE_COLOR", "circle_color", "",),
	("PSGVAL___CLICK_SUBMITS", FMAXPSG_SCTN0910_STR_DEF, "CLICK_SUBMITS", "click_submits", "",),
	("PSGVAL___DEBUGGER_ENABLED", FMAXPSG_SCTN0910_STR_DEF, "DEBUGGER_ENABLED", "debugger_enabled", "",),
	("PSGVAL___DEFAULT", FMAXPSG_SCTN0910_STR_DEF, "DEFAULT", "default", "",),
	("PSGVAL___DEFAULT_BUTTON_ELEMENT_SIZE", FMAXPSG_SCTN0910_STR_DEF, "DEFAULT_BUTTON_ELEMENT_SIZE", "default_button_element_size", "",),
	("PSGVAL___DEFAULT_ELEMENT_SIZE", FMAXPSG_SCTN0910_STR_DEF, "DEFAULT_ELEMENT_SIZE", "default_element_size", "",),
	("PSGVAL___DEFAULT_EXTENSION", FMAXPSG_SCTN0910_STR_DEF, "DEFAULT_EXTENSION", "default_extension", "",),
	("PSGVAL___DEFAULT_VALUE", FMAXPSG_SCTN0910_STR_DEF, "DEFAULT_VALUE", "default_value", "",),
	("PSGVAL___DISABLED", FMAXPSG_SCTN0910_STR_DEF, "DISABLED", "disabled", "",),
	("PSGVAL___DISABLED_BUTTON_COLOR", FMAXPSG_SCTN0910_STR_DEF, "DISABLED_BUTTON_COLOR", "disabled_button_color", "",),
	("PSGVAL___DISABLE_CLOSE", FMAXPSG_SCTN0910_STR_DEF, "DISABLE_CLOSE", "disable_close", "",),
	("PSGVAL___DISABLE_MINIMIZE", FMAXPSG_SCTN0910_STR_DEF, "DISABLE_MINIMIZE", "disable_minimize", "",),
	("PSGVAL___DISMISSED", FMAXPSG_SCTN0901_KEY_DEF, "DISMISSED", "alarm dismissed bool",),
	("PSGVAL___ELEMENT_JUSTIFICATION", FMAXPSG_SCTN0910_STR_DEF, "ELEMENT_JUSTIFICATION", "element_justification", "",),
	("PSGVAL___ELEMENT_PADDING", FMAXPSG_SCTN0910_STR_DEF, "ELEMENT_PADDING", "element_padding", "",),
	("PSGVAL___ENABLED", FMAXPSG_SCTN0910_STR_DEF, "ENABLED", "enabled", "",),
	("PSGVAL___ENABLE_CLOSE_ATTEMPTED_EVENT", FMAXPSG_SCTN0910_STR_DEF, "ENABLE_CLOSE_ATTEMPTED_EVENT", "enable_close_attempted_event", "",),
	("PSGVAL___ENABLE_EVENTS", FMAXPSG_SCTN0910_STR_DEF, "ENABLE_EVENTS", "enable_events", "",),
	("PSGVAL___EVENT_ENTRIES", FMAXPSG_SCTN0901_KEY_DEF, "EVENT_ENTRIES", "",),
	("PSGVAL___EXPAND_X", FMAXPSG_SCTN0910_STR_DEF, "EXPAND_X", "expand_x", "",),
	("PSGVAL___EXPAND_Y", FMAXPSG_SCTN0910_STR_DEF, "EXPAND_Y", "expand_y", "",),
	("PSGVAL___FILE_TYPES", FMAXPSG_SCTN0910_STR_DEF, "FILE_TYPES", "file_types", "",),
	("PSGVAL___FINALIZE", FMAXPSG_SCTN0910_STR_DEF, "FINALIZE", "finalize", "",),
	("PSGVAL___FOCUS", FMAXPSG_SCTN0910_STR_DEF, "FOCUS", "focus", "",),
	("PSGVAL___FONT_", FMAXPSG_SCTN0910_STR_DEF, "FONT", "font", "",),
	("PSGVAL___FORCE_TOPLEVEL", FMAXPSG_SCTN0910_STR_DEF, "FORCE_TOPLEVEL", "force_toplevel", "",),
	("PSGVAL___GRAB", FMAXPSG_SCTN0910_STR_DEF, "GRAB", "grab", "",),
	("PSGVAL___GRAB_ANYWHERE", FMAXPSG_SCTN0910_STR_DEF, "GRAB_ANYWHERE", "grab_anywhere", "",),
	("PSGVAL___GROUP_ID", FMAXPSG_SCTN0910_STR_DEF, "GROUP_ID", "group_id", "",),
	("PSGVAL___HIGHLIGHT_COLORS", FMAXPSG_SCTN0910_STR_DEF, "HIGHLIGHT_COLORS", "highlight_colors", "",),
	("PSGVAL___ICON", FMAXPSG_SCTN0910_STR_DEF, "ICON", "icon", "",),
	("PSGVAL___IMAGE_DATA", FMAXPSG_SCTN0910_STR_DEF, "IMAGE_DATA", "image_data", "",),
	("PSGVAL___IMAGE_FILENAME", FMAXPSG_SCTN0910_STR_DEF, "IMAGE_FILENAME", "image_filename", "",),
	("PSGVAL___IMAGE_SIZE", FMAXPSG_SCTN0910_STR_DEF, "IMAGE_SIZE", "image_size", "",),
	("PSGVAL___IMAGE_SUBSAMPLE", FMAXPSG_SCTN0910_STR_DEF, "IMAGE_SUBSAMPLE", "image_subsample", "",),
	("PSGVAL___INITIAL_FOLDER", FMAXPSG_SCTN0910_STR_DEF, "INITIAL_FOLDER", "initial_folder", "",),
	("PSGVAL___INITIAL_VALUE", FMAXPSG_SCTN0910_STR_DEF, "INITIAL_VALUE", "initial_value", "",),
	("PSGVAL___JUSTIFICATION", FMAXPSG_SCTN0910_STR_DEF, "JUSTIFICATION", "justification", "",),
	("PSGVAL___K", FMAXPSG_SCTN0910_STR_DEF, "K", "k", "",),
	("PSGVAL___KEEP_ON_TOP", FMAXPSG_SCTN0910_STR_DEF, "KEEP_ON_TOP", "keep_on_top", "",),
	("PSGVAL___KEY", FMAXPSG_SCTN0910_STR_DEF, "KEY", "key", "",),
	("PSGVAL___LAYOUT", FMAXPSG_SCTN0910_STR_DEF, "LAYOUT", "layout", "",),
	("PSGVAL___LOCATION", FMAXPSG_SCTN0910_STR_DEF, "LOCATION", "location", "",),
	("PSGVAL___MARGINS", FMAXPSG_SCTN0910_STR_DEF, "MARGINS", "margins", "",),
	("PSGVAL___METADATA", FMAXPSG_SCTN0910_STR_DEF, "METADATA", "metadata", "",),
	("PSGVAL___MODAL", FMAXPSG_SCTN0910_STR_DEF, "MODAL", "modal", "",),
	("PSGVAL___NO_TITLEBAR", FMAXPSG_SCTN0910_STR_DEF, "NO_TITLEBAR", "no_titlebar", "",),
	("PSGVAL___PAD", FMAXPSG_SCTN0910_STR_DEF, "PAD", "pad", "",),
	("PSGVAL___PROGRESS_BAR_COLOR", FMAXPSG_SCTN0910_STR_DEF, "PROGRESS_BAR_COLOR", "progress_bar_color", "",),
	("PSGVAL___READONLY", FMAXPSG_SCTN0910_STR_DEF, "READONLY", "readonly", "",),
	("PSGVAL___RELIEF", FMAXPSG_SCTN0910_STR_DEF, "RELIEF", "relief", "",),
	("PSGVAL___RESIZABLE", FMAXPSG_SCTN0910_STR_DEF, "RESIZABLE", "resizable", "",),
	("PSGVAL___RETURN_KEYBOARD_EVENTS", FMAXPSG_SCTN0910_STR_DEF, "RETURN_KEYBOARD_EVENTS", "return_keyboard_events", "",),
	("PSGVAL___RIGHT_CLICK_MENU", FMAXPSG_SCTN0910_STR_DEF, "RIGHT_CLICK_MENU", "right_click_menu", "",),
	("PSGVAL___RIGHT_CLICK_MENU_BACKGROUND_COLOR", FMAXPSG_SCTN0910_STR_DEF, "RIGHT_CLICK_MENU_BACKGROUND_COLOR", "right_click_menu_background_color", "",),
	("PSGVAL___RIGHT_CLICK_MENU_DISABLED_TEXT_COLOR", FMAXPSG_SCTN0910_STR_DEF, "RIGHT_CLICK_MENU_DISABLED_TEXT_COLOR", "right_click_menu_disabled_text_color", "",),
	("PSGVAL___RIGHT_CLICK_MENU_FONT", FMAXPSG_SCTN0910_STR_DEF, "RIGHT_CLICK_MENU_FONT", "right_click_menu_font", "",),
	("PSGVAL___RIGHT_CLICK_MENU_SELECTED_COLORS", FMAXPSG_SCTN0910_STR_DEF, "RIGHT_CLICK_MENU_SELECTED_COLORS", "right_click_menu_selected_colors", "",),
	("PSGVAL___RIGHT_CLICK_MENU_TEAROFF", FMAXPSG_SCTN0910_STR_DEF, "RIGHT_CLICK_MENU_TEAROFF", "right_click_menu_tearoff", "",),
	("PSGVAL___RIGHT_CLICK_MENU_TEXT_COLOR", FMAXPSG_SCTN0910_STR_DEF, "RIGHT_CLICK_MENU_TEXT_COLOR", "right_click_menu_text_color", "",),
	("PSGVAL___S", FMAXPSG_SCTN0910_STR_DEF, "S", "s", "",),
	("PSGVAL___SCROLLABLE", FMAXPSG_SCTN0910_STR_DEF, "SCROLLABLE", "scrollable", "can this column be scrolled bool",),
	("PSGVAL___SET_TO_INDEX", FMAXPSG_SCTN0910_STR_DEF, "SET_TO_INDEX", "set_to_index", "change selection to a particular choice starting with index = 0",),
	("PSGVAL___SIZE", FMAXPSG_SCTN0910_STR_DEF, "SIZE", "size", "",),
	("PSGVAL___TARGET", FMAXPSG_SCTN0910_STR_DEF, "TARGET", "target", "",),
	("PSGVAL___TEXT", FMAXPSG_SCTN0910_STR_DEF, "TEXT", "text", "",),
	("PSGVAL___TEXT_COLOR", FMAXPSG_SCTN0910_STR_DEF, "TEXT_COLOR", "text_color", "",),
	("PSGVAL___TEXT_JUSTIFICATION", FMAXPSG_SCTN0910_STR_DEF, "TEXT_JUSTIFICATION", "text_justification", "",),
	("PSGVAL___TITLE", FMAXPSG_SCTN0910_STR_DEF, "TITLE", "title", "",),
	("PSGVAL___TITLEBAR_BACKGROUND_COLOR", FMAXPSG_SCTN0910_STR_DEF, "TITLEBAR_BACKGROUND_COLOR", "titlebar_background_color", "",),
	("PSGVAL___TITLEBAR_FONT", FMAXPSG_SCTN0910_STR_DEF, "TITLEBAR_FONT", "titlebar_font", "",),
	("PSGVAL___TITLEBAR_ICON", FMAXPSG_SCTN0910_STR_DEF, "TITLEBAR_ICON", "titlebar_icon", "",),
	("PSGVAL___TITLEBAR_TEXT_COLOR", FMAXPSG_SCTN0910_STR_DEF, "TITLEBAR_TEXT_COLOR", "titlebar_text_color", "",),
	("PSGVAL___TOOLTIP", FMAXPSG_SCTN0910_STR_DEF, "TOOLTIP", "tooltip", "",),
	("PSGVAL___TRANSPARENT_COLOR", FMAXPSG_SCTN0910_STR_DEF, "TRANSPARENT_COLOR", "transparent_color", "",),
	("PSGVAL___TTK_THEME", FMAXPSG_SCTN0910_STR_DEF, "TTK_THEME", "ttk_theme", "",),
	("PSGVAL___USE_CUSTOM_TITLEBAR", FMAXPSG_SCTN0910_STR_DEF, "USE_CUSTOM_TITLEBAR", "use_custom_titlebar", "",),
	("PSGVAL___USE_DEFAULT_FOCUS", FMAXPSG_SCTN0910_STR_DEF, "USE_DEFAULT_FOCUS", "use_default_focus", "",),
	("PSGVAL___USE_TTK_BUTTONS", FMAXPSG_SCTN0910_STR_DEF, "USE_TTK_BUTTONS", "use_ttk_buttons", "",),
	("PSGVAL___VALUE", FMAXPSG_SCTN0910_STR_DEF, "VALUE", "value", "the value of the element",),
	("PSGVAL___VALUES", FMAXPSG_SCTN0910_STR_DEF, "VALUES", "values", "list of values",),
	("PSGVAL___VERTICAL_ALIGNMENT", FMAXPSG_SCTN0910_STR_DEF, "VERTICAL_ALIGNMENT", "vertical_alignment", "",),
	("PSGVAL___VERTICAL_SCROLL_ONLY", FMAXPSG_SCTN0910_STR_DEF, "VERTICAL_SCROLL_ONLY", "verticale_scroll_only", "",),
	("PSGVAL___VISIBLE", FMAXPSG_SCTN0910_STR_DEF, "VISIBLE", "visible", "visibility of elements",),
	("PSGVAL_____", FMAX_NOP, "FMPSG_BEGINS",),
	# fold here ⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1⥣1
]
