#!/usr/bin/python


import imp
import os


from CF.CONSTANTS import MARKERS as M
from CF.CONSTANTS import NAMES as N
from CF.CONSTANTS import VALS as V



# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# modules defined in FM.py
# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# FM.py is copied, along with the appropriate FMxxxxxx.py file from CONFIGDIR to local by pythonUnitsLink.py
# make sure if you change the modules, you also update the stored copy FMxxxxxx.py TBGLST file when you update FM.py
# CF.py is always linked, make sure to update CFTOP.py and SCTN0102 when FM.py or CF.py are changed
# all other units are loaded dynamically by pythonUnitsLink.py using the SCTN16 structure, FMSCTNENABLED.py file locally, etc.
# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# * def doErrorItem(message_, itemToError_):
# * def explodeItem(itemToExplode_):
# * def M.makeAComment(comment_):
# * def makeADict(dictName_, dictComment_, dictItems_):
# * def makeAList(listName_, listComment_, listItems_):
# * def makeATupDict(tupDictName_, tupDictItems_, tupDictSidecar_):
# * def makeAWideComment(comment_):
# * def makeCF():
# * def makeDBSQLT()
# * def makeDO():
# * def makeDOHBI():
# * def makeFM():
# * def makeFO():
# * def makeSP():
# * def parseTBGLST(FDTBGLST):
# * def readFileToStr(FILENAME_):
# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# * def __main__():


#


#
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * SCTN003 TYPEs and lambda
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*


# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * SCTN101 FMAX _DEF_
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
FMAX.NOP = "FMAX.NOP"  # ignore the remainder of the line
FMAX.SCTNS_DEF = "FMAX.SCTNS_DEF"  # define the sections <NAC><SCTN><MODULE><SUB0><SUB1><SUB2><DESCRIPTION>
FMAX.SCTN0003_LAMBDA_DEF = "FMAX.SCTN0003_LAMBDA_DEF"  # define a lambda function <NAC><K_EVENT_NAME><lambda str>
FMAX.SCTN0003_TYPE_DEF = "FMAX.SCTN0003_TYPE_DEF"  # define a fake type used in the translation dict <NAC><K_EVENT_NAME><TYPE>
FMAX.SCTN0201_STR_DEF = "FMAX.SCTN0201_STR_DEF"  # define a STR in SCTN0201 <NAC><K_EVENT_NAME><str>
FMAX.SCTN0201_VAL_DEF = "FMAX.SCTN0201_VAL_DEF"  # define a VAL in SCTN0201 <NAC><K_EVENT_NAME><VAL>
FMAX.SCTN0202_OPT_ADD_HLPLN = "FMAX.SCTN0202_OPT_ADD_HLPLN"  # add a line to the help for a PARM, after the comment is automatically added<NAC><PARM><ADDONHELPLINE>
FMAX.SCTN0202_OPT_STR_ADD = "FMAX.SCTN0202_OPT_STR_ADD"  # define a '-a[=]' in SCTN22 <NAC><PARM><KEY><VAL>
FMAX.SCTN0202_OPT_VAL_ADD = "FMAX.SCTN0202_OPT_VAL_ADD"  # define a '-a[=]' in SCTN22 <NAC><PARM><KEY><VAL>
FMAX.SCTN0202_OPTDICT_STR_ADD = "FMAX.SCTN0202_OPTDICT_STR_ADD"  # define a OPTNAME: 'str' in SCTN0202 <NAC><KEY><PARM><STRDEFAULT>
FMAX.SCTN0202_OPTDICT_VAL_ADD = "FMAX.SCTN0202_OPTDICT_VAL_ADD"  # define a OPTNAME: VAL in SCTN0202 <NAC><KEY><PARM><VALDEFAULT>
FMAX.SCTN0203_DICT_DEF = "FMAX.SCTN0203_DICT_DEF"  # define a dict in SCTN203 <NAC><DICTNAME><DICTMODE>
FMAX.SCTN0203_DICT_VS_ADD = "FMAX.SCTN0203_DICT_VS_ADD"  # define a dict STR in SCTN203 <NAC><DICTNAME><STR>
FMAX.SCTN0203_DICT_VV_ADD = "FMAX.SCTN0203_DICT_VV_ADD"  # define a dict VAL in SCTN203 <NAC><DICTNAME><VAL>
FMAX.SCTN0204_LIST_DEF = "FMAX.SCTN0204_LIST_DEF"  # define a list in SCTN204 <NAC><LISTNAME>
FMAX.SCTN0204_LIST_STR_ADD = "FMAX.SCTN0204_LIST_STR_ADD"  # define a list STR in SCTN204 <NAC><LISTNAME><STR>
FMAX.SCTN0204_LIST_VAL_ADD = "FMAX.SCTN0204_LIST_VAL_ADD"  # define a VAL in a list in SCTN204 <NAC><LISTNAME><VAL>
FMAX.SCTN0101_AX_DEF = "FMAX.SCTN0101_AX_DEF"  # define a new FM action <NAC>
FMAX.SCTN0102_STR_DEF = "FMAX.SCTN0102_STR_DEF"  # define a FM string <NAC><VALNAME><STR>
FMAX.SCTN0102_VAL_DEF = "FMAX.SCTN0102_VAL_DEF"  # define a FM _value_ <NAC><VALNAME><VAL>
FMAX.SCTN0103_DICT_DEF = "FMAX.SCTN0103_DICT_DEF"  # define a dict for FM <NAC><DICTNAME>
FMAX.SCTN0104_LIST_DEF = "FMAX.SCTN0104_LIST_DEF"  # define a list in FM <NAC><LISTNAME>
FMAX.SCTN0104_LIST_STR_ADD = "FMAX.SCTN0104_LIST_STR_ADD"  # define a list in FM <NAC>
FMAX.SCTN0104_LIST_VAL_ADD = "FMAX.SCTN0104_LIST_VAL_ADD"  # define a list in FM <NAC>
FMAX.SCTN0105_LDICT_DEF = "FMAX.SCTN0105_LDICT_DEF"  # define a dict for FM <NAC>
FMAX.SCTN0105_LDICT_VS_ADD = "FMAX.SCTN0105_LDICT_VS_ADD"  # define a dict for FM <NAC>
FMAX.SCTN0105_LDICT_VV_ADD = "FMAX.SCTN0105_LDICT_VV_ADD"  # define a dict for FM <NAC>
FMAX.SCTN0106_SCTN_DEF = "FMAX.SCTN0106_SCTN_DEF"  # define the SCTN all over the place <NAC><SCTNNAME><DESCRIPTION0>
FMAX.SCTN0900_STR_DEF = "FMAX.SCTN0900_STR_DEF"  # define a string in the first section (colors, etc.) of defines in PSG.py <NAC><VALNAME><VAL>
FMAX.SCTN0900_VAL_DEF = "FMAX.SCTN0900_VAL_DEF"  # define a value in the first define section in PSG.py <NAC><VALNAME><VAL>
FMAX.SCTN0901_DUBLT_SS_DEF = "FMAX.SCTN0901_DUBLT_SS_DEF"  # define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>
FMAX.SCTN0901_DUBLT_SV_DEF = "FMAX.SCTN0901_DUBLT_SV_DEF"  # define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>
FMAX.SCTN0901_DUBLT_VS_DEF = "FMAX.SCTN0901_DUBLT_VS_DEF"  # define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>
FMAX.SCTN0901_DUBLT_VV_DEF = "FMAX.SCTN0901_DUBLT_VV_DEF"  # define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>
FMAX.SCTN0901_KEY_DEF = "FMAX.SCTN0901_KEY_DEF"  # define a key in the second section of defines in PSG.py <NAC><VALNAME>
FMAX.SCTN0901_STR_DEF = "FMAX.SCTN0901_STR_DEF"  # define a string in the second section of defines in PSG.py <NAC><VALNAME><VAL>
FMAX.SCTN0901_VAL_DEF = "FMAX.SCTN0901_VAL_DEF"  # define a value in the second define section in PSG.py <NAC><VALNAME><VAL>
FMAX.SCTN0902_DICT_DEF = "FMAX.SCTN0902_DICT_DEF"  # define a dict in PSG <NAC><DICTNAME>
FMAX.SCTN0902_DICT_SS_ADD = "FMAX.SCTN0902_DICT_SS_ADD"  # add a str-str to a dict <NAC><DICTNAME><STR><STR>
FMAX.SCTN0902_DICT_SV_ADD = "FMAX.SCTN0902_DICT_SV_ADD"  # add a str-val to a dict <NAC><DICTNAME><STR><VAL>
FMAX.SCTN0902_DICT_VS_ADD = "FMAX.SCTN0902_DICT_VS_ADD"  # add a str to a dict <NAC><DICTNAME><KEY><VAL>
FMAX.SCTN0902_DICT_VV_ADD = "FMAX.SCTN0902_DICT_VV_ADD"  # add a val to a dict in PSG <NAC><DICTNAME><KEY><VAL>
FMAX.SCTN0903_LIST_DEF = "FMAX.SCTN0903_LIST_DEF"  # define a list in PSG <NAC><LISTNAME>
FMAX.SCTN0903_LIST_STR_ADD = "FMAX.SCTN0903_LIST_STR_ADD"  # add a str to a list in PSG <NAC><LISTNAME><STR>
FMAX.SCTN0903_LIST_VAL_ADD = "FMAX.SCTN0903_LIST_VAL_ADD"  # add a val to a list in PSG <NAC><LISTNAME><VAL>
FMAX.SCTN0904_PLATEQ_ELIF_ADD = "FMAX.SCTN0904_PLATEQ_ELIF_ADD"  # platform equalizer define an elif <NAC><STRUCTNAME><CONDITION><VAL>
FMAX.SCTN0904_PLATEQ_ELSE_ADD = "FMAX.SCTN0904_PLATEQ_ELSE_ADD"  # platform equalizer define an else <NAC><STRUCTNAME><CONDITION>
FMAX.SCTN0904_PLATEQ_FUNC_STR_ADD = "FMAX.SCTN0904_PLATEQ_FUNC_STR_ADD"  # add a function string line <NAC><STRUCTNAME><CONDITION>
FMAX.SCTN0904_PLATEQ_IF_ADD = "FMAX.SCTN0904_PLATEQ_IF_ADD"  # add the 1st if to a platform equalizer <NAC><STRUCTNAME><CONDITION>
FMAX.SCTN0904_PLATEQ_PLAT_DEF = "FMAX.SCTN0904_PLATEQ_PLAT_DEF"  # define a platform equalizer struct <NAC><STRUCTNAME>
FMAX.SCTN0904_PLATEQ_STR_ADD = "FMAX.SCTN0904_PLATEQ_STR_ADD"  # add a string to a PLATEQ <NAC><STRUCTNAME><VALNAME><VAL>
FMAX.SCTN0904_PLATEQ_VAL_ADD = "FMAX.SCTN0904_PLATEQ_VAL_ADD"  # add a value to a PLATEQ <NAC><STRUCTNAME><VALNAME><VAL>
FMAX.SCTN0905_TDD_VS_ADD = "FMAX.SCTN0905_TDD_VS_ADD"  # define a ddict <NAC><TUPDICTNAME><KEY><VAL><DDICTKEY>
FMAX.SCTN0905_TDD_VV_ADD = "FMAX.SCTN0905_TDD_VV_ADD"  # define a ddict <NAC><TUPDICTNAME><KEY><VAL><DDICTKEY>
FMAX.SCTN0905_TUPDICT_DDICT_DEF = "FMAX.SCTN0905_TUPDICT_DDICT_DEF"  # define a ddict <NAC><TUPDICTNAME><KEY><DDICTKEY>
FMAX.SCTN0905_TUPDICT_DEF = "FMAX.SCTN0905_TUPDICT_DEF"  # define a TUPDICT in the second define section in PSG.py <NAC><TUPDICTNAME>
FMAX.SCTN0905_TUPDICT_DICT_ADD = "FMAX.SCTN0905_TUPDICT_DICT_ADD"  # add a value to a tupdict <NAC><TUPDICTNAME><KEY><VAL>
FMAX.SCTN0905_TUPDICT_SS_ADD = "FMAX.SCTN0905_TUPDICT_SS_ADD"  # add a str to a tupdict <NAC><TUPDICTNAME><STR><STR>
FMAX.SCTN0905_TUPDICT_SV_ADD = "FMAX.SCTN0905_TUPDICT_SV_ADD"  # add a value to a tupdict <NAC><TUPDICTNAME><STR><VAL>
FMAX.SCTN0905_TUPDICT_VS_ADD = "FMAX.SCTN0905_TUPDICT_VS_ADD"  # add a str to a tupdict <NAC><TUPDICTNAME><KEY><STR>
FMAX.SCTN0905_TUPDICT_VV_ADD = "FMAX.SCTN0905_TUPDICT_VV_ADD"  # add a value to a tupdict <NAC><TUPDICTNAME><KEY><VAL>
FMAX.SCTN0906_BTN_DEF = "FMAX.SCTN0906_BTN_DEF"  # define a button <NAC><BTNNAME>
FMAX.SCTN0906_BTN_STR_ADD = "FMAX.SCTN0906_BTN_STR_ADD"  # add a (VAL,VAL) to a tupdict <NAC><BTNNAME><KEY><VAL>
FMAX.SCTN0906_BTN_VAL_ADD = "FMAX.SCTN0906_BTN_VAL_ADD"  # add a (VAL,VAL) to a tupdict <NAC><BTNNAME><KEY><VAL>
FMAX.SCTN0907_SPIN_DEF = "FMAX.SCTN0907_SPIN_DEF"  # define a spin box entry <NAC><SPINNAME>
FMAX.SCTN0907_SPIN_DICT_STR_ADD = "FMAX.SCTN0907_SPIN_DICT_STR_ADD"  # add a STR to the SPINDICT <NAC><SPINNAME><KEY><STR>
FMAX.SCTN0907_SPIN_DICT_VAL_ADD = "FMAX.SCTN0907_SPIN_DICT_VAL_ADD"  # add a VAL to the SPINDICT <NAC><SPINNAME><KEY><VAL>
FMAX.SCTN0907_SPIN_VALUES_STR_ADD = "FMAX.SCTN0907_SPIN_VALUES_STR_ADD"  # add a STR to the values list <NAC><SPINNAME><STR>
FMAX.SCTN0907_SPIN_VALUES_VAL_ADD = "FMAX.SCTN0907_SPIN_VALUES_VAL_ADD"  # add a VAL to the values list <NAC><SPINNAME><VAL>
FMAX.SCTN0908_CHECKBOX_DEF = "FMAX.SCTN0908_CHECKBOX_DEF"  # define a checkbox <NAC><CHECKBOXNAME>
FMAX.SCTN0908_CHECKBOX_STR_ADD = "FMAX.SCTN0908_CHECKBOX_STR_ADD"  # add a str to a checkbox <NAC><CHECKBOXNAME><KEY><VAL>
FMAX.SCTN0908_CHECKBOX_VAL_ADD = "FMAX.SCTN0908_CHECKBOX_VAL_ADD"  # add a val to a checkbox <NAC><CHECKBOXNAME><KEY><VAL>
FMAX.SCTN0909_TEXT_DEF = "FMAX.SCTN0909_TEXT_DEF"  # define a text <NAC><TEXTNAME>
FMAX.SCTN0909_TEXT_STR_ADD = "FMAX.SCTN0909_TEXT_STR_ADD"  # add a str to a text element <NAC><TEXTNAME><KEY><VAL>
FMAX.SCTN0909_TEXT_VAL_ADD = "FMAX.SCTN0909_TEXT_VAL_ADD"  # add a val to a text element <NAC><TEXTNAME>
FMAX.SCTN090A_RADIO_DEF = "FMAX.SCTN090A_RADIO_DEF"  # define a radio button element
FMAX.SCTN090B_COLUMN_BUTTON_ADD = "FMAX.SCTN090B_COLUMN_BUTTON_ADD"  # add a button to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN090B_COLUMN_CHECKBOX_ADD = "FMAX.SCTN090B_COLUMN_CHECKBOX_ADD"  # add a combo to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN090B_COLUMN_COLUMN_ADD = "FMAX.SCTN090B_COLUMN_COLUMN_ADD"  # add a column to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN090B_COLUMN_COLUMN_PARM_STR_ADD = "FMAX.SCTN090B_COLUMN_COLUMN_PARM_STR_ADD"  # add a column parm to the column to a row <NAC><COLUMNNAME>[ROWKEY]<LEVEL><KEY><VAL>
FMAX.SCTN090B_COLUMN_COLUMN_PARM_VAL_ADD = "FMAX.SCTN090B_COLUMN_COLUMN_PARM_VAL_ADD"  # add a column parm to the column to a row <NAC><COLUMNNAME>[ROWKEY]<LEVEL><KEY><VAL>
FMAX.SCTN090B_COLUMN_COMBO_ADD = "FMAX.SCTN090B_COLUMN_COMBO_ADD"  # add a combo to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN090B_COLUMN_DEF = "FMAX.SCTN090B_COLUMN_DEF"  # define a column <NAC><COLUMNNAME>
FMAX.SCTN090B_COLUMN_KEY_ADD = "FMAX.SCTN090B_COLUMN_KEY_ADD"  # add a key to a column element 'key=' will be added automatically <NAC><COLUMNNAME><ROWKEY><ELEMENTKEY><VAL>
FMAX.SCTN090B_COLUMN_PACKEDPARM_ADD = "FMAX.SCTN090B_COLUMN_PACKEDPARM_ADD"  # add packedparms to a column entry <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
FMAX.SCTN090B_COLUMN_PARM_ADD = "FMAX.SCTN090B_COLUMN_PARM_ADD"  # add parms to a column entry <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
FMAX.SCTN090B_COLUMN_RADIO_ADD = "FMAX.SCTN090B_COLUMN_RADIO_ADD"  # add a radio to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN090B_COLUMN_ROW_ADD = "FMAX.SCTN090B_COLUMN_ROW_ADD"  # add a row [] to a column <NAC><COLUMNNAME><ROWKEY><LEVEL>
FMAX.SCTN090B_COLUMN_SPIN_ADD = "FMAX.SCTN090B_COLUMN_SPIN_ADD"  # add a spinbox to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN090B_COLUMN_TEXT_ADD = "FMAX.SCTN090B_COLUMN_TEXT_ADD"  # add a text element to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN090C_APPDS_DEF = "FMAX.SCTN090C_APPDS_DEF"  # add a nested dict holding all of the variables passed between PySimpleGUI and this app
FMAX.SCTN090C_APPDS_DICT_DEF = "FMAX.SCTN090C_APPDS_DICT_DEF"  # add a dict to the mainapp dict <NAC><DICTNAME
FMAX.SCTN090C_APPDS_DICT_VS_ADD = "FMAX.SCTN090C_APPDS_DICT_VS_ADD"  # add a string to a dict mainapp dict <NAC><DICTNAME><KEY><STR>
FMAX.SCTN090C_APPDS_DICT_VV_ADD = "FMAX.SCTN090C_APPDS_DICT_VV_ADD"  # add a value to a dict mainapp dict <NAC><DICTNAME><KEY><VAL>
FMAX.SCTN090C_APPDS_VS_ADD = "FMAX.SCTN090C_APPDS_VS_ADD"  # add a string to the mainapp dict <NAC><KEY><STR>
FMAX.SCTN090C_APPDS_VV_ADD = "FMAX.SCTN090C_APPDS_VV_ADD"  # add a value to the mainapp dict <NAC><KEY><VAL>
FMAX.SCTN090D_FORMMAIN_DEF = "FMAX.SCTN090D_FORMMAIN_DEF"  # define a frame <NAC><FRAMENAME><_WINDOW_><FINALIZEBOOL> (** added automatically bool adds or not chained finalize() call)
FMAX.SCTN090E_LAYOUT_BUTTON_ADD = "FMAX.SCTN090E_LAYOUT_BUTTON_ADD"  # add a button to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN090E_LAYOUT_CHECKBOX_ADD = "FMAX.SCTN090E_LAYOUT_CHECKBOX_ADD"  # add a checkbox to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN090E_LAYOUT_COLUMN_ADD = "FMAX.SCTN090E_LAYOUT_COLUMN_ADD"  # add a column to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN090E_LAYOUT_COMBO_ADD = "FMAX.SCTN090E_LAYOUT_COMBO_ADD"  # add a combo to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN090E_LAYOUT_DEF = "FMAX.SCTN090E_LAYOUT_DEF"  # define a layout <NAC><LAYOUTNAME>
FMAX.SCTN090E_LAYOUT_KEY_ADD = "FMAX.SCTN090E_LAYOUT_KEY_ADD"  # add a key to a layout element 'key=' will be added automatically <NAC><LAYOUTNAME><ROWKEY><ELEMENTKEY><VAL>
FMAX.SCTN090E_LAYOUT_PACKEDPARM_ADD = "FMAX.SCTN090E_LAYOUT_PACKEDPARM_ADD"  # add packedparms to a layout entry <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
FMAX.SCTN090E_LAYOUT_PARM_VAL_ADD = "FMAX.SCTN090E_LAYOUT_PARM_VAL_ADD"  # add parms to a layout entry <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
FMAX.SCTN090E_LAYOUT_RADIO_ADD = "FMAX.SCTN090E_LAYOUT_RADIO_ADD"  # add a radio to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN090E_LAYOUT_ROW_ADD = "FMAX.SCTN090E_LAYOUT_ROW_ADD"  # add a row [] to a layout <NAC><LAYOUTNAME><ROWKEY><LEVEL>
FMAX.SCTN090E_LAYOUT_SPIN_ADD = "FMAX.SCTN090E_LAYOUT_SPIN_ADD"  # add a spinbox to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN090E_LAYOUT_TEXT_ADD = "FMAX.SCTN090E_LAYOUT_TEXT_ADD"  # add a text element to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN090F_WINDOW_DEF = "FMAX.SCTN090F_WINDOW_DEF"  # define a window element <NAC><WINDOWNAME>
FMAX.SCTN090F_WINDOW_STR_ADD = "FMAX.SCTN090F_WINDOW_STR_ADD"  # add a str to the window element <NAC><WINDOWNAME><VALNAME><VAL>
FMAX.SCTN090F_WINDOW_VAL_ADD = "FMAX.SCTN090F_WINDOW_VAL_ADD"  # add a str to the window element <NAC><WINDOWNAME><VALNAME><VAL>
FMAX.SCTN0910_DUBLT_SS_DEF = "FMAX.SCTN0910_DUBLT_SS_DEF"  # define a (x,y) tuple <NAC><DUBTUPNAME><VAL1><VAL2>
FMAX.SCTN0910_DUBLT_SV_DEF = "FMAX.SCTN0910_DUBLT_SV_DEF"  # define a (x,y) tuple <NAC><DUBTUPNAME><VAL1><VAL2>
FMAX.SCTN0910_DUBLT_VS_DEF = "FMAX.SCTN0910_DUBLT_VS_DEF"  # define a (x,y) tuple <NAC><DUBTUPNAME><VAL1><VAL2>
FMAX.SCTN0910_DUBLT_VV_DEF = "FMAX.SCTN0910_DUBLT_VV_DEF"  # define a (x,y) tuple <NAC><DUBTUPNAME><VAL1><VAL2>
FMAX.SCTN0910_STR_DEF = "FMAX.SCTN0910_STR_DEF"  # define a string in the second section of defines in PSG.py <NAC><VALNAME><VAL>
FMAX.SCTN0910_VAL_DEF = "FMAX.SCTN0910_VAL_DEF"  # define a value in the second define section in PSG.py <NAC><VALNAME><VAL>
FMAX.SCTN0911_COMBO_DEF = "FMAX.SCTN0911_COMBO_DEF"  # define a combo box <NAC><COMBOBOXNAME>
FMAX.SCTN0912_FRAMEELEMENT_DEF = "FMAX.SCTN0912_FRAMEELEMENT_DEF"  # define a frame element <NAC><FENAME>
FMAX.SCTN0913_RCMENU_DEF = "FMAX.SCTN0913_RCMENU_DEF"  # define a right click menu <NAC><RCMENUNAME>
FMAX.SCTN0913_RCMENU_VAL_ADD = "FMAX.SCTN0913_RCMENU_VAL_ADD"  # define a right click menu <NAC><RCMENUNAME><VAL>
FMAX.SCTN0914_FORMPOPUP_DEF = "FMAX.SCTN0914_FORMPOPUP_DEF"  # define a frame <NAC><FRAMENAME><_WINDOW_><FINALIZEBOOL> (** added automatically bool adds or not chained finalize() call)
FMAX.SCTN0915_PUDLG_DEF = "FMAX.SCTN0915_PUDLG_DEF"  # define a popup dialog <NAC><POPUPNAME><POPUPTYPE>
FMAX.SCTN0915_PUDLG_DICT_STR_ADD = "FMAX.SCTN0915_PUDLG_DICT_STR_ADD"  # add a str to a text element <NAC><POPUPNAME><KEY><VAL>
FMAX.SCTN0915_PUDLG_DICT_VAL_ADD = "FMAX.SCTN0915_PUDLG_DICT_VAL_ADD"  # add a val to a text element <NAC><POPUPNAME><KEY><VAL>
FMAX.SCTN0915_PUDLG_LIST_STR_ADD = "FMAX.SCTN0915_PUDLG_LIST_STR_ADD"  # add a str to a text element <NAC><POPUPNAME><KEY><VAL>
FMAX.SCTN0915_PUDLG_LIST_VAL_ADD = "FMAX.SCTN0915_PUDLG_LIST_VAL_ADD"  # add a val to a text element <NAC><POPUPNAME><KEY><VAL>
FMAX.SCTN0916_KEY0_DEF = "FMAX.SCTN0916_KEY0_DEF"  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><KEY>
FMAX.SCTN0916_KEY1_DEF = "FMAX.SCTN0916_KEY1_DEF"  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><SUB1><KEY>
FMAX.SCTN0916_KEY2_DEF = "FMAX.SCTN0916_KEY2_DEF"  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><SUB1><SUB2><KEY>
FMAX.SCTN0916_KEY_DEF = "FMAX.SCTN0916_KEY_DEF"  # put a key in def1 of PSG.py <NAC><KEYGROUP><KEY>
FMAX.SCTN0916_KEYSTR0_DEF = "FMAX.SCTN0916_KEYSTR0_DEF"  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><KEY><VAL>
FMAX.SCTN0916_KEYSTR1_DEF = "FMAX.SCTN0916_KEYSTR1_DEF"  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><SUB1><KEY><VAL>
FMAX.SCTN0916_KEYSTR2_DEF = "FMAX.SCTN0916_KEYSTR2_DEF"  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><SUB1><SUB2><KEY><VAL>
FMAX.SCTN0916_KEYSTR_DEF = "FMAX.SCTN0916_KEYSTR_DEF"  # put a key in def1 of PSG.py <NAC><KEYGROUP><KEY><VAL>
FMAX.SCTN09FF_BTN_DEF = "FMAX.SCTN09FF_BTN_DEF"  # define a button <NAC><CLASSNAME><BTNNAME>
FMAX.SCTN09FF_BTN_STR_ADD = "FMAX.SCTN09FF_BTN_STR_ADD"  # add a (VAL,VAL) to a tupdict <NAC><CLASSNAME><BTNNAME><KEY><VAL>
FMAX.SCTN09FF_BTN_VAL_ADD = "FMAX.SCTN09FF_BTN_VAL_ADD"  # add a (VAL,VAL) to a tupdict <NAC><CLASSNAME><BTNNAME><KEY><VAL>
FMAX.SCTN09FF_CHECKBOX_DEF = "FMAX.SCTN09FF_CHECKBOX_DEF"  # define a checkbox <NAC><CLASSNAME><CHECKBOXNAME>
FMAX.SCTN09FF_CHECKBOX_PARM_ADD = "FMAX.SCTN09FF_CHECKBOX_PARM_ADD"  # add a parameter to a checkbox <NAC><CLASSNAME><CHECKBOXNAME><VAL>
FMAX.SCTN09FF_CHECKBOX_STR_ADD = "FMAX.SCTN09FF_CHECKBOX_STR_ADD"  # add a str to a checkbox <NAC><CLASSNAME><CHECKBOXNAME><KEY><VAL>
FMAX.SCTN09FF_CHECKBOX_VAL_ADD = "FMAX.SCTN09FF_CHECKBOX_VAL_ADD"  # add a val to a checkbox <NAC><CLASSNAME><CHECKBOXNAME><KEY><VAL>
FMAX.SCTN09FF_COLUMN_BUTTON_ADD = "FMAX.SCTN09FF_COLUMN_BUTTON_ADD"  # add a button to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN09FF_COLUMN_CHECKBOX_ADD = "FMAX.SCTN09FF_COLUMN_CHECKBOX_ADD"  # add a combo to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN09FF_COLUMN_COLUMN_ADD = "FMAX.SCTN09FF_COLUMN_COLUMN_ADD"  # add a column to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN09FF_COLUMN_COLUMN_PARM_STR_ADD = "FMAX.SCTN09FF_COLUMN_COLUMN_PARM_STR_ADD"  # add a column parm to the column to a row <NAC><CLASSNAME><COLUMNNAME>[ROWKEY]<LEVEL><KEY><VAL>
FMAX.SCTN09FF_COLUMN_COLUMN_PARM_VAL_ADD = "FMAX.SCTN09FF_COLUMN_COLUMN_PARM_VAL_ADD"  # add a column parm to the column to a row <NAC><CLASSNAME><COLUMNNAME>[ROWKEY]<LEVEL><KEY><VAL>
FMAX.SCTN09FF_COLUMN_COMBO_ADD = "FMAX.SCTN09FF_COLUMN_COMBO_ADD"  # add a combo to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN09FF_COLUMN_DEF = "FMAX.SCTN09FF_COLUMN_DEF"  # define a column <NAC><CLASSNAME><COLUMNNAME>
FMAX.SCTN09FF_COLUMN_GROUP_DEF = "FMAX.SCTN09FF_COLUMN_GROUP_DEF"  # define a column group <NAC><CLASSNAME><COLUMNGROUP>
FMAX.SCTN09FF_COLUMN_KEY_ADD = "FMAX.SCTN09FF_COLUMN_KEY_ADD"  # add a key to a column element 'key=' will be added automatically <NAC><CLASSNAME><COLUMNNAME><ROWKEY><ELEMENTKEY><VAL>
FMAX.SCTN09FF_COLUMN_PACKEDPARM_ADD = "FMAX.SCTN09FF_COLUMN_PACKEDPARM_ADD"  # add packedparms to a column entry <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
FMAX.SCTN09FF_COLUMN_PARM_ADD = "FMAX.SCTN09FF_COLUMN_PARM_ADD"  # add parms to a column entry <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
FMAX.SCTN09FF_COLUMN_RADIO_ADD = "FMAX.SCTN09FF_COLUMN_RADIO_ADD"  # add a radio to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN09FF_COLUMN_ROW_ADD = "FMAX.SCTN09FF_COLUMN_ROW_ADD"  # add a row [] to a column <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL>
FMAX.SCTN09FF_COLUMN_SPIN_ADD = "FMAX.SCTN09FF_COLUMN_SPIN_ADD"  # add a spinbox to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN09FF_COLUMN_TEXT_ADD = "FMAX.SCTN09FF_COLUMN_TEXT_ADD"  # add a text element to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAX.SCTN09FF_COMBO_DEF = "FMAX.SCTN09FF_COMBO_DEF"  # define a combo box <NAC><COMBOBOXNAME>
FMAX.SCTN09FF_DEF = "FMAX.SCTN09FF_DEF"  # define a class <NAC><CLASSNAME>
FMAX.SCTN09FF_DICT_DEF = "FMAX.SCTN09FF_DICT_DEF"  # define a dict in PSG <NAC><CLASSNAME><DICTNAME>
FMAX.SCTN09FF_DICT_SS_ADD = "FMAX.SCTN09FF_DICT_SS_ADD"  # add a str-str to a dict <NAC><CLASSNAME><DICTNAME><STR><STR>
FMAX.SCTN09FF_DICT_SV_ADD = "FMAX.SCTN09FF_DICT_SV_ADD"  # add a str-val to a dict <NAC><CLASSNAME><DICTNAME><STR><VAL>
FMAX.SCTN09FF_DICT_VS_ADD = "FMAX.SCTN09FF_DICT_VS_ADD"  # add a str to a dict <NAC><CLASSNAME><DICTNAME><KEY><VAL>
FMAX.SCTN09FF_DICT_VV_ADD = "FMAX.SCTN09FF_DICT_VV_ADD"  # add a val to a dict in PSG <NAC><CLASSNAME><DICTNAME><KEY><VAL>
FMAX.SCTN09FF_DPD_DEF = "FMAX.SCTN09FF_DPD_DEF"  # define a DPD debugPrintDict in PSG <NAC><CLASSNAME><DPDNAME>
FMAX.SCTN09FF_DPD_VV_ADD = "FMAX.SCTN09FF_DPD_VV_ADD"  # add a val to a DPD debugPrintDict in PSG <NAC><CLASSNAME><DPDNAME><KEY><VAL>
FMAX.SCTN09FF_FORMMAIN_DEF = "FMAX.SCTN09FF_FORMMAIN_DEF"  # define a class mainframe
FMAX.SCTN09FF_FORMPOPUP_DEF = "FMAX.SCTN09FF_FORMPOPUP_DEF"  # define a class mainframe
FMAX.SCTN09FF_FRAMEELEMENT_DEF = "FMAX.SCTN09FF_FRAMEELEMENT_DEF"  # define a frame element
FMAX.SCTN09FF_FUNCTION_BLANKLINE = "FMAX.SCTN09FF_FUNCTION_BLANKLINE"  # define a class <NAC><CLASSNAME><FUNCNAME><PARMS>
FMAX.SCTN09FF_FUNCTION_DEF = "FMAX.SCTN09FF_FUNCTION_DEF"  # define a class <NAC><CLASSNAME><FUNCNAME><PARMS>
FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE = "FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE"  # define a class <NAC><CLASSNAME><FUNCNAME><FILENAME>
FMAX.SCTN09FF_FUNCTION_LAMBDA1_DEF = "FMAX.SCTN09FF_FUNCTION_LAMBDA1_DEF"  # add a lambda to the top of a function, usually for absorbing things
FMAX.SCTN09FF_FUNCTION_LAMBDA2_DEF = "FMAX.SCTN09FF_FUNCTION_LAMBDA2_DEF"  # add a lambda to the top of a function, usually for absorbing things
FMAX.SCTN09FF_FUNCTION_LINE_ADD = "FMAX.SCTN09FF_FUNCTION_LINE_ADD"  # define a class <NAC><CLASSNAME><FUNCNAME><LINE>
FMAX.SCTN09FF_FUNCTION_READ_FROM_FILE = "FMAX.SCTN09FF_FUNCTION_READ_FROM_FILE"  # define a class <NAC><CLASSNAME><FUNCNAME><FILENAME>
FMAX.SCTN09FF_FUNCTION_STR1_DEF = "FMAX.SCTN09FF_FUNCTION_STR1_DEF"  # define a string in the class <NAC><CLASSNAME><FUNCNAME><VALNAME><VAL>
FMAX.SCTN09FF_FUNCTION_STR2_DEF = "FMAX.SCTN09FF_FUNCTION_STR2_DEF"  # define a string in the class <NAC><CLASSNAME><FUNCNAME><VALNAME><VAL>
FMAX.SCTN09FF_FUNCTION_VAL1_DEF = "FMAX.SCTN09FF_FUNCTION_VAL1_DEF"  # define a value in the class <NAC><CLASSNAME><FUNCNAME><VALNAME><VAL>
FMAXPSG_SCTN09FF_FUNCTION_VAL2_DEF = "FMAXPSG_SCTN09FF_FUNCTION_VAL2_DEF"  # define a value in the class <NAC><CLASSNAME><FUNCNAME><VALNAME><VAL>
FMAXPSG_SCTN09FF_GROUP_SELECT = "FMAXPSG_SCTN09FF_GROUP_SELECT"  # define a column group default <NAC><CLASSNAME><GROUPNAME><GROUPVALUE>
FMAXPSG_SCTN09FF_INIT_ADD1_LAMBDA = "FMAXPSG_SCTN09FF_INIT_ADD1_LAMBDA"  # define a string in the class <NAC><CLASSNAME><VALNAME><VAL>
FMAXPSG_SCTN09FF_INIT_ADD1_LINE = "FMAXPSG_SCTN09FF_INIT_ADD1_LINE"  # define a class <NAC><CLASSNAME><LINE>
FMAXPSG_SCTN09FF_INIT_ADD1_READ_FROM_FILE = "FMAXPSG_SCTN09FF_INIT_ADD1_READ_FROM_FILE"  # read a section of __init__ from a file in res/functions <NAC><CLASSNAME><FILENAME>
FMAXPSG_SCTN09FF_INIT_ADD1_STR = "FMAXPSG_SCTN09FF_INIT_ADD1_STR"  # define a string in the class <NAC><CLASSNAME><VALNAME><VAL>
FMAXPSG_SCTN09FF_INIT_ADD1_VAL = "FMAXPSG_SCTN09FF_INIT_ADD1_VAL"  # define a value in the class <NAC><CLASSNAME><VALNAME><VAL>
FMAXPSG_SCTN09FF_INIT_ADD2_DICTIN_SS = "FMAXPSG_SCTN09FF_INIT_ADD2_DICTIN_SS"  # add a str-str to a dict <NAC><CLASSNAME><STR><STR>
FMAXPSG_SCTN09FF_INIT_ADD2_DICTIN_SV = "FMAXPSG_SCTN09FF_INIT_ADD2_DICTIN_SV"  # add a str-val to a dict <NAC><CLASSNAME><STR><VAL>
FMAXPSG_SCTN09FF_INIT_ADD2_DICTIN_VS = "FMAXPSG_SCTN09FF_INIT_ADD2_DICTIN_VS"  # add a str to a dict <NAC><CLASSNAME><KEY><VAL>
FMAXPSG_SCTN09FF_INIT_ADD2_DICTIN_VV = "FMAXPSG_SCTN09FF_INIT_ADD2_DICTIN_VV"  # add a val to a dict in PSG <NAC><CLASSNAME><KEY><VAL>
FMAXPSG_SCTN09FF_INIT_ADD2_FOREIGN_KEY = "FMAXPSG_SCTN09FF_INIT_ADD2_FOREIGN_KEY"  # add values to _DICT_KEYS, _DICT_KEYS_REVERSE_ for external elements like buttons and checkboxes <NAC><CLASSNAME><KEY>
FMAXPSG_SCTN09FF_INIT_ADD2_LAMBDA = "FMAXPSG_SCTN09FF_INIT_ADD2_LAMBDA"  # define a value in the class <NAC><CLASSNAME><VALNAME><VAL>
FMAXPSG_SCTN09FF_INIT_ADD2_LINE = "FMAXPSG_SCTN09FF_INIT_ADD2_LINE"  # define a class <NAC><CLASSNAME><LINE>
FMAXPSG_SCTN09FF_INIT_ADD2_READ_FROM_FILE = "FMAXPSG_SCTN09FF_INIT_ADD2_READ_FROM_FILE"  # read a section of __init__ from a file in res/functions <NAC><CLASSNAME><FILENAME>
FMAXPSG_SCTN09FF_INIT_ADD2_STR = "FMAXPSG_SCTN09FF_INIT_ADD2_STR"  # define a string in the class <NAC><CLASSNAME><VALNAME><VAL>
FMAXPSG_SCTN09FF_INIT_ADD2_VAL = "FMAXPSG_SCTN09FF_INIT_ADD2_VAL"  # define a value in the class <NAC><CLASSNAME><VALNAME><VAL>
FMAXPSG_SCTN09FF_INIT_ADD3_LINE = "FMAXPSG_SCTN09FF_INIT_ADD3_LINE"  # define a class <NAC><CLASSNAME><LINE>
FMAXPSG_SCTN09FF_INIT_DEF = "FMAXPSG_SCTN09FF_INIT_DEF"  # define a class <NAC><CLASSNAME><PARMS>
FMAXPSG_SCTN09FF_LAYOUT_BUTTON_ADD = "FMAXPSG_SCTN09FF_LAYOUT_BUTTON_ADD"  # add a button to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAXPSG_SCTN09FF_LAYOUT_CHECKBOX_ADD = "FMAXPSG_SCTN09FF_LAYOUT_CHECKBOX_ADD"  # add a checkbox to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAXPSG_SCTN09FF_LAYOUT_COLUMN_ADD = "FMAXPSG_SCTN09FF_LAYOUT_COLUMN_ADD"  # add a column to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAXPSG_SCTN09FF_LAYOUT_COMBO_ADD = "FMAXPSG_SCTN09FF_LAYOUT_COMBO_ADD"  # add a combo to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAXPSG_SCTN09FF_LAYOUT_DEF = "FMAXPSG_SCTN09FF_LAYOUT_DEF"  # define layouts
FMAXPSG_SCTN09FF_LAYOUT_KEY_ADD = "FMAXPSG_SCTN09FF_LAYOUT_KEY_ADD"  # add a key to a layout element 'key=' will be added automatically <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><ELEMENTKEY><VAL>
FMAXPSG_SCTN09FF_LAYOUT_PACKEDPARM_ADD = "FMAXPSG_SCTN09FF_LAYOUT_PACKEDPARM_ADD"  # add packedparms to a layout entry <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
FMAXPSG_SCTN09FF_LAYOUT_PARM_VAL_ADD = "FMAXPSG_SCTN09FF_LAYOUT_PARM_VAL_ADD"  # add parms to a layout entry <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
FMAXPSG_SCTN09FF_LAYOUT_RADIO_ADD = "FMAXPSG_SCTN09FF_LAYOUT_RADIO_ADD"  # add a radio to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAXPSG_SCTN09FF_LAYOUT_ROW_ADD = "FMAXPSG_SCTN09FF_LAYOUT_ROW_ADD"  # add a row [] to a layout <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL>
FMAXPSG_SCTN09FF_LAYOUT_SPIN_ADD = "FMAXPSG_SCTN09FF_LAYOUT_SPIN_ADD"  # add a spinbox to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAXPSG_SCTN09FF_LAYOUT_TEXT_ADD = "FMAXPSG_SCTN09FF_LAYOUT_TEXT_ADD"  # add a text element to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
FMAXPSG_SCTN09FF_LIST_DEF = "FMAXPSG_SCTN09FF_LIST_DEF"  # define a list in PSG <NAC><CLASSNAME><LISTNAME>
FMAXPSG_SCTN09FF_LIST_STR_ADD = "FMAXPSG_SCTN09FF_LIST_STR_ADD"  # add a str to a list in PSG <NAC><CLASSNAME><LISTNAME><STR>
FMAXPSG_SCTN09FF_LIST_VAL_ADD = "FMAXPSG_SCTN09FF_LIST_VAL_ADD"  # add a val to a list in PSG <NAC><CLASSNAME><LISTNAME><VAL>
FMAXPSG_SCTN09FF_RADIO_DEF = "FMAXPSG_SCTN09FF_RADIO_DEF"  # define a radio button element
FMAXPSG_SCTN09FF_RCMENU_DEF = "FMAXPSG_SCTN09FF_RCMENU_DEF"  # define a right click menu
FMAXPSG_SCTN09FF_RCMENU_VAL_ADD = "FMAXPSG_SCTN09FF_RCMENU_VAL_ADD"  # define a right click menu
FMAXPSG_SCTN09FF_SPIN_DEF = "FMAXPSG_SCTN09FF_SPIN_DEF"  # define a spin box entry <NAC><CLASSNAME><SPINNAME>
FMAXPSG_SCTN09FF_SPIN_DICT_VS_ADD = "FMAXPSG_SCTN09FF_SPIN_DICT_VS_ADD"  # add a STR to the SPINDICT <NAC><CLASSNAME><SPINNAME><KEY><STR>
FMAXPSG_SCTN09FF_SPIN_DICT_VV_ADD = "FMAXPSG_SCTN09FF_SPIN_DICT_VV_ADD"  # add a VAL to the SPINDICT <NAC><CLASSNAME><SPINNAME><KEY><VAL>
FMAXPSG_SCTN09FF_SPIN_LIST_STR_ADD = "FMAXPSG_SCTN09FF_SPIN_LIST_STR_ADD"  # add a STR to the values list <NAC><CLASSNAME><SPINNAME><STR>
FMAXPSG_SCTN09FF_SPIN_LIST_VAL_ADD = "FMAXPSG_SCTN09FF_SPIN_LIST_VAL_ADD"  # add a VAL to the values list <NAC><CLASSNAME><SPINNAME><VAL>
FMAXPSG_SCTN09FF_TEXT_DEF = "FMAXPSG_SCTN09FF_TEXT_DEF"  # define a text <NAC><CLASSNAME><TEXTNAME><ISATIME>
FMAXPSG_SCTN09FF_TEXT_PARM_ADD = "FMAXPSG_SCTN09FF_TEXT_PARM_ADD"  # add a PARM to a text element <NAC><CLASSNAME><TEXTNAME><VAL>
FMAXPSG_SCTN09FF_TEXT_STR_ADD = "FMAXPSG_SCTN09FF_TEXT_STR_ADD"  # add a str to a text element <NAC><CLASSNAME><TEXTNAME><KEY><MODULE><VAL>
FMAXPSG_SCTN09FF_TEXT_VAL_ADD = "FMAXPSG_SCTN09FF_TEXT_VAL_ADD"  # add a val to a text element <NAC><CLASSNAME><TEXTNAME><KEY><MODULE><VAL>
FMAXPSG_SCTN09FF_WINDOW_DEF = "FMAXPSG_SCTN09FF_WINDOW_DEF"  # define a main dictdict <NAC><CLASSNAME><MAINNAME>
FMAXPSG_SCTN09FF_WINDOW_STR_ADD = "FMAXPSG_SCTN09FF_WINDOW_STR_ADD"  # add a str to the main dictdict
FMAXPSG_SCTN09FF_WINDOW_VAL_ADD = "FMAXPSG_SCTN09FF_WINDOW_VAL_ADD"  # add a str to the main dictdict


FMAXFM_AXLST = [
	FMAX.NOP,  # ignore the remainder of the line
	FMAX.SCTNS_DEF,  # define the sections <NAC><SCTN><MODULE><SUB0><SUB1><SUB2><DESCRIPTION>
	FMAX.SCTN0003_LAMBDA_DEF,  # define a lambda function <NAC><K_EVENT_NAME><lambda str>
	FMAX.SCTN0003_TYPE_DEF,  # define a fake type used in the translation dict <NAC><K_EVENT_NAME><TYPE>
	FMAX.SCTN0201_STR_DEF,  # define a STR in SCTN0201 <NAC><K_EVENT_NAME><str>
	FMAX.SCTN0201_VAL_DEF,  # define a VAL in SCTN0201 <NAC><K_EVENT_NAME><VAL>
	FMAX.SCTN0202_OPT_ADD_HLPLN,  # add a line to the help for a PARM, after the comment is automatically added<NAC><PARM><ADDONHELPLINE>
	FMAX.SCTN0202_OPT_STR_ADD,  # define a '-a[=]' in SCTN22 <NAC><PARM><KEY><VAL>
	FMAX.SCTN0202_OPT_VAL_ADD,  # define a '-a[=]' in SCTN22 <NAC><PARM><KEY><VAL>
	FMAX.SCTN0202_OPTDICT_STR_ADD,  # define a OPTNAME: 'str' in SCTN0202 <NAC><KEY><PARM><STRDEFAULT>
	FMAX.SCTN0202_OPTDICT_VAL_ADD,  # define a OPTNAME: VAL in SCTN0202 <NAC><KEY><PARM><VALDEFAULT>
	FMAX.SCTN0203_DICT_DEF,  # define a dict in SCTN203 <NAC><DICTNAME><DICTMODE>
	FMAX.SCTN0203_DICT_VS_ADD,  # define a dict STR in SCTN203 <NAC><DICTNAME><STR>
	FMAX.SCTN0203_DICT_VV_ADD,  # define a dict VAL in SCTN203 <NAC><DICTNAME><VAL>
	FMAX.SCTN0204_LIST_DEF,  # define a list in SCTN204 <NAC><LISTNAME>
	FMAX.SCTN0204_LIST_STR_ADD,  # define a list STR in SCTN204 <NAC><LISTNAME><STR>
	FMAX.SCTN0204_LIST_VAL_ADD,  # define a VAL in a list in SCTN204 <NAC><LISTNAME><VAL>
	FMAX.SCTN0101_AX_DEF,  # define a new FM action <NAC>
	FMAX.SCTN0102_STR_DEF,  # define a FM string <NAC><VALNAME><STR>
	FMAX.SCTN0102_VAL_DEF,  # define a FM _value_ <NAC><VALNAME><VAL>
	FMAX.SCTN0103_DICT_DEF,  # define a dict for FM <NAC><DICTNAME>
	FMAX.SCTN0104_LIST_DEF,  # define a list in FM <NAC><LISTNAME>
	FMAX.SCTN0104_LIST_STR_ADD,  # define a list in FM <NAC>
	FMAX.SCTN0104_LIST_VAL_ADD,  # define a list in FM <NAC>
	FMAX.SCTN0105_LDICT_DEF,  # define a dict for FM <NAC>
	FMAX.SCTN0105_LDICT_VS_ADD,  # define a dict for FM <NAC>
	FMAX.SCTN0105_LDICT_VV_ADD,  # define a dict for FM <NAC>
	FMAX.SCTN0106_SCTN_DEF,  # define the SCTN all over the place <NAC><SCTNNAME><DESCRIPTION0>
	FMAX.SCTN0900_STR_DEF,  # define a string in the first section (colors, etc.) of defines in PSG.py <NAC><VALNAME><VAL>
	FMAX.SCTN0900_VAL_DEF,  # define a value in the first define section in PSG.py <NAC><VALNAME><VAL>
	FMAX.SCTN0901_DUBLT_SS_DEF,  # define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>
	FMAX.SCTN0901_DUBLT_SV_DEF,  # define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>
	FMAX.SCTN0901_DUBLT_VS_DEF,  # define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>
	FMAX.SCTN0901_DUBLT_VV_DEF,  # define a (x,y) tuple used to hold URL pairs <NAC><DUBTUPNAME><VAL1><VAL2>
	FMAX.SCTN0901_KEY_DEF,  # define a key in the second section of defines in PSG.py <NAC><VALNAME>
	FMAX.SCTN0901_STR_DEF,  # define a string in the second section of defines in PSG.py <NAC><VALNAME><VAL>
	FMAX.SCTN0901_VAL_DEF,  # define a value in the second define section in PSG.py <NAC><VALNAME><VAL>
	FMAX.SCTN0902_DICT_DEF,  # define a dict in PSG <NAC><DICTNAME>
	FMAX.SCTN0902_DICT_SS_ADD,  # add a str-str to a dict <NAC><DICTNAME><STR><STR>
	FMAX.SCTN0902_DICT_SV_ADD,  # add a str-val to a dict <NAC><DICTNAME><STR><VAL>
	FMAX.SCTN0902_DICT_VS_ADD,  # add a str to a dict <NAC><DICTNAME><KEY><VAL>
	FMAX.SCTN0902_DICT_VV_ADD,  # add a val to a dict in PSG <NAC><DICTNAME><KEY><VAL>
	FMAX.SCTN0903_LIST_DEF,  # define a list in PSG <NAC><LISTNAME>
	FMAX.SCTN0903_LIST_STR_ADD,  # add a str to a list in PSG <NAC><LISTNAME><STR>
	FMAX.SCTN0903_LIST_VAL_ADD,  # add a val to a list in PSG <NAC><LISTNAME><VAL>
	FMAX.SCTN0904_PLATEQ_ELIF_ADD,  # platform equalizer define an elif <NAC><STRUCTNAME><CONDITION><VAL>
	FMAX.SCTN0904_PLATEQ_ELSE_ADD,  # platform equalizer define an else <NAC><STRUCTNAME><CONDITION>
	FMAX.SCTN0904_PLATEQ_FUNC_STR_ADD,  # add a function string line <NAC><STRUCTNAME><CONDITION>
	FMAX.SCTN0904_PLATEQ_IF_ADD,  # add the 1st if to a platform equalizer <NAC><STRUCTNAME><CONDITION>
	FMAX.SCTN0904_PLATEQ_PLAT_DEF,  # define a platform equalizer struct <NAC><STRUCTNAME>
	FMAX.SCTN0904_PLATEQ_STR_ADD,  # add a string to a PLATEQ <NAC><STRUCTNAME><VALNAME><VAL>
	FMAX.SCTN0904_PLATEQ_VAL_ADD,  # add a value to a PLATEQ <NAC><STRUCTNAME><VALNAME><VAL>
	FMAX.SCTN0905_TDD_VS_ADD,  # define a ddict <NAC><TUPDICTNAME><KEY><VAL><DDICTKEY>
	FMAX.SCTN0905_TDD_VV_ADD,  # define a ddict <NAC><TUPDICTNAME><KEY><VAL><DDICTKEY>
	FMAX.SCTN0905_TUPDICT_DDICT_DEF,  # define a ddict <NAC><TUPDICTNAME><KEY><DDICTKEY>
	FMAX.SCTN0905_TUPDICT_DEF,  # define a TUPDICT in the second define section in PSG.py <NAC><TUPDICTNAME>
	FMAX.SCTN0905_TUPDICT_DICT_ADD,  # add a value to a tupdict <NAC><TUPDICTNAME><KEY><VAL>
	FMAX.SCTN0905_TUPDICT_SS_ADD,  # add a str to a tupdict <NAC><TUPDICTNAME><STR><STR>
	FMAX.SCTN0905_TUPDICT_SV_ADD,  # add a value to a tupdict <NAC><TUPDICTNAME><STR><VAL>
	FMAX.SCTN0905_TUPDICT_VS_ADD,  # add a str to a tupdict <NAC><TUPDICTNAME><KEY><STR>
	FMAX.SCTN0905_TUPDICT_VV_ADD,  # add a value to a tupdict <NAC><TUPDICTNAME><KEY><VAL>
	FMAX.SCTN0906_BTN_DEF,  # define a button <NAC><BTNNAME>
	FMAX.SCTN0906_BTN_STR_ADD,  # add a (VAL,VAL) to a tupdict <NAC><BTNNAME><KEY><VAL>
	FMAX.SCTN0906_BTN_VAL_ADD,  # add a (VAL,VAL) to a tupdict <NAC><BTNNAME><KEY><VAL>
	FMAX.SCTN0907_SPIN_DEF,  # define a spin box entry <NAC><SPINNAME>
	FMAX.SCTN0907_SPIN_DICT_STR_ADD,  # add a STR to the SPINDICT <NAC><SPINNAME><KEY><STR>
	FMAX.SCTN0907_SPIN_DICT_VAL_ADD,  # add a VAL to the SPINDICT <NAC><SPINNAME><KEY><VAL>
	FMAX.SCTN0907_SPIN_VALUES_STR_ADD,  # add a STR to the values list <NAC><SPINNAME><STR>
	FMAX.SCTN0907_SPIN_VALUES_VAL_ADD,  # add a VAL to the values list <NAC><SPINNAME><VAL>
	FMAX.SCTN0908_CHECKBOX_DEF,  # define a checkbox <NAC><CHECKBOXNAME>
	FMAX.SCTN0908_CHECKBOX_STR_ADD,  # add a str to a checkbox <NAC><CHECKBOXNAME><KEY><VAL>
	FMAX.SCTN0908_CHECKBOX_VAL_ADD,  # add a val to a checkbox <NAC><CHECKBOXNAME><KEY><VAL>
	FMAX.SCTN0909_TEXT_DEF,  # define a text <NAC><TEXTNAME>
	FMAX.SCTN0909_TEXT_STR_ADD,  # add a str to a text element <NAC><TEXTNAME><KEY><VAL>
	FMAX.SCTN0909_TEXT_VAL_ADD,  # add a val to a text element <NAC><TEXTNAME>
	FMAX.SCTN090A_RADIO_DEF,  # define a radio button element
	FMAX.SCTN090B_COLUMN_BUTTON_ADD,  # add a button to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN090B_COLUMN_CHECKBOX_ADD,  # add a combo to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN090B_COLUMN_COLUMN_ADD,  # add a column to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN090B_COLUMN_COLUMN_PARM_STR_ADD,  # add a column parm to the column to a row <NAC><COLUMNNAME>[ROWKEY]<LEVEL><KEY><VAL>
	FMAX.SCTN090B_COLUMN_COLUMN_PARM_VAL_ADD,  # add a column parm to the column to a row <NAC><COLUMNNAME>[ROWKEY]<LEVEL><KEY><VAL>
	FMAX.SCTN090B_COLUMN_COMBO_ADD,  # add a combo to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN090B_COLUMN_DEF,  # define a column <NAC><COLUMNNAME>
	FMAX.SCTN090B_COLUMN_KEY_ADD,  # add a key to a column element 'key=' will be added automatically <NAC><COLUMNNAME><ROWKEY><ELEMENTKEY><VAL>
	FMAX.SCTN090B_COLUMN_PACKEDPARM_ADD,  # add packedparms to a column entry <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
	FMAX.SCTN090B_COLUMN_PARM_ADD,  # add parms to a column entry <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
	FMAX.SCTN090B_COLUMN_RADIO_ADD,  # add a radio to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN090B_COLUMN_ROW_ADD,  # add a row [] to a column <NAC><COLUMNNAME><ROWKEY><LEVEL>
	FMAX.SCTN090B_COLUMN_SPIN_ADD,  # add a spinbox to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN090B_COLUMN_TEXT_ADD,  # add a text element to a row <NAC><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN090C_APPDS_DEF,  # add a nested dict holding all of the variables passed between PySimpleGUI and this app
	FMAX.SCTN090C_APPDS_DICT_DEF,  # add a dict to the mainapp dict <NAC><DICTNAME
	FMAX.SCTN090C_APPDS_DICT_VS_ADD,  # add a string to a dict mainapp dict <NAC><DICTNAME><KEY><STR>
	FMAX.SCTN090C_APPDS_DICT_VV_ADD,  # add a value to a dict mainapp dict <NAC><DICTNAME><KEY><VAL>
	FMAX.SCTN090C_APPDS_VS_ADD,  # add a string to the mainapp dict <NAC><KEY><STR>
	FMAX.SCTN090C_APPDS_VV_ADD,  # add a value to the mainapp dict <NAC><KEY><VAL>
	FMAX.SCTN090D_FORMMAIN_DEF,  # define a frame <NAC><FRAMENAME><_WINDOW_><FINALIZEBOOL> (** added automatically bool adds or not chained finalize() call)
	FMAX.SCTN090E_LAYOUT_BUTTON_ADD,  # add a button to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN090E_LAYOUT_CHECKBOX_ADD,  # add a checkbox to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN090E_LAYOUT_COLUMN_ADD,  # add a column to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN090E_LAYOUT_COMBO_ADD,  # add a combo to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN090E_LAYOUT_DEF,  # define a layout <NAC><LAYOUTNAME>
	FMAX.SCTN090E_LAYOUT_KEY_ADD,  # add a key to a layout element 'key=' will be added automatically <NAC><LAYOUTNAME><ROWKEY><ELEMENTKEY><VAL>
	FMAX.SCTN090E_LAYOUT_PACKEDPARM_ADD,  # add packedparms to a layout entry <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
	FMAX.SCTN090E_LAYOUT_PARM_VAL_ADD,  # add parms to a layout entry <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
	FMAX.SCTN090E_LAYOUT_RADIO_ADD,  # add a radio to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN090E_LAYOUT_ROW_ADD,  # add a row [] to a layout <NAC><LAYOUTNAME><ROWKEY><LEVEL>
	FMAX.SCTN090E_LAYOUT_SPIN_ADD,  # add a spinbox to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN090E_LAYOUT_TEXT_ADD,  # add a text element to a row <NAC><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN090F_WINDOW_DEF,  # define a window element <NAC><WINDOWNAME>
	FMAX.SCTN090F_WINDOW_STR_ADD,  # add a str to the window element <NAC><WINDOWNAME><VALNAME><VAL>
	FMAX.SCTN090F_WINDOW_VAL_ADD,  # add a str to the window element <NAC><WINDOWNAME><VALNAME><VAL>
	FMAX.SCTN0910_DUBLT_SS_DEF,  # define a (x,y) tuple <NAC><DUBTUPNAME><VAL1><VAL2>
	FMAX.SCTN0910_DUBLT_SV_DEF,  # define a (x,y) tuple <NAC><DUBTUPNAME><VAL1><VAL2>
	FMAX.SCTN0910_DUBLT_VS_DEF,  # define a (x,y) tuple <NAC><DUBTUPNAME><VAL1><VAL2>
	FMAX.SCTN0910_DUBLT_VV_DEF,  # define a (x,y) tuple <NAC><DUBTUPNAME><VAL1><VAL2>
	FMAX.SCTN0910_STR_DEF,  # define a string in the second section of defines in PSG.py <NAC><VALNAME><VAL>
	FMAX.SCTN0910_VAL_DEF,  # define a value in the second define section in PSG.py <NAC><VALNAME><VAL>
	FMAX.SCTN0911_COMBO_DEF,  # define a combo box <NAC><COMBOBOXNAME>
	FMAX.SCTN0912_FRAMEELEMENT_DEF,  # define a frame element <NAC><FENAME>
	FMAX.SCTN0913_RCMENU_DEF,  # define a right click menu <NAC><RCMENUNAME>
	FMAX.SCTN0913_RCMENU_VAL_ADD,  # define a right click menu <NAC><RCMENUNAME><VAL>
	FMAX.SCTN0914_FORMPOPUP_DEF,  # define a frame <NAC><FRAMENAME><_WINDOW_><FINALIZEBOOL> (** added automatically bool adds or not chained finalize() call)
	FMAX.SCTN0915_PUDLG_DEF,  # define a popup dialog <NAC><POPUPNAME><POPUPTYPE>
	FMAX.SCTN0915_PUDLG_DICT_STR_ADD,  # add a str to a text element <NAC><POPUPNAME><KEY><VAL>
	FMAX.SCTN0915_PUDLG_DICT_VAL_ADD,  # add a val to a text element <NAC><POPUPNAME><KEY><VAL>
	FMAX.SCTN0915_PUDLG_LIST_STR_ADD,  # add a str to a text element <NAC><POPUPNAME><KEY><VAL>
	FMAX.SCTN0915_PUDLG_LIST_VAL_ADD,  # add a val to a text element <NAC><POPUPNAME><KEY><VAL>
	FMAX.SCTN0916_KEY0_DEF,  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><KEY>
	FMAX.SCTN0916_KEY1_DEF,  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><SUB1><KEY>
	FMAX.SCTN0916_KEY2_DEF,  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><SUB1><SUB2><KEY>
	FMAX.SCTN0916_KEY_DEF,  # put a key in def1 of PSG.py <NAC><KEYGROUP><KEY>
	FMAX.SCTN0916_KEYSTR0_DEF,  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><KEY><VAL>
	FMAX.SCTN0916_KEYSTR1_DEF,  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><SUB1><KEY><VAL>
	FMAX.SCTN0916_KEYSTR2_DEF,  # put a key in def1 of PSG.py <NAC><KEYGROUP><SUB0><SUB1><SUB2><KEY><VAL>
	FMAX.SCTN0916_KEYSTR_DEF,  # put a key in def1 of PSG.py <NAC><KEYGROUP><KEY><VAL>
	FMAX.SCTN09FF_BTN_DEF,  # define a button <NAC><CLASSNAME><BTNNAME>
	FMAX.SCTN09FF_BTN_STR_ADD,  # add a (VAL,VAL) to a tupdict <NAC><CLASSNAME><BTNNAME><KEY><VAL>
	FMAX.SCTN09FF_BTN_VAL_ADD,  # add a (VAL,VAL) to a tupdict <NAC><CLASSNAME><BTNNAME><KEY><VAL>
	FMAX.SCTN09FF_CHECKBOX_DEF,  # define a checkbox <NAC><CLASSNAME><CHECKBOXNAME>
	FMAX.SCTN09FF_CHECKBOX_PARM_ADD,  # add a parameter to a checkbox <NAC><CLASSNAME><CHECKBOXNAME><VAL>
	FMAX.SCTN09FF_CHECKBOX_STR_ADD,  # add a str to a checkbox <NAC><CLASSNAME><CHECKBOXNAME><KEY><VAL>
	FMAX.SCTN09FF_CHECKBOX_VAL_ADD,  # add a val to a checkbox <NAC><CLASSNAME><CHECKBOXNAME><KEY><VAL>
	FMAX.SCTN09FF_COLUMN_BUTTON_ADD,  # add a button to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN09FF_COLUMN_CHECKBOX_ADD,  # add a combo to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN09FF_COLUMN_COLUMN_ADD,  # add a column to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN09FF_COLUMN_COLUMN_PARM_STR_ADD,  # add a column parm to the column to a row <NAC><CLASSNAME><COLUMNNAME>[ROWKEY]<LEVEL><KEY><VAL>
	FMAX.SCTN09FF_COLUMN_COLUMN_PARM_VAL_ADD,  # add a column parm to the column to a row <NAC><CLASSNAME><COLUMNNAME>[ROWKEY]<LEVEL><KEY><VAL>
	FMAX.SCTN09FF_COLUMN_COMBO_ADD,  # add a combo to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN09FF_COLUMN_DEF,  # define a column <NAC><CLASSNAME><COLUMNNAME>
	FMAX.SCTN09FF_COLUMN_GROUP_DEF,  # define a column group <NAC><CLASSNAME><COLUMNGROUP>
	FMAX.SCTN09FF_COLUMN_KEY_ADD,  # add a key to a column element 'key=' will be added automatically <NAC><CLASSNAME><COLUMNNAME><ROWKEY><ELEMENTKEY><VAL>
	FMAX.SCTN09FF_COLUMN_PACKEDPARM_ADD,  # add packedparms to a column entry <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
	FMAX.SCTN09FF_COLUMN_PARM_ADD,  # add parms to a column entry <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
	FMAX.SCTN09FF_COLUMN_RADIO_ADD,  # add a radio to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN09FF_COLUMN_ROW_ADD,  # add a row [] to a column <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL>
	FMAX.SCTN09FF_COLUMN_SPIN_ADD,  # add a spinbox to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN09FF_COLUMN_TEXT_ADD,  # add a text element to a row <NAC><CLASSNAME><COLUMNNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAX.SCTN09FF_COMBO_DEF,  # define a combo box <NAC><COMBOBOXNAME>
	FMAX.SCTN09FF_DEF,  # define a class <NAC><CLASSNAME>
	FMAX.SCTN09FF_DICT_DEF,  # define a dict in PSG <NAC><CLASSNAME><DICTNAME>
	FMAX.SCTN09FF_DICT_SS_ADD,  # add a str-str to a dict <NAC><CLASSNAME><DICTNAME><STR><STR>
	FMAX.SCTN09FF_DICT_SV_ADD,  # add a str-val to a dict <NAC><CLASSNAME><DICTNAME><STR><VAL>
	FMAX.SCTN09FF_DICT_VS_ADD,  # add a str to a dict <NAC><CLASSNAME><DICTNAME><KEY><VAL>
	FMAX.SCTN09FF_DICT_VV_ADD,  # add a val to a dict in PSG <NAC><CLASSNAME><DICTNAME><KEY><VAL>
	FMAX.SCTN09FF_DPD_DEF,  # define a DPD debugPrintDict in PSG <NAC><CLASSNAME><DPDNAME>
	FMAX.SCTN09FF_DPD_VV_ADD,  # add a val to a DPD debugPrintDict in PSG <NAC><CLASSNAME><DPDNAME><KEY><VAL>
	FMAX.SCTN09FF_FORMMAIN_DEF,  # define a class mainframe
	FMAX.SCTN09FF_FORMPOPUP_DEF,  # define a class mainframe
	FMAX.SCTN09FF_FRAMEELEMENT_DEF,  # define a frame element
	FMAX.SCTN09FF_FUNCTION_BLANKLINE,  # define a class <NAC><CLASSNAME><FUNCNAME><PARMS>
	FMAX.SCTN09FF_FUNCTION_DEF,  # define a class <NAC><CLASSNAME><FUNCNAME><PARMS>
	FMAX.SCTN09FF_FUNCTION_DEF_FROM_FILE,  # define a class <NAC><CLASSNAME><FUNCNAME><FILENAME>
	FMAX.SCTN09FF_FUNCTION_LAMBDA1_DEF,  # add a lambda to the top of a function, usually for absorbing things
	FMAX.SCTN09FF_FUNCTION_LAMBDA2_DEF,  # add a lambda to the top of a function, usually for absorbing things
	FMAX.SCTN09FF_FUNCTION_LINE_ADD,  # define a class <NAC><CLASSNAME><FUNCNAME><LINE>
	FMAX.SCTN09FF_FUNCTION_READ_FROM_FILE,  # define a class <NAC><CLASSNAME><FUNCNAME><FILENAME>
	FMAX.SCTN09FF_FUNCTION_STR1_DEF,  # define a string in the class <NAC><CLASSNAME><FUNCNAME><VALNAME><VAL>
	FMAX.SCTN09FF_FUNCTION_STR2_DEF,  # define a string in the class <NAC><CLASSNAME><FUNCNAME><VALNAME><VAL>
	FMAX.SCTN09FF_FUNCTION_VAL1_DEF,  # define a value in the class <NAC><CLASSNAME><FUNCNAME><VALNAME><VAL>
	FMAXPSG_SCTN09FF_FUNCTION_VAL2_DEF,  # define a value in the class <NAC><CLASSNAME><FUNCNAME><VALNAME><VAL>
	FMAXPSG_SCTN09FF_GROUP_SELECT,  # define a column group default <NAC><CLASSNAME><GROUPNAME><GROUPVALUE>
	FMAXPSG_SCTN09FF_INIT_ADD1_LAMBDA,  # define a string in the class <NAC><CLASSNAME><VALNAME><VAL>
	FMAXPSG_SCTN09FF_INIT_ADD1_LINE,  # define a class <NAC><CLASSNAME><LINE>
	FMAXPSG_SCTN09FF_INIT_ADD1_READ_FROM_FILE,  # read a section of __init__ from a file in res/functions <NAC><CLASSNAME><FILENAME>
	FMAXPSG_SCTN09FF_INIT_ADD1_STR,  # define a string in the class <NAC><CLASSNAME><VALNAME><VAL>
	FMAXPSG_SCTN09FF_INIT_ADD1_VAL,  # define a value in the class <NAC><CLASSNAME><VALNAME><VAL>
	FMAXPSG_SCTN09FF_INIT_ADD2_DICTIN_SS,  # add a str-str to a dict <NAC><CLASSNAME><STR><STR>
	FMAXPSG_SCTN09FF_INIT_ADD2_DICTIN_SV,  # add a str-val to a dict <NAC><CLASSNAME><STR><VAL>
	FMAXPSG_SCTN09FF_INIT_ADD2_DICTIN_VS,  # add a str to a dict <NAC><CLASSNAME><KEY><VAL>
	FMAXPSG_SCTN09FF_INIT_ADD2_DICTIN_VV,  # add a val to a dict in PSG <NAC><CLASSNAME><KEY><VAL>
	FMAXPSG_SCTN09FF_INIT_ADD2_FOREIGN_KEY,  # add values to _DICT_KEYS, _DICT_KEYS_REVERSE_ for external elements like buttons and checkboxes <NAC><CLASSNAME><KEY>
	FMAXPSG_SCTN09FF_INIT_ADD2_LAMBDA,  # define a value in the class <NAC><CLASSNAME><VALNAME><VAL>
	FMAXPSG_SCTN09FF_INIT_ADD2_LINE,  # define a class <NAC><CLASSNAME><LINE>
	FMAXPSG_SCTN09FF_INIT_ADD2_READ_FROM_FILE,  # read a section of __init__ from a file in res/functions <NAC><CLASSNAME><FILENAME>
	FMAXPSG_SCTN09FF_INIT_ADD2_STR,  # define a string in the class <NAC><CLASSNAME><VALNAME><VAL>
	FMAXPSG_SCTN09FF_INIT_ADD2_VAL,  # define a value in the class <NAC><CLASSNAME><VALNAME><VAL>
	FMAXPSG_SCTN09FF_INIT_ADD3_LINE,  # define a class <NAC><CLASSNAME><LINE>
	FMAXPSG_SCTN09FF_INIT_DEF,  # define a class <NAC><CLASSNAME><PARMS>
	FMAXPSG_SCTN09FF_LAYOUT_BUTTON_ADD,  # add a button to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAXPSG_SCTN09FF_LAYOUT_CHECKBOX_ADD,  # add a checkbox to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAXPSG_SCTN09FF_LAYOUT_COLUMN_ADD,  # add a column to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAXPSG_SCTN09FF_LAYOUT_COMBO_ADD,  # add a combo to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAXPSG_SCTN09FF_LAYOUT_DEF,  # define layouts
	FMAXPSG_SCTN09FF_LAYOUT_KEY_ADD,  # add a key to a layout element 'key=' will be added automatically <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><ELEMENTKEY><VAL>
	FMAXPSG_SCTN09FF_LAYOUT_PACKEDPARM_ADD,  # add packedparms to a layout entry <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
	FMAXPSG_SCTN09FF_LAYOUT_PARM_VAL_ADD,  # add parms to a layout entry <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY><VAL>
	FMAXPSG_SCTN09FF_LAYOUT_RADIO_ADD,  # add a radio to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAXPSG_SCTN09FF_LAYOUT_ROW_ADD,  # add a row [] to a layout <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL>
	FMAXPSG_SCTN09FF_LAYOUT_SPIN_ADD,  # add a spinbox to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAXPSG_SCTN09FF_LAYOUT_TEXT_ADD,  # add a text element to a row <NAC><CLASSNAME><LAYOUTNAME><ROWKEY><LEVEL><ELEMENTKEY>
	FMAXPSG_SCTN09FF_LIST_DEF,  # define a list in PSG <NAC><CLASSNAME><LISTNAME>
	FMAXPSG_SCTN09FF_LIST_STR_ADD,  # add a str to a list in PSG <NAC><CLASSNAME><LISTNAME><STR>
	FMAXPSG_SCTN09FF_LIST_VAL_ADD,  # add a val to a list in PSG <NAC><CLASSNAME><LISTNAME><VAL>
	FMAXPSG_SCTN09FF_RADIO_DEF,  # define a radio button element
	FMAXPSG_SCTN09FF_RCMENU_DEF,  # define a right click menu
	FMAXPSG_SCTN09FF_RCMENU_VAL_ADD,  # define a right click menu
	FMAXPSG_SCTN09FF_SPIN_DEF,  # define a spin box entry <NAC><CLASSNAME><SPINNAME>
	FMAXPSG_SCTN09FF_SPIN_DICT_VS_ADD,  # add a STR to the SPINDICT <NAC><CLASSNAME><SPINNAME><KEY><STR>
	FMAXPSG_SCTN09FF_SPIN_DICT_VV_ADD,  # add a VAL to the SPINDICT <NAC><CLASSNAME><SPINNAME><KEY><VAL>
	FMAXPSG_SCTN09FF_SPIN_LIST_STR_ADD,  # add a STR to the values list <NAC><CLASSNAME><SPINNAME><STR>
	FMAXPSG_SCTN09FF_SPIN_LIST_VAL_ADD,  # add a VAL to the values list <NAC><CLASSNAME><SPINNAME><VAL>
	FMAXPSG_SCTN09FF_TEXT_DEF,  # define a text <NAC><CLASSNAME><TEXTNAME><ISATIME>
	FMAXPSG_SCTN09FF_TEXT_PARM_ADD,  # add a PARM to a text element <NAC><CLASSNAME><TEXTNAME><VAL>
	FMAXPSG_SCTN09FF_TEXT_STR_ADD,  # add a str to a text element <NAC><CLASSNAME><TEXTNAME><KEY><MODULE><VAL>
	FMAXPSG_SCTN09FF_TEXT_VAL_ADD,  # add a val to a text element <NAC><CLASSNAME><TEXTNAME><KEY><MODULE><VAL>
	FMAXPSG_SCTN09FF_WINDOW_DEF,  # define a main dictdict <NAC><CLASSNAME><MAINNAME>
	FMAXPSG_SCTN09FF_WINDOW_STR_ADD,  # add a str to the main dictdict
	FMAXPSG_SCTN09FF_WINDOW_VAL_ADD,  # add a str to the main dictdict
]


# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * SCTN102 VAL _DEF_
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
TABLEVEL = "TABLEVEL"  # key for tab levels


# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * SCTN103 _DICT_ _DEF_
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
FILENAMES_DICT = {}  # dict of filename: FD??
FMCF_SCTN0003_TYPE_CMNT_DICT = {}  # SCTN009 types comments
FMCF_SCTN0003_TYPE_DICT = {}  # SCTN003 types
FMCF_SCTN0201_DEF_CMNT_DICT = {}  # SCTN201 defines comments dict
FMCF_SCTN0201_DEF_DICT = {}  # SCTN201 defines dict
FMCF_SCTN0202_OPTIONS_CMNT_DICT = {}  # SCTN202 OPTIONS comments dict
FMCF_SCTN0202_OPTIONS_DICT = {}  # SCTN202 OPTIONS dict
FMCF_SCTN0202_OPTIONSDICT_CMNT_DICT = {}  # SCTN202 OPTIONSDICT comments dict
FMCF_SCTN0202_OPTIONSDICT_DICT = {}  # SCTN202 OPTIONSDICT
FMCF_SCTN0202_OPTIONSHELPDICT_DICT = {}  # SCTN202 OPTIONS HELPDICT
FMCF_SCTN0203_DICT_CMNT_DICT = {}  # SCTN203 dict comments dict
FMCF_SCTN0203_DICT_DICT = {}  # SCTN203 dict dict
FMCF_SCTN0204_LIST_CMNT_DICT = {}  # SCTN204 list comments dict
FMCF_SCTN0204_LIST_DICT = {}  # SCTN204 list dict
FMFM_SCTN0101_AX_CMNT_DICT = {}  # SCTN101 FMAX defined
FMFM_SCTN0101_AX_DICT = {}  # SCTN101 FMAX defined
FMFM_SCTN0102_VAL_CMNT_DICT = {}  # SCTN102 val
FMFM_SCTN0102_VAL_DICT = {}  # SCTN102 val
FMFM_SCTN0103_DICT_CMNT_DICT = {}  # SCTN103 dict defined
FMFM_SCTN0103_DICT_DICT = {}  # SCTN103 dict defined
FMFM_SCTN0104_LIST_CMNT_DICT = {}  # SCTN201 device defines
FMFM_SCTN0104_LIST_DICT = {}  # SCTN201 device defines
FMFM_SCTN0105_LDICT_CMNT_DICT = {}  # SCTN105 ldict defined
FMFM_SCTN0105_LDICT_DICT = {}  # SCTN105 ldict defined
FMFM_SCTN0106_SCTN_CLASS_DICT = {}  # holds anything under the h5:CLASS
FMFM_SCTN0106_SCTN_DICT = {}  # everything h3 and bigger, and their immediate subs not h4-h6
FMFM_SCTN0106_SCTN_FUNC_DICT = {}  # holds anything under the h5:FUNCTIONS
FMFM_SCTN0106_SCTN_VAR_DICT = {}  # holds anything under the h5:VARIABLES
FMPSG_SCTN0900_DEF1_CMNT_DICT = {}  #
FMPSG_SCTN0900_DEF1_DICT = {}  #
FMPSG_SCTN0901_DEF2_CMNT_DICT = {}  # define the dict to hold everything in SCTN0901
FMPSG_SCTN0901_DEF2_DICT = {}  # define the dict to hold everything in SCTN0901
FMPSG_SCTN0902_DICT_CMNT_DICT = {}  # define the dict to hold everything in SCTN0902
FMPSG_SCTN0902_DICT_DICT = {}  # define the dict to hold everything in SCTN0902
FMPSG_SCTN0903_LIST_CMNT_DICT = {}  # define the dict to hold everything in SCTN0903
FMPSG_SCTN0903_LIST_DICT = {}  # define the dict to hold everything in SCTN0903
FMPSG_SCTN0904_PLATEQ_INNER_CMNT_DICT = {}  # define the dict to hold everything in SCTN0904
FMPSG_SCTN0904_PLATEQ_INNER_DICT = {}  # define the dict to hold everything in SCTN0904
FMPSG_SCTN0904_PLATEQ_OUTER_CMNT_DICT = {}  # define the dict to hold everything in SCTN0904
FMPSG_SCTN0904_PLATEQ_OUTER_DICT = {}  # define the dict to hold everything in SCTN0904
FMPSG_SCTN0905_TUPDICT_CMNT_DICT = {}  # define the dict to hold everything in SCTN0905
FMPSG_SCTN0905_TUPDICT_DICT = {}  # define the dict to hold everything in SCTN0905
FMPSG_SCTN0905_TUPDICT_TDD_DICT = {}  # define the dict to hold everything in SCTN0905
FMPSG_SCTN0906_BTNS_CMNT_DICT = {}  #
FMPSG_SCTN0906_BTNS_DICT = {}  #
FMPSG_SCTN0907_SPIN_CMNT_DICT = {}  # holds the spin element stuffs (TUPDICT)f
FMPSG_SCTN0907_SPIN_DICT = {}  # holds the spin element stuffs (TUPDICT)
FMPSG_SCTN0907_SPIN_VALUES_LIST_DICT = {}  # holds the spin element stuffs (TUPDICT)
FMPSG_SCTN0908_CHECKBOX_CMNT_DICT = {}  #
FMPSG_SCTN0908_CHECKBOX_DICT = {}  #
FMPSG_SCTN0909_TEXT_CMNT_DICT = {}  #
FMPSG_SCTN0909_TEXT_DICT = {}  #
FMPSG_SCTN090A_RADIO_CMNT_DICT = {}  #
FMPSG_SCTN090A_RADIO_DICT = {}  #
FMPSG_SCTN090B_COLUMN_CMNT_DICT = {}  #
FMPSG_SCTN090B_COLUMN_DICT = {}  #
FMPSG_SCTN090B_COLUMN_PARMS_DICT = {}  #
FMPSG_SCTN090C_APPDS_CMNT_DICT = {}  # the main app dict for this app
FMPSG_SCTN090C_APPDS_DICT = {}  # the main app dict for this app
FMPSG_SCTN090C_APPDSDICT_DICT = {}  # the main app dict+dict for this app
FMPSG_SCTN090D_FORMMAIN_CMNT_DICT = {}  #
FMPSG_SCTN090D_FORMMAIN_DICT = {}  #
FMPSG_SCTN090E_LAYOUT_CMNT_DICT = {}  #
FMPSG_SCTN090E_LAYOUT_DICT = {}  #
FMPSG_SCTN090F_WINDOW_CMNT_DICT = {}  #
FMPSG_SCTN090F_WINDOW_DICT = {}  #
FMPSG_SCTN0910_DEF3_CMNT_DICT = {}  #
FMPSG_SCTN0910_DEF3_DICT = {}  #
FMPSG_SCTN0911_COMBO_CMNT_DICT = {}  #
FMPSG_SCTN0911_COMBO_DICT = {}  #
FMPSG_SCTN0912_FRAME_CMNT_DICT = {}  #
FMPSG_SCTN0912_FRAME_DICT = {}  #
FMPSG_SCTN0913_RCMENU_CMNT_DICT = {}  #
FMPSG_SCTN0913_RCMENU_DICT = {}  #
FMPSG_SCTN0914_FORMPOPUP_CMNT_DICT = {}  #
FMPSG_SCTN0914_FORMPOPUP_DICT = {}  #
FMPSG_SCTN0915_PUDLG_CMNT_DICT = {}  #
FMPSG_SCTN0915_PUDLG_DICT_DICT = {}  #
FMPSG_SCTN0915_PUDLG_LIST_DICT = {}  #
FMPSG_SCTN0915_PUDLG_TYPE_DICT = {}  #
FMPSG_SCTN0916_CLASS_SPIN_LIST_DICT = {}  # holds the spin element stuffs (TUPDICT)
FMPSG_SCTN09FF_BTNS_ADDON_DICT = {}  #
FMPSG_SCTN09FF_BTNS_CMNT_DICT = {}  #
FMPSG_SCTN09FF_BTNS_DICT = {}  #
FMPSG_SCTN09FF_CHECKBOX_ADDON_DICT = {}  #
FMPSG_SCTN09FF_CHECKBOX_CMNT_DICT = {}  #
FMPSG_SCTN09FF_CHECKBOX_DICT = {}  #
FMPSG_SCTN09FF_CMNT_DICT = {}  #
FMPSG_SCTN09FF_COLUMN_ADDON_DICT = {}  #
FMPSG_SCTN09FF_COLUMN_CMNT_DICT = {}  #
FMPSG_SCTN09FF_COLUMN_DICT = {}  #
FMPSG_SCTN09FF_COLUMN_PARMS_DICT = {}  #
FMPSG_SCTN09FF_COMBO_ADDON_DICT = {}  #
FMPSG_SCTN09FF_COMBO_CMNT_DICT = {}  #
FMPSG_SCTN09FF_COMBO_DICT = {}  #
FMPSG_SCTN09FF_DEF_DICT = {}  # str and val defines in a class
FMPSG_SCTN09FF_DICT = {}  #
FMPSG_SCTN09FF_DICT_CMNT_DICT = {}  #
FMPSG_SCTN09FF_DICT_DICT = {}  #
FMPSG_SCTN09FF_FRAME_ADDON_DICT = {}  #
FMPSG_SCTN09FF_FRAME_CMNT_DICT = {}  #
FMPSG_SCTN09FF_FRAME_DICT = {}  #
FMPSG_SCTN09FF_FUNCTION_CMNT_DICT = {}  #
FMPSG_SCTN09FF_FUNCTION_DEF1_DICT = {}  #
FMPSG_SCTN09FF_FUNCTION_DEF2_DICT = {}  #
FMPSG_SCTN09FF_FUNCTION_DICT = {}  #
FMPSG_SCTN09FF_GROUP_DICT = {}  #
FMPSG_SCTN09FF_INIT_CMNT_DICT = {}  #
FMPSG_SCTN09FF_INIT_DEF1_DICT = {}  #
FMPSG_SCTN09FF_INIT_DEF2_DICT = {}  #
FMPSG_SCTN09FF_INIT_DEF3_DICT = {}  #
FMPSG_SCTN09FF_INIT_DICT = {}  #
FMPSG_SCTN09FF_INIT_DICTIN_DICT = {}  #
FMPSG_SCTN09FF_INIT_DICTINSTR_DICT = {}  #
FMPSG_SCTN09FF_LAYOUT_CMNT_DICT = {}  #
FMPSG_SCTN09FF_LAYOUT_DICT = {}  #
FMPSG_SCTN09FF_LIST_CMNT_DICT = {}  #
FMPSG_SCTN09FF_LIST_DICT = {}  #
FMPSG_SCTN09FF_RADIO_ADDON_DICT = {}  #
FMPSG_SCTN09FF_RADIO_CMNT_DICT = {}  #
FMPSG_SCTN09FF_RADIO_DICT = {}  #
FMPSG_SCTN09FF_RCMENU_ADDON_DICT = {}  #
FMPSG_SCTN09FF_RCMENU_CMNT_DICT = {}  #
FMPSG_SCTN09FF_RCMENU_DICT = {}  #
FMPSG_SCTN09FF_SPIN_ADDON_DICT = {}  #
FMPSG_SCTN09FF_SPIN_CMNT_DICT = {}  # holds the spin element stuffs (TUPDICT)f
FMPSG_SCTN09FF_SPIN_DICT = {}  # holds the spin element stuffs (TUPDICT)
FMPSG_SCTN09FF_TEXT_ADDON_DICT = {}  #
FMPSG_SCTN09FF_TEXT_CMNT_DICT = {}  #
FMPSG_SCTN09FF_TEXT_DICT = {}  #
FMPSG_SCTN09FF_WINDOW_CMNT_DICT = {}  #
FMPSG_SCTN09FF_WINDOW_DICT = {}  #


# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * SCTN104 _LIST_ _DEF_
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*


#
#
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * end of managed portions of FM.py
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
#
#


# <<>>
#
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# * start of unmanaged sections of FM.py
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
#
#


# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# subMyPlaceKpr
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
def subMyPlaceKpr(
		sourceStr_,
):
	# fold here ⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1
	_strToRtn_ = V.subMyPlaceKpr(sourceStr_)
	return _strToRtn_
	# fold here ⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1


# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# makeADict
# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
def makeADict(
		dictName_,
		dictComment_,
		dictItems_
):
	# fold here ⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1
	_strToRtn_ = ""
	_strToRtn_ += f"""{dictName_} = {V.OBRCE}  # {dictComment_}
{dictItems_}{V.CBRCE}{V.NEWLINE}{V.NEWLINE}{V.NEWLINE}"""
	return _strToRtn_
	# fold here ⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1


# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# sortADict
# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
def sortADict(
		dictToSort_
):
	# fold here ⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1
	_dictToRtn_ = {}
	for _thisKey_ in sorted(dictToSort_.keys(), key=lambda __KEY__: __KEY__.lower()):
		_dictToRtn_[_thisKey_] = dictToSort_[_thisKey_]
	return _dictToRtn_
	# fold here ⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1


# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# makeAList
# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
def makeAList(
		listName_,
		listComment_,
		listItems_,
		listItemCmntDict_=None,
		addQuotes_=False):
	# fold here ⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1
	_strToRtn_ = ""
	_strToRtn_ += f"""{listName_} = {V.OBRKT}  # {listComment_}{V.NEWLINE}"""
	for _thisItem_ in listItems_:
		if listItemCmntDict_ is None:
			if addQuotes_ is True:
				_strToRtn_ += f"""{V.NTAB(1)}{V.DBLQT}{_thisItem_}{V.DBLQT}"""
			else:
				_strToRtn_ += f"""{V.NTAB(1)}{_thisItem_}"""
		else:
			if addQuotes_ is True:
				_strToRtn_ += f"""{V.NTAB(1)}{V.DBLQT}{_thisItem_}{V.DBLQT},  # {listItemCmntDict_[_thisItem_]}{V.NEWLINE}"""
			else:
				_strToRtn_ += f"""{V.NTAB(1)}{_thisItem_},  # {listItemCmntDict_[_thisItem_]}{V.NEWLINE}"""
	_strToRtn_ += f"""{V.CBRKT}{V.NEWLINE}{V.NEWLINE}{V.NEWLINE}"""
	return _strToRtn_
	# fold here ⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1


# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# makeANormalTDD
# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
def makeANormalTDD(
		tupDictName_,
		tupDictItems_,
		TDDItems_
):
	# fold here ⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1
	_strToRtn_ = ""
	_strToRtn1_ = ""

	# 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱
	_strToRtn_ += f"""{M.makeAComment(f"start of {tupDictName_} structures")}
{tupDictName_}TUP = {V.OPAREN}
{tupDictItems_}{V.CPAREN}{V.NEWLINE}{V.NEWLINE}def {tupDictName_}DICT{V.OPAREN}{V.CPAREN}:
{V.NTAB(1)}return dict{V.OPAREN}{V.OPAREN}x, y{V.CPAREN} for x, y in {tupDictName_}TUP{V.CPAREN}{V.NEWLINE}{V.NEWLINE}
{tupDictName_}_TDD = {V.OBRCE}{V.NEWLINE}{TDDItems_}{V.CBRCE}{V.NEWLINE}{V.NEWLINE}{V.NEWLINE}"""
	return _strToRtn_
	# fold here ⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1


# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# makeANormalTupDict
# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
def makeANormalTupDict(
		tupDictName_,
		tupDictItems_
):
	# fold here ⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1
	_strToRtn_ = ""
	_strToRtn1_ = ""

	# 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱
	_strToRtn_ += f"""{M.makeAComment(f"start of {tupDictName_} structures")}
{tupDictName_}TUP = {V.OPAREN}
{tupDictItems_}{V.CPAREN}{V.NEWLINE}{V.NEWLINE}def {tupDictName_}DICT{V.OPAREN}{V.CPAREN}:
{V.NTAB(1)}return dict{V.OPAREN}{V.OPAREN}x, y{V.CPAREN} for x, y in {tupDictName_}TUP{V.CPAREN}{V.NEWLINE}{V.NEWLINE}{V.NEWLINE}"""
	return _strToRtn_
	# fold here ⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1


# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# makeASidecarTupDic
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
def makeASidecarTupDic(
		tupDictName_,
		tupDictItems_,
		tupDictSidecars_
):
	# fold here ⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1
	_strToRtn_ = ""
	_strToRtn1_ = ""
	_strToRtn_ += f"""{M.makeAComment(f"start of {tupDictName_} structures")}{V.NEWLINE}"""
	for _key_, _items_ in tupDictSidecars_.items():
		_strToRtn_ += f"""{tupDictName_}_{_key_}TUP = {V.OPAREN}{V.NEWLINE}{_items_}{V.CPAREN}{V.NEWLINE}{V.NEWLINE}"""
		_strToRtn1_ += f"""{V.NTAB(1)}_listToRtn_ = list((x) for x in {tupDictName_}_{_key_}TUP){V.NEWLINE}"""
	_strToRtn_ += f"""{tupDictName_}TUP = {V.OPAREN}
{tupDictItems_}{V.CPAREN}{V.NEWLINE}{V.NEWLINE}def {tupDictName_}DICT{V.OPAREN}{V.CPAREN}:
{V.NTAB(1)}_dictToRtn_ = dict{V.OPAREN}{V.OPAREN}x, y{V.CPAREN} for x, y in {tupDictName_}TUP{V.CPAREN}{V.NEWLINE}{_strToRtn1_}{V.NTAB(1)}return _listToRtn_, _dictToRtn_{V.NEWLINE}{V.NEWLINE}{V.NEWLINE}"""
	return _strToRtn_
	# fold here ⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1


# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
# makeAFullTupDict (sidecar is a single item list, or alist of strings that will be concatenated before substitution)
# * #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
def makeAFullTupDict(
		tupDictName_,
		tupDictItems_,
		tupDictSidecars_,
		tupDictParms_
):
	# fold here ⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1
# ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱
	subParmsStr_ = f"""{V.NTAB(1)}def {tupDictName_}_subParms(listIn_, tupDictParms_):
{V.NTAB(2)}_listToRtn_ = []
{V.NTAB(2)}for _thisStr_ in listIn_:
{V.NTAB(3)}for _subParm_, _replaceStr_ in tupDictParms_:
{V.NTAB(4)}_thisStr_ = _thisStr_.replace(_subParm_, _replaceStr_)
{V.NTAB(3)}_listToRtn_.append(_thisStr_)
{V.NTAB(2)}return _listToRtn_{V.NEWLINE}{V.NEWLINE}"""
# ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰
	_strToRtn1_ = ""
	_strToRtn2_ = ""
	sideCarToRtn = {}
	_parmsNames_ = ""
	_sideCar_ = {}
	# 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱
	for _subParm_, _replaceStr_ in tupDictParms_:
		_parmsNames_ += f"""{_replaceStr_}, """
	# ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1
	_parmsNames_ = _parmsNames_[:-2]
	_strToRtn1_ += f"""{M.makeAComment(f"start of {tupDictName_} structures")}{V.NEWLINE}"""
	strToRtn3_ = f"""{V.NTAB(1)}{tupDictName_}_PARMS = {V.OBRKT}{V.NEWLINE}"""
	# 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱
	for _subParm_, _replaceStr_ in tupDictParms_:
		strToRtn3_ += f"""{V.NTAB(2)}{V.OPAREN}{V.DBLQT}{_subParm_}{V.DBLQT}, {_replaceStr_}{V.CPAREN},{V.NEWLINE}"""
	# ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1
	strToRtn3_ = strToRtn3_[:-1] + f"""{V.NEWLINE}{V.NTAB(1)}{V.CBRKT}{V.NEWLINE}"""
	# 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱ 1⟱
	for _key_, _items_ in tupDictSidecars_.items():
		_strToRtn1_ += f"""{tupDictName_}_{_key_}TUP = {V.OPAREN}{V.NEWLINE}{_items_}{V.CPAREN}{V.NEWLINE}{V.NEWLINE}"""
		_strToRtn2_ += f"""{V.NTAB(1)}_listToRtn_ = list((x) for x in {tupDictName_}_{_key_}TUP){V.NEWLINE}"""
		_strToRtn2_ += f"""{V.NTAB(1)}_listToRtn_ = CF.subParms(_listToRtn_, {tupDictName_}_PARMS)"""
	# ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1 ⟰1
	# ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱ ⟱
	_strToRtn1_ += f"""{tupDictName_}TUP = {V.OPAREN}
{tupDictItems_}{V.CPAREN}{V.NEWLINE}{V.NEWLINE}def {tupDictName_}DICT{V.OPAREN}{_parmsNames_}{V.CPAREN}:{V.NEWLINE}{strToRtn3_}
{V.NTAB(1)}_dictToRtn_ = dict{V.OPAREN}{V.OPAREN}x, y{V.CPAREN} for x, y in {tupDictName_}TUP{V.CPAREN}{V.NEWLINE}"""
# ⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱⟰⟱
	_strToRtn1_ += f"""{_strToRtn2_}{V.NEWLINE}{V.NTAB(1)}return _listToRtn_, _dictToRtn_{V.NEWLINE}{V.NEWLINE}{V.NEWLINE}"""
# ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰ ⟰
	return _strToRtn1_
	# fold here ⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1


# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# doErrorItem
# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
def doErrorItem(
		message_,
		itemToError_,
		itemID_
):
	# fold here ⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1
	# *** NOT DIAGNOSTIC ***  %_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_
	print(f"""{V.NEWLINE}{message_}{V.NEWLINE}is a tuple {isinstance(itemToError_, tuple)}{V.NEWLINE}item as parsed{V.NEWLINE}{repr(itemToError_)}{V.NEWLINE}{itemID_}{V.NEWLINE}""")
	# fold here ⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1


# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# FM.FM
# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
def FM():
	# fold here ⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1⟱1
		from FM.PARSE_D import PARSE_C
		PARSE_C.parseTBGLST()
		import FM.MAKE_D
		# 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱ 2⟱
		for _module_ in sorted(os.listdir("FM/MAKE_D")):
			# 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱ 3⟱
			if (
					(_module_[0:2] != "__") and
					(_module_[-7:] != "_NEW.py") and
					(_module_[0] == "_")
			):
				_moduleToImport_ = f"""FM/MAKE_D/{_module_}"""
				# *** NOT DIAGNOSTIC ***  %_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_%_
				print(f"""making {_module_}
_moduleToImport_ {_moduleToImport_}""")
				_thisModule_ = imp.load_source("module", _moduleToImport_)
				_thisModule_.__make__()
			# ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3 ⟰3
		# ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2 ⟰2
	# fold here ⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1⟰1ff


# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# end of FM.py
# #*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
#
#
