

from FM import FM
__FILENAME__ = "FM_TBGLST_CF.py"
TBGLST = [
	(__FILENAME__, "CFVAL", FM.FMAX_NOP, "CFVAL_BEGINS",),
	(__FILENAME__, "CFVAL_____", FM.FMAX_NOP, "CFVAL_ENDS",),
	(__FILENAME__, "FMAXCF", FM.FMAX_NOP, "FMAXCF_BEGINS",),
	(__FILENAME__, "FMAXCF_SCTN0003_LAMBDA_DEF", FM.FMAXFM_SCTN0101_AX_DEF, "define a lambda function <NAC><K_EVENT_NAME><lambda str>",),
	(__FILENAME__, "FMAXCF_SCTN0003_TYPE_DEF", FM.FMAXFM_SCTN0101_AX_DEF, "define a fake type used in the translation dict <NAC><K_EVENT_NAME><TYPE>",),
	(__FILENAME__, "FMAXCF_SCTN0201_STR_DEF", FM.FMAXFM_SCTN0101_AX_DEF, "define a STR in SCTN0201 <NAC><K_EVENT_NAME><str>",),
	(__FILENAME__, "FMAXCF_SCTN0201_VAL_DEF", FM.FMAXFM_SCTN0101_AX_DEF, "define a VAL in SCTN0201 <NAC><K_EVENT_NAME><VAL>",),
	(__FILENAME__, "FMAXCF_SCTN0202_OPTIONSDICT_STR_ADD", FM.FMAXFM_SCTN0101_AX_DEF, "define a OPTNAME: 'str' in SCTN0202 <NAC><KEY><PARM><STRDEFAULT>",),
	(__FILENAME__, "FMAXCF_SCTN0202_OPTIONSDICT_VAL_ADD", FM.FMAXFM_SCTN0101_AX_DEF, "define a OPTNAME: VAL in SCTN0202 <NAC><KEY><PARM><VALDEFAULT>",),
	(__FILENAME__, "FMAXCF_SCTN0202_OPTIONS_ADD_HELP_LINE", FM.FMAXFM_SCTN0101_AX_DEF, "add a line to the help for a PARM, after the comment is automatically added<NAC><PARM><ADDONHELPLINE>",),
	(__FILENAME__, "FMAXCF_SCTN0202_OPTIONS_STR_ADD", FM.FMAXFM_SCTN0101_AX_DEF, "define a '-a[=]' in SCTN22 <NAC><PARM><KEY><VAL>",),
	(__FILENAME__, "FMAXCF_SCTN0202_OPTIONS_VAL_ADD", FM.FMAXFM_SCTN0101_AX_DEF, "define a '-a[=]' in SCTN22 <NAC><PARM><KEY><VAL>",),
	(__FILENAME__, "FMAXCF_SCTN0203_DICT_DEF", FM.FMAXFM_SCTN0101_AX_DEF, "define a dict in SCTN203 <NAC><DICTNAME><DICTMODE>",),
	(__FILENAME__, "FMAXCF_SCTN0203_DICT_VS_ADD", FM.FMAXFM_SCTN0101_AX_DEF, "define a dict STR in SCTN203 <NAC><DICTNAME><STR>",),
	(__FILENAME__, "FMAXCF_SCTN0203_DICT_VV_ADD", FM.FMAXFM_SCTN0101_AX_DEF, "define a dict VAL in SCTN203 <NAC><DICTNAME><VAL>",),
	(__FILENAME__, "FMAXCF_SCTN0204_LIST_DEF", FM.FMAXFM_SCTN0101_AX_DEF, "define a list in SCTN204 <NAC><LISTNAME>",),
	(__FILENAME__, "FMAXCF_SCTN0204_LIST_STR_ADD", FM.FMAXFM_SCTN0101_AX_DEF, "define a list STR in SCTN204 <NAC><LISTNAME><STR>",),
	(__FILENAME__, "FMAXCF_SCTN0204_LIST_VAL_ADD", FM.FMAXFM_SCTN0101_AX_DEF, "define a VAL in a list in SCTN204 <NAC><LISTNAME><VAL>",),
	(__FILENAME__, "FMAXCF_____", FM.FMAX_NOP, "FMAXCF_ENDS",),
	(__FILENAME__, "FMCF", FM.FMAX_NOP, "FMCF_BEGINS",),
	(__FILENAME__, "FMCF_SCTN0003_TYPE_CMNT_DICT", FM.FMAXFM_SCTN0103_DICT_DEF, "SCTN009 types comments",),
	(__FILENAME__, "FMCF_SCTN0003_TYPE_DICT", FM.FMAXFM_SCTN0103_DICT_DEF, "SCTN003 types",),
	(__FILENAME__, "FMCF_SCTN0201_DEF_CMNT_DICT", FM.FMAXFM_SCTN0103_DICT_DEF, "SCTN201 defines comments dict",),
	(__FILENAME__, "FMCF_SCTN0201_DEF_DICT", FM.FMAXFM_SCTN0103_DICT_DEF, "SCTN201 defines dict",),
	(__FILENAME__, "FMCF_SCTN0202_OPTIONSDICT_CMNT_DICT", FM.FMAXFM_SCTN0103_DICT_DEF, "SCTN202 OPTIONSDICT comments dict",),
	(__FILENAME__, "FMCF_SCTN0202_OPTIONSDICT_DICT", FM.FMAXFM_SCTN0103_DICT_DEF, "SCTN202 OPTIONSDICT",),
	(__FILENAME__, "FMCF_SCTN0202_OPTIONSHELPDICT_DICT", FM.FMAXFM_SCTN0103_DICT_DEF, "SCTN202 OPTIONS HELPDICT",),
	(__FILENAME__, "FMCF_SCTN0202_OPTIONS_CMNT_DICT", FM.FMAXFM_SCTN0103_DICT_DEF, "SCTN202 OPTIONS comments dict",),
	(__FILENAME__, "FMCF_SCTN0202_OPTIONS_DICT", FM.FMAXFM_SCTN0103_DICT_DEF, "SCTN202 OPTIONS dict",),
	(__FILENAME__, "FMCF_SCTN0203_DICT_CMNT_DICT", FM.FMAXFM_SCTN0103_DICT_DEF, "SCTN203 dict comments dict",),
	(__FILENAME__, "FMCF_SCTN0203_DICT_DICT", FM.FMAXFM_SCTN0103_DICT_DEF, "SCTN203 dict dict",),
	(__FILENAME__, "FMCF_SCTN0204_LIST_CMNT_DICT", FM.FMAXFM_SCTN0103_DICT_DEF, "SCTN204 list comments dict",),
	(__FILENAME__, "FMCF_SCTN0204_LIST_DICT", FM.FMAXFM_SCTN0103_DICT_DEF, "SCTN204 list dict",),
	(__FILENAME__, "FMCF_____", FM.FMAX_NOP, "FMCF_ENDS",),
]

#
