	(("CF, "FM/FM_TBGLST_CF_NEW.py"), "CFVAL", FM.FMAX_NOP, "CFVAL_BEGINS",),
	(("CF, "FM/FM_TBGLST_CF_NEW.py"), "CFVAL_____", FM.FMAX_NOP, "CFVAL_ENDS",),
	(("CF, "FM/FM_TBGLST_CF_NEW.py"), "FMAXCF", FM.FMAX_NOP, "FMAXCF_BEGINS",),
	(("CF, "FM/FM_TBGLST_CF_NEW.py"), "FMAXCF_SCTN0003_LAMBDA_DEF", FM.FMAXFM_SCTN0101_AX_DEF, "define a lambda function <NAC><K_EVENT_NAME><lambda str>",),
