

__CLASS__ = "POPUP_ALERT"
__MODULE_NAME__ = "PSG"
__FILENAME__ = "FM_TBGLST_PSG_POPUP_ALERT.py"
TBGLST = [
	((__MODULE_NAME__, __FILENAME__), ("CLASS_POPUP_ALERT", FMAXPSG_SCTN09FF_CLASS_DEF, __CLASS__, "start the POPUP_ALERT class",),),
	((__MODULE_NAME__, __FILENAME__), ("POPUP_ALERT_COL0100", FMAXPSG_SCTN09FF_CLASS_COLUMN_DEF, __CLASS__, "COL01", "comment",),),
]
