#!/usr/bin/env zsh


mv FM_TBGLST_CF.py FM_TBGLST_CF_OLD.py
mv FM_TBGLST_FM.py FM_TBGLST_FM_OLD.py
mv FM_TBGLST_PSG.py FM_TBGLST_PSG_OLD.py
mv FM_TBGLST_CF.py FM_TBGLST_CF_OLD.py
mv FM_TBGLST_CF.py FM_TBGLST_CF_OLD.py

#
